### PR TITLE
Added Github Actions automatic build

### PR DESCRIPTION
**Pull request by Turupawn**
I added an automatic build for Linux. I can also try to add automatic builds and releases for MacOS and Windows. It can help to quickly know if new warnings and incompatibilities between platforms are made on each PR. What do you guys think? Has this been discussed before? Also is there an IRC or Discord where the devs hang out so I can have a better understating of your workflow so I'm able to figure out how I can help?

such actions

### CODE REVIEW

**Comment by patricklodder** [comment]
Thanks you.

We already have a CI running with Travis. We may of course consider changing platforms in the future, for now, travis serves our needs.

**Comment by patricklodder** [comment]
This has been cherry-picked into #2320. Thank you!

**Comment by mmicael1** [comment]
@patricklodder Shouldn't we let the .travis.yml file for the developers who have a Travis Paid Plan?

**Comment by patricklodder** [comment]
> @patricklodder Shouldn't we let the .travis.yml file for the developers who have a Travis Paid Plan?

You can put your own if you really want to use another CI on your fork

**Pull request closed without merging**
