### PR TITLE
Update block generation constants in wallet_bumpfee

### PR DESCRIPTION
**Pull request by rnicoll**
* Remove early block generation by RBF node (introduced earlier in 1.21 cycle).
* Increase block generation values from original test, to meet Dogecoin coinbase maturity requirements.

### CODE REVIEW

**Comment by rnicoll** [comment]
Alternative to #2115

**Comment by carloviscusi** [comment]
@rnicoll  I like the updates. Is there an easier way to contact you ? To discuss development stages & make this easier to communicate ?

**Comment by rnicoll** [comment]
@carloviscusi GitHub is generally good, because I don't want to end up as a communication hub. If you're looking for tasks we need help with, please see https://github.com/dogecoin/dogecoin/projects/4 . https://github.com/dogecoin/dogecoin/pull/2111 (the contributions guide) might also be helpful

**Comment by rnicoll** [comment]
Closing & reopening to trigger Travis

**Comment by kaidhar** [comment]
Hey Ross, is this still an issue? If it's still timing out I can take a look at it as well.

**Pull request closed without merging**
