### PR TITLE
Add install_db5.sh and update build-unix

### PR DESCRIPTION
**Pull request by vertiond**
This PR adds install_db4.sh from upstream and updates it for db5.  I tested only on unix and thus have updated the build-unix doc.

### CODE REVIEW

**Comment by patricklodder** [comment]
@vertiond I have added a patch to allow using the bdb autodetect overrides in vertiond#1

**Comment by vertiond** [comment]
Tested ACK

**Comment by patricklodder** [comment]
@vertiond could you please rebase to get rid of the inner non-linear commits (your merge of my PR)? After that it's good to go for me. (tested again today, works like a charm)

**Comment by vertiond** [comment]
Eh will fix this

**Comment by rnicoll** [comment]
Looks good, running Gitian Linux build just to be sure

**Review by rnicoll — APPROVED** [review]

**Comment by rnicoll** [comment]
Only did Linux (and just to ensure it built), but in case anyone wants to match:


```
dadc65326eaa0f824c86b4991b27af24682a8a441f238f00b0444227323fe184  dogecoin-1.14.6-aarch64-linux-gnu-debug.tar.gz
fe71a9f0c810f657a79fca62d0ea4fed41df27202f8d6029389cb05a287e8516  dogecoin-1.14.6-aarch64-linux-gnu.tar.gz
838d0b71e77a896cfa0aeec25f0ac64ddb133719b23978d2875658d69b3c1173  dogecoin-1.14.6-arm-linux-gnueabihf-debug.tar.gz
efd49c62c74d5bd16d1663e77e6dd9062cba47185b1c60c9103f30cbba68fc81  dogecoin-1.14.6-arm-linux-gnueabihf.tar.gz
7af9e539f889ff344f0dc4e2ad706e0ef38502afddc13ab75fd81b8753d90043  dogecoin-1.14.6-i686-pc-linux-gnu-debug.tar.gz
312f2456dcdfe5416531afe5e20bd672c3affcb74d0f8f74e1feb214d5ddb95b  dogecoin-1.14.6-i686-pc-linux-gnu.tar.gz
a7e5b6c3b600c8b179e12ac9ea1c315dd154f40166fee7f79d810298b21d0cee  dogecoin-1.14.6-x86_64-linux-gnu-debug.tar.gz
fdf5e601e90bb3fced3726da07941e4aa78ffd2540be3f794dc4c106695f1015  dogecoin-1.14.6-x86_64-linux-gnu.tar.gz
570d47fac09bc6ad683dbb453f464e68b2968261eb6e082f1096fc50c188d0e1  src/dogecoin-1.14.6.tar.gz
a90a08e4a6f22a6a13e646771bed8385c928a0959c0b54cac6cc84b071618311  dogecoin-linux-1.14-res.yml
```

**Comment by patricklodder** [comment]
mine:

```
dadc65326eaa0f824c86b4991b27af24682a8a441f238f00b0444227323fe184  dogecoin-1.14.6-aarch64-linux-gnu-debug.tar.gz
fe71a9f0c810f657a79fca62d0ea4fed41df27202f8d6029389cb05a287e8516  dogecoin-1.14.6-aarch64-linux-gnu.tar.gz
838d0b71e77a896cfa0aeec25f0ac64ddb133719b23978d2875658d69b3c1173  dogecoin-1.14.6-arm-linux-gnueabihf-debug.tar.gz
efd49c62c74d5bd16d1663e77e6dd9062cba47185b1c60c9103f30cbba68fc81  dogecoin-1.14.6-arm-linux-gnueabihf.tar.gz
7af9e539f889ff344f0dc4e2ad706e0ef38502afddc13ab75fd81b8753d90043  dogecoin-1.14.6-i686-pc-linux-gnu-debug.tar.gz
312f2456dcdfe5416531afe5e20bd672c3affcb74d0f8f74e1feb214d5ddb95b  dogecoin-1.14.6-i686-pc-linux-gnu.tar.gz
a7e5b6c3b600c8b179e12ac9ea1c315dd154f40166fee7f79d810298b21d0cee  dogecoin-1.14.6-x86_64-linux-gnu-debug.tar.gz
fdf5e601e90bb3fced3726da07941e4aa78ffd2540be3f794dc4c106695f1015  dogecoin-1.14.6-x86_64-linux-gnu.tar.gz
570d47fac09bc6ad683dbb453f464e68b2968261eb6e082f1096fc50c188d0e1  src/dogecoin-1.14.6.tar.gz
37a64d3cfb8145e2932b4f57093bb5cd5869e0a320444f17d7c06d90d140a80c  dogecoin-linux-1.14-res.yml
```

all good.

**Review by CryptoUnchained — COMMENTED** [review]
Can't tell you how much I appreciate everyone's hard work in this upgrade

**Pull request merged**
