### PR TITLE
Improve energy efficiency of Dogecoin 

### PR DESCRIPTION
**Pull request by erubboli**
This PR **massively** improve energy efficiency of Dogecoin as requested by Elon Musk :

https://twitter.com/elonmusk/status/1392974251011895300

### CODE REVIEW

**Comment by bobthegrownup** [comment]
Just use Solana instead

**Comment by PapaOscar90** [comment]
Changing a copyright date of the underlying hash, adding/changing a few tests, and code formatting does not improve energy efficiency. This seems to be push for the hype train. 

In the future, please also keep in mind commits are atomic changes. Having one enormous commit only causes confusion, which may be the intent here.

**Comment by willwooten** [comment]
ACK

**Comment by Moun1r1** [comment]
0 Energy improvement, nice joke

**Comment by svallier** [comment]
2427 files changed ^^.

The were aware about elon statement since 6 months lol

**Comment by hirishh** [comment]
@PapaOscar90 you must be the fun guy at parties.

ACK

**Review by IvanTelia — APPROVED** [review]

**Comment by langerhans** [comment]
teehee you did a funny

**Pull request closed without merging**
