### PR TITLE
Adapt Bitcoin to Dogecoin

### PR DESCRIPTION
**Pull request by rnicoll**
This should bring the dev branch into sync with everything we need for Dogecoin. I've rebased this a few times to get the changes down to a cleaner set, so this won't match 1.10-dev 1:1 for commits, but the result should be the same.

### CODE REVIEW

**Comment by rnicoll** [comment]
Not sure why the OS X tests are failing, to be honest mostly because I don't look at Travis much. Ideas?

**Comment by langerhans** [comment]
That's because 06fdc18 didn't apply fully as it was in #1212 . The Calls to `sudo apt-get` have to be removed and the PACKAGES line cleaned up in the OS X config.

**Comment by patricklodder** [comment]
OSX fails on paper wallet print code now:
```
libtool: link: /home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/native/bin/ccache /home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/native/bin/clang++ -target x86_64-apple-darwin11 -mmacosx-version-min=10.7 --sysroot /home/travis/build/dogecoin/dogecoin/depends/SDKs/MacOSX10.9.sdk -mlinker-version=241.9 -pipe -O2 -Wstack-protector -fstack-protector-all -fPIE -fvisibility=hidden -D_THREAD_SAFE -pthread -Wl,-headerpad_max_install_names -pie -Wl,-dead_strip -o qt/bitcoin-qt qt/qt_bitcoin_qt-bitcoin.o qt/macdockiconhandler.o qt/macnotificationhandler.o -D_THREAD_SAFE -Wl,-bind_at_load  -L/home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/lib qt/libbitcoinqt.a libbitcoin_server.a libbitcoin_wallet.a libbitcoin_cli.a libbitcoin_common.a libbitcoin_util.a crypto/libbitcoin_crypto.a univalue/libbitcoin_univalue.a ./leveldb/libleveldb.a ./leveldb/libmemenv.a -lboost_system-mt -lboost_filesystem-mt -lboost_program_options-mt -lboost_thread-mt -lboost_chrono-mt -lqcocoa -framework DiskArbitration -framework IOKit -framework Foundation -framework CoreServices -framework ApplicationServices -framework CoreFoundation -framework Cocoa -framework OpenGL -framework AGL -framework Carbon -lQt5PlatformSupport -framework Security -framework SystemConfiguration -lQt5Network -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lqtharfbuzzng -L/home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/plugins/platforms -L/home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/plugins/printsupport -framework AppKit -lQt5DBus -lQt5Core -lqtpcre -lm /home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/lib/libqrencode.a -lpthread /home/travis/build/dogecoin/dogecoin/depends/x86_64-apple-darwin11/lib/libprotobuf.a -lz -ldb_cxx-5.1 -lssl -lminiupnpc secp256k1/.libs/libsecp256k1.a -lcrypto -pthread
clang: warning: argument unused during compilation: '-pthread'
clang: warning: argument unused during compilation: '-pie'
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "QPrinter::~QPrinter()", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrinter::newPage()", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrinter::QPrinter(QPrinter::PrinterMode)", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QAbstractPrintDialog::setPrintRange(QAbstractPrintDialog::PrintRange)", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrinter::setPaperSize(QPagedPaintDevice::PageSize)", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrinter::setOrientation(QPrinter::Orientation)", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrinter::setFullPage(bool)", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrintDialog::QPrintDialog(QPrinter*, QWidget*)", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
  "QPrinter::pageRect() const", referenced from:
      PaperWalletDialog::on_printButton_clicked() in libbitcoinqt.a(qt_libbitcoinqt_a-utilitydialog.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [qt/bitcoin-qt] Error 1
make[1]: Leaving directory `/home/travis/build/dogecoin/dogecoin/bitcoin-x86_64-apple-darwin11/src'
make: *** [src/qt/bitcoin-qt] Error 2```

**Comment by rnicoll** [comment]
Not a clue what's gone wrong this time, the obvious parts that deal with Qt dependencies all look like they've been applied, to me. Anyone got any ideas?

**Comment by rnicoll** [comment]
As @langerhans has suggested, it's definitely the QT5 patch that's breaking this. I'll try figuring out a solution over the weekend

**Comment by rnicoll** [comment]
For reference, the problem appears to be that Qt 5.5 will not compile with print support without CUPS. Need to either address that with the Qt devs or add CUPS.

**Comment by patricklodder** [comment]
Did some research re: osx printing, found this note: http://wiki.qt.io/Qt-Printing#Mac_OSX_Differences

**Comment by langerhans** [comment]
So, I found this: https://github.com/dogecoin/dogecoin/blob/1.10.2-dev/depends/patches/qt/mac-qmake.conf#L3

But removing the line I end up with:
```
checking for static Qt plugins: -lqcocoa... no
configure: WARNING: Could not resolve: -lqcocoa; bitcoin-qt frontend will not be built
checking whether to build Bitcoin Core GUI... no (Qt5)
```

There is also https://github.com/dogecoin/dogecoin/blob/1.10.2-dev/depends/packages/qt.mk#L29
But this is there on master too :/

**Pull request closed without merging**
