### PR TITLE
Fix JSON output rounding errors, add integer output

### PR DESCRIPTION
**Pull request by linuxion**
Hello,

While building [Blockchair Dogecoin explorer](https://blockchair.com/dogecoin) we discovered that all the existing explorers contain one particular bug.

Processing float number from JSON gives incorrect value because most programming languages round it off incorrectly. Blockchain explorers show negative fees due to the wrong values. See example of how Dogechain.info shows [negative fees](https://dogechain.info/tx/beda0098b99485a0824ea5b46d4562d901b35563e41a453957747a9f6c08a5d2), Blockcypher.com shows [incorrect output value](https://live.blockcypher.com/doge/tx/beda0098b99485a0824ea5b46d4562d901b35563e41a453957747a9f6c08a5d2/).

[Same transaction](https://blockchair.com/dogecoin/transaction/beda0098b99485a0824ea5b46d4562d901b35563e41a453957747a9f6c08a5d2) after the fix.

Example 1:
Command:
`./dogecoin-cli getrawtransaction 45714460376a8da932f88e130c4300684138f9120c315681014db950690ed291 1`
Value output from JSON:
`"value": 1020495.46420877`
Parsing result: 
`"value": 1020495.46420880`.

After parsing JSON most programming languages convert `1020495.46420877` to `1020495.46420880`

Example 2:
Command:
`./dogecoin-cli getrawtransaction beda0098b99485a0824ea5b46d4562d901b35563e41a453957747a9f6c08a5d2 1`
Value output from JSON:
`"value": 99850808.70669570`
Parsing result:
`"value": 99850808.70669571`

Same issue here.

E.g. run this from the console:
```
> php -r "echo 99850808.70669570;"
99850808.706696
```
Most wallets and exchanges use JSON as preferred output format so the most of them have incorrect values. I don't think that serious monetary problems can appear from this, but anyway we should fix it.

The fix includes `-rpcintegers` command line argument which toggles RPC to return values in `uint64_t` (satoshi). It can hold up to 18,446,744,073,709,551,615 satoshi = ~184,4 billion Doge which will be generated in April 2032. 

CC @Har01d discovered the bug.

P.S. I compiled it only with `./configure --disable-wallet` flag so it would be great if someone could test the wallet.

### CODE REVIEW

**Comment by DR-BoneZ** [comment]
The original rpc values produced are accurate, and conformant to the json standard. Just because JavaScript uses IEEE7 floating point in it's number representation doesn't mean json has to be parsed that way. You could instead deserialize the values into an actual decimal based arbitrary precision representation.

**Comment by patricklodder** [comment]
So I [rebased this against the new 1.14.3-dev](https://github.com/patricklodder/dogecoin/tree/pr-1567) and [there are some issues](https://travis-ci.org/github/patricklodder/dogecoin/builds/711000752).

I'm not against having an option to work around float issues that occur in many higher-level languages (not just JS) and the solution could be uint in Koinu (Dogecoin equivalent unit of "satoshi".) Perhaps BigDecimal-as-a-string would be more intuitive; as I somewhat worry that integrators would take the nice uint64 and then implicitly cast it to a double when dividing it by 1e8. Open to thoughts.

To move this particular PR forward, we need:
1. rebase
2. make existing unit tests pass
3. create some tests (at the very least a test in `qa/rpc-tests`)

**Comment by orhtej2** [comment]
I'd say there's something off with this PR, the only commit relevant to the issue seems to be be59da799685500753c6f2b1b678c9adfc8130ca

**Comment by patricklodder** [comment]
> I'd say there's something off with this PR, the only commit relevant to the issue seems to be [be59da7](https://github.com/dogecoin/dogecoin/commit/be59da799685500753c6f2b1b678c9adfc8130ca)

Correct, it needs a rebase.

**Pull request closed without merging**
