### PR TITLE
test: Fixup replace-by-fee values

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by rnicoll** [comment]
Opening early while I work out the remaining test case.

**Review by patricklodder — COMMENTED** [review]
Can we move this from extended tests to standard tests so we get CI coverage? Otherwise ack (tested locally on Ubuntu 20.04)

**Comment by rnicoll** [comment]
@patricklodder Done

**Review by patricklodder — APPROVED** [review]
ACK. tested on Ubuntu 20.04.

**Pull request merged**
