### PR TITLE
Fix depends mk scripts for a successful (initial) Dogecoin compatible build

### PR DESCRIPTION
**Pull request by langerhans**
Title says all. Edited version in accordance to our current ones. I figure there will be lot of changes to these files later down the sheet anyway, but this makes it usable for now. Comparison tool is left out since it's not compatible with dogecoin anyway (anyone wants it? ;D ).

### CODE REVIEW

**Comment by patricklodder** [comment]
Alright, found 2 non-blocking issues:
1. pull-tester gets triggered somewhere
2. some trayicon issues on ubuntu 14.10

We'll revisit those later (as the label indicates) to not block the queue right now

**Comment by langerhans** [comment]
I will take a look at them, this here is not really holding up the queue as it can easily be rebased.

**Comment by langerhans** [comment]
1. Commented out the comparison tool trigger in `config.site.in`
2. See bitcoin/bitcoin#5260 which refers to the same issue being an upstream Qt bug. So not much luck there until that gets fixed.

**Comment by patricklodder** [comment]
```make check``` works for me now. Understand re: icon bug, i'm rather sure i saw it on some other coins with newer UI too (btsx if i remember correctly.)

ACK :)

**Pull request merged**
