### PR TITLE
Fixed typos and enhanced messages for Polish translation

### PR DESCRIPTION
**Pull request by pmzajaczkowski**
Fixed multiple typos (duplicated spaces, misspelled words, etc.) and introduced new messages which were previously not translated to Polish. Also removed couple of redundant numerusforms.

### CODE REVIEW

**Comment by patricklodder** [comment]
closing & opening to re-trigger CI against 1.14.4-dev

**Review by patricklodder — DISMISSED** [review]
This is okay with me. Since my Polish is not what it used to be, I'll wait 48h with the merge in case someone has an opinion about the actual translation

**Review by sruPL — CHANGES_REQUESTED** [review]
dogecoinowym - dogecoin'owym (seems better to use apostrophe for English words)

<translation>Przycinanie: ostatnia synchronizacja portfela jest za danymi. Mus**z**isz użyć -reindex (pobrać cały ciąg bloków ponownie w przypadku przyciętego węzła)</translation>

Musisz - typo

"Przycinanie: ostatnia synchronizacja portfela jest za danymi."

Suggesting change for:

Przycinanie: ostatnia synchronizacja portfela wykracza poza przycięte dane 

Because "jest za danymi" can sound confusing and not straightforward.

I see also several dogecoin noun declensions, I would use apostrophe for all of "dogecoin" forms in Polish.

**Comment by pmzajaczkowski** [comment]
> dogecoinowym - dogecoin'owym (seems better to use apostrophe for English words)
> (...)
> I see also several dogecoin noun declensions, I would use apostrophe for all of "dogecoin" forms in Polish.

I've done some research on that topic and it seems that apostrophes are intended for words ending with unpronounceable/mute endings (like 'e' in 'iPhone'). In such cases you write iPhone'a. But you should not use apostrophes in words which are easily pronounceable in a declinated form (like iPoda).

See:
- http://wittamina.pl/apostrof-w-zlym-miejscu/
- https://websoul.pl/blog/jak-poprawnie-odmieniac-slowa-fanpage-blog-facebook-twitter-i-google
- https://trudnyjezykpolski.pl/apostrof-w-wyrazach-obcych/

Because of that I haven't used apostrophes in Dogecoin-related words. Let me know what you think, @sruPL.

Regarding the rest of changes - I have unified the case in translations (dogecoin -> Dogecoin), fixed the typo and applied your suggestion of the change.

**Comment by sruPL** [comment]
Looks fine to me, I guess we learn new things every day :)

**Review by patricklodder — APPROVED** [review]
ACK.

Since the `.idea` addition to `.gitignore` in a separate commit, I'm ok with keeping it that way.

**Pull request merged**
