### PR TITLE
Added 'moon' value in GetInfo()

### PR DESCRIPTION
**Pull request by IeuanG**
Just tested, works fine :+1:

### CODE REVIEW

**Comment by rnicoll** [comment]
+UntestedACK

@langerhans ?

**Comment by langerhans** [comment]
utACK, but would like to discuss the term "to the server" there. Are we seing this method only used in daemon and therefore mostly server applications, or do we see Dogecoin Core as client to the Dogecoin network? In latter case we'd have to use a different term there.

**Comment by IeuanG** [comment]
@langerhans Does the term 'to the Dogecoin core' suffice?

**Comment by langerhans** [comment]
Dogecoin **C**ore :)

**Comment by IeuanG** [comment]
Updated @langerhans

**Comment by patricklodder** [comment]
So, under which conditions would we have to patch this to `false`? :)

**Comment by langerhans** [comment]
@patricklodder Probably when safe mode is triggered ;)  
(And in all seriousness, leaving this open until the other changes are merged that touch this file so we don't get too many conflicts in the meantime)

**Comment by rnicoll** [comment]
As we're apparently now actually putting a Dogecoin on the moon, could define this to match whether there is a Dogecoin on the moon. For 1.10.1 though I think, just in case anyone's parsing JSON badly and we break something. Thoughts?

**Pull request closed without merging**
