### PR TITLE
RPC row added to "such ports" table

### PR DESCRIPTION
**Pull request by daank-c**
The "RPC" row in the "Such Ports" table was missing. Row has been added to the "such ports" table.

### CODE REVIEW

**Comment by daank-c** [comment]
First time submitting a PR, be gentle. :p

**Review by patricklodder — APPROVED** [review]
utACK. Thank you!

**Comment by patricklodder** [comment]
> First time submitting a PR, be gentle.

The only thing I had to change was that you were requesting a pull against master and instead it needs to go against the dev branch. This is the "base" selector when you open a PR. Otherwise, great! Thanks!

**Comment by daank-c** [comment]
>it needs to go against the dev branch.

I was toying with the idea of sending that to `dev.1.14.7` , but came to second guess myself because it was less a "development" and more of a "typo". 

So i'll ask:  is it best practice to assume that all PRs should be directed at the next version that is still under development?

**Comment by patricklodder** [comment]
> So i'll ask: is it best practice to assume that all PRs should be directed at the next version that is still under development?

Even better: no need to practice or assume, it's [documented in the readme](https://github.com/dogecoin/dogecoin#branches) 😁

We'll simply not merge anything to master as long as we have this branching strategy. The strategy is subject to change after 1.21 becomes master, but until then, master is only mutable on release (so that we can fast-forward it when we do minor releases and keep things clean.) ❤️

**Comment by daank-c** [comment]
> Even better: no need to practice or assume, it's [documented in the readme](https://github.com/dogecoin/dogecoin#branches) 😁

LOL 😅

**Pull request merged**
