### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Computer-Genuis**
some places refer to doge as xdg

### CODE REVIEW

**Comment by Sporklin** [comment]
Our four letter DOGE is standard to most exchanges for listing purposes to avoid this exact issue. 

It was until recently the unofficial ISO code relating until it was found to be conflicting there with existing connections. References to XDG in any do not exist in any official manner as the currency abbreviation exists in the space already which is not attached to Dogecoin. This is part of why before the standard moved to four letters, DogeCoin was able to be listed as DOGE in majority of usage outlets.

This is perhaps why it has never been added, and why I do not think it should be.

**Comment by Computer-Genuis** [comment]
Why not add a fast facts section? Also, why not also put dogecoin in the brackets?

**Comment by Computer-Genuis** [comment]
I changed it

**Comment by Computer-Genuis** [comment]
Many newcomers to bitcoin think bitcoin core and bitcoin are different. The same could happen with dogecoin

**Pull request closed without merging**
