### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Tracachang**
Since Dogecoin will have a big upgade with the proof of wow which is a more ecofriendly way to mine, README should be updated too.

### CODE REVIEW

**Review by huy-springlabs — APPROVED** [review]

**Comment by stoiclord** [comment]
>*figthing 

please spell it correctly

>it even help figthing the climate change using this new techonology

did you just buy this meme coin two weeks back? As long as Doge has PoW as its consensus mechanism, it's not going to be environmentally friendly.

**Comment by Tracachang** [comment]
> > *figthing
> 
> please spell it correctly
 
done.

And yes, proof of wow it is super eco friendly, if not ask elon, he will explain you.

**Comment by willwooten** [comment]
consensus among devs seems to be "Proof-of-Woof"

**Comment by delbonis** [comment]
@stoiclord 

I just want to clarify a misconception for everyone here:

>As long as Doge has PoW as its consensus mechanism, it's not going to be environmentally friendly.

Proof-of-work is not "not environmentally friendly".  Proof-of-work is more or less completely neutral in that regard.  *Greenhouse gas emissions* are what is not environmentally friendly.  Proof-of-work requires large amounts of power generation, and power generation *generally* involves burning fossil fuels and releasing greenhouse gases, *though not necessarily*.  If every cryptocurrency miner in the world relied on clean renewables (and/or nuclear perhaps), then proof-of-work as practiced would be perfectly fine and completely ethically sound.

Many projects will *never* move away from proof-of-work, because it is relatively simple to implement and has very well-understood and accepted economics and assumptions (compared to the alternatives).  The effort that people should be expending on the matter of the current environmental impact cryptocurrencies would be much better spent on advocating for transitioning the energy supply in the nations we live in towards renewables.  This is beneficial to *everyone* involved, including (and primarily, even) the people that don't have anything to do with cryptocurrencies.  The outrage against cryptocurrencies for their indirect impact on the environment comes from position good faith but it is a misinterpretations of the underlying issues and is misdirected in the ends it is advocating for.

**Comment by Tracachang** [comment]
> consensus among devs seems to be "Proof-of-Woof"

You are right, updated

**Review by EverythingWillBeCode — APPROVED** [review]

**Review by willwooten — APPROVED** [review]

**Comment by rnicoll** [comment]
Sorry I need to clear up the funny PRs so we can find the ones we need to apply, but appreciate the enthusiasm.

**Pull request closed without merging**
