### PR TITLE
Apply BIP 66 changes to 1.8.3 client

### PR DESCRIPTION
**Pull request by rnicoll**
Needs more testing, but opening early for code review

### CODE REVIEW

**Comment by patricklodder** [comment]
PR'd against your PR branch :)

**Comment by patricklodder** [comment]
Also found this: https://github.com/rnicoll/dogecoin/blame/1.8.3-bip66/src/main.cpp#L2823-L2825

from 1bf5913

We'll need to get rid of that but this can potentially hurt :/

**Comment by rnicoll** [comment]
We should cut the v2 check (as 1.10 does) and the "return false;" is then only used to enforce v3.

I've already seen what happens if you try enforcing v2 on supermajority, it doesn't go well, had that with 1.10 in early testing.

**Comment by patricklodder** [comment]
I'll create a separate PR for that.

**Comment by patricklodder** [comment]
@rnicoll, @langerhans please read my proposal for fixing the IsSuperMajority issue carefully at https://github.com/rnicoll/dogecoin/pull/6

**Comment by patricklodder** [comment]
I've synched testnet post-softfork successfully with this.

If @rnicoll could rebase this to get rid of the merge-commit at 0a59c7c, then ACK.

**Comment by rnicoll** [comment]
Confirmed fully syncs against the v3 fork on testnet, up to block 736,541.

**Comment by patricklodder** [comment]
ACK.

@langerhans i think since this introduces code from both rnicoll and myself, the final decision to merge is yours :)

**Comment by langerhans** [comment]
Looks good

**Pull request merged**
