### PR TITLE
Security enhancements for preventing two kinds of attacks

### PR DESCRIPTION
**Pull request by alamshafil**
This PR addresses #2735. (https://github.com/bitcoin/bitcoin/pull/14897 and https://github.com/bitcoin/bitcoin/pull/19988)

I have cherry-picked https://github.com/bitcoin/bitcoin/pull/14897 and resolved the conflicts. Working to cherry-pick https://github.com/bitcoin/bitcoin/pull/19988 and resolve all the conflicts.

Since I haven't cherry-picked both Bitcoin PRs, I have opened this PR as a draft. If anything looks wrong as of right now, feel free to comment.

### CODE REVIEW

**Comment by patricklodder** [comment]
Another day, another waking up to a sweet surprise. Thank you! 😁

I'll go over this, and will have some suggestions for testability.

I have some considerations about doing #19988 too because it is a huge change and has a lot of dependencies if we want a clean merge, so I am unsure if we can be deliver this at proper quality if we pull that one in right now.

I've been working on a clean pull earlier this year but the problem is really to get a clean, testable change, while at the same time, we also need to change some of the mechanics in there. One of the bigger problems is that we cannot differentiate between "txid peers" and "wtxid peers" (we won't have any of the latter) so our attack surface is different than that of Bitcoin Core: we have no fallback to that transaction serialization format.

-----

Instead, we could mitigate the problem with the limit of 100 in-flight transactions with allowing this parameter to be configured. The risk of hardcoding the limit with `MAX_PEER_TX_IN_FLIGHT ` is that we have lots of nodes using lower-end connectivity that may simply need a larger buffer, and at the same time Dogecoin node operators rarely self-compile so we cannot say "just tune it by changing the constant".

Perhaps, we can do it like this:

1. We optimize this PR
2. We add some tests
3. We amend to allow the hardcoded 100 in-flight txs to be configured by a node operator (with a loud "caution" and explanation marks around it)

I'm fine with doing the latter on a separate PR so that we don't get blocked by that.

Looking for feedback on this, am open for better ideas.

**Comment by patricklodder** [comment]
I have PR'd the rpc-test at https://github.com/alamshafil/dogecoin/pull/1

**Review by patricklodder — COMMENTED** [review]
Would greatly benefit to rebase this on top of #2986 - which got merged into 1.14.6-dev recently, and then we can write some tests to make sure the vulnerability is taken care of.

**Comment by patricklodder** [comment]
I see some qa failures that are caused by logic for the "cached chain" in RPC tests. I've seen that happen in another change - will propose a fix to that separately.

**Comment by patricklodder** [comment]
@alamshafil if you rebase this on top of current 1.14.6-dev now that #2994 is merged, cached-chain tests should no longer fail.

**Comment by patricklodder** [comment]
I'm in the process of writing a qa test for this, but since no user-facing strings are changed, I'm postponing further work on that until next week, because other PRs are on the critical path for the 06/19 deadline.

**Comment by patricklodder** [comment]
Functionally, this works, but we're introducing new bugs with this, so this is becoming high risk.

See for example https://github.com/bitcoin/bitcoin/pull/15834 - and there are some more side effects from this change (that we don't have tests for, so they're going to be risky) like for example the bug fixed with e32e0840.

I'm doing a full impact analysis and hope to have that today or tomorrow, but in the meantime I'm interested in thoughts.

**Comment by alamshafil** [comment]
In my opinion, if the full impact is complicated and requires many backports from Bitcoin PRs, then I would rather push this to the 1.14.7 release since I don't want this PR to rushed and "patched" just to meet deadlines for the 1.14.6 release. The only issue I have with this is that it's a vulnerability that is actively present; however, the issue has been open for a year.

**Comment by alamshafil** [comment]
Note: I won't be at home for the next week so I won't be able to create commits, merge PRs, etc. Sorry about the inconvenience.

**Comment by patricklodder** [comment]
No worries. I am doing some experiments on top of this to see if we can get it all done. I can always open a new PR for that with this work included.

Thanks for everything so far - you're awesome ❤️

**Comment by patricklodder** [comment]
Update: I have a fix on top of this that deals with vulns introduced by the backported code on this, am finalizing the test and will pull in separately.

**Re: 100 max in-flight tx per peer issue.**

Assuming a worst case scenario where a really slow node has only 8 outgoing connections, this would give us space for 800 in-flight transactions concurrently. I have not observed any situations in the past month where we have that many transactions in mempool between blocks. If it does happen, the most likely cause is very large transactions from a custodial service being consolidated, as we've seen in the past. In fact, I haven't seen the number of transactions go over 200 much, not even when we have a delay in blocks. Here's the graph for the past week:

tx in mempool July week 1

I think we can keep the hard limit for now and fix that in a followup if we experience any issues for slower nodes.

**Comment by patricklodder** [comment]
@alamshafil I have included your work from this PR in #3030 - felt like the easier way to accomplish it - and squashed the 2 commits from here into a single annotated one.

**Comment by alamshafil** [comment]
Sounds good to me!

**Pull request closed without merging**
