### PR TITLE
Second batch of 1.15 patches

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by langerhans** [comment]
Does this replace #1417 ? If so that can be closed and this one merged.

**Comment by rnicoll** [comment]
It layers on top of #1417, and I'll probably split #1417 into 2-3 smaller PRs before it's merged, too.

**Comment by rnicoll** [comment]
I'd like to get this merged in when we can, please review when you have time.

**Comment by gewure** [comment]
hows progress on this?

**Comment by rnicoll** [comment]
Abandoning, work continues in 1.17

**Pull request closed without merging**
