### PR TITLE
Make links in About Dogecoin Core clickable.

### PR DESCRIPTION
**Pull request by Sporklin**
Added clickable thingys. (Something about telling QT to parse some of the HTML)

Devsnack pls?

### CODE REVIEW

**Comment by langerhans** [comment]
Missing a space there between the words.
>Thomas Bernard.Paper wallet art provided by Anacoluthia.

**Comment by Sporklin** [comment]
Maybe that works...?

**Comment by langerhans** [comment]
Yup, that works, thanks 👍

**Comment by Sporklin** [comment]
Rebased

**Comment by langerhans** [comment]
It marks them as links, but they don't actually open a browser for me. Tested on Ubuntu 14.04 with FIrefox. If someone else wants to test? If not, might just not pull it.

**Comment by Sporklin** [comment]
It was on the doom sheet lol

**Comment by rnicoll** [comment]
Tested with Ubuntu 14.04 and get the same result. I think this is a bug in QT, however, and personally I'd rather merge this change and keep in sync with Bitcoin Core. I'm also optimistic we'll see this behaviour change in the longer term.

**Comment by langerhans** [comment]
Sounds good to me. Maybe it works in windows. But nontheless, it allows to right click and "copy link location" so I'm fine either way.

**Pull request merged**
