### PR TITLE
Create README_pt_BR.md

### PR DESCRIPTION
**Pull request by scarletletters**
A fully translated version of README on Brazilian Portuguese. For better assessment and understanding of Dogecoin Core. It should be refered on EN and CH Readme files too.

### CODE REVIEW

**Comment by patricklodder** [comment]
I've marked this as "help wanted". Could a native (Brazilian) Portuguese speaker please have a look at this? Thanks!

**Comment by matheusbach** [comment]
[My contribution](https://github.com/scarletletters/dogecoin/pull/1)

**Review by matheusbach — DISMISSED** [review]

**Comment by patricklodder** [comment]
@scarletletters are you able to rebase this to get rid of the merge commit in here? If not, I can do it for you.

**Comment by scarletletters** [comment]
> @scarletletters are you able to rebase this to get rid of the merge commit in here? If not, I can do it for you.

I do know how to rebase but I'm not that used to github, so beeing cautious and if I'm not bothering , can you do it for me?

**Comment by patricklodder** [comment]
> can you do it for me?

Done! I've also squashed the changes from @matheusbach

**Review by patricklodder — APPROVED** [review]
ACK - based on review/collab between @scarletletters and @matheusbach.

**Comment by scarletletters** [comment]
Such help, very thanks 🐕 😆

**Pull request merged**
