### PR TITLE
Implement SI-style (thin space) thousands separator

### PR DESCRIPTION
**Pull request by rnicoll**
Reverts patches bitcoin/bitcoin#3893 and related patches. Applies bitcoin/bitcoin#4167 instead.

Opening for discussion, DO NOT merge until further testing has been completed.

### CODE REVIEW

**Comment by langerhans** [comment]
See also the referenced PRs and issues which revert part of this again. We did merge the locale specific formatting while Bitcoin did not.   
Now that we have it for nearly a year already in the code I feel like a sudden change would do nothing but confuse the shibes.  
This also still leaves open the problem of the locale specific decimal separator where for example en_US uses '.' and de_DE uses ',' .

In favor of not confusing anyone by the change after months of getting used to it I'd NACK here. The argument that "Bitcoin Core is not made for Joe Sixpack" doesn't quite hold true for Dogecoin.

**Comment by rnicoll** [comment]
I'm nervous of diverging from Bitcoin Core, and I can see how at least having the thousand-grouping consistent, even if decimal separators are not, is beneficial. I can understand it's a change that will cause some confusion on introduction, but over time I'd expect adoption rates to mean this is more confusing over time.

I'm actually now just arguing both sides just so I have, rather than I really believe in for or against this.

@patricklodder ?

**Comment by patricklodder** [comment]
I agree with @langerhans regarding the impact this change has on dogecoin-qt users and I personally value that higher than merging this because Bitcoin does it. We already are not sharing source code on this particular feature, so if the only reason to revert+merge this is to stay compatible, we can always do that if it's needed for a better reason.

That said, personally I really like how bitcoin/bitcoin master looks after their #4867, even with large amounts of doge (see below.) But this again might be overkill for some users, so I would propose either of:

1. Making this a configurable feature, or
2. Skipping this altogether for now

Where 1 takes time and 2 does not so much right now. I'd love to have option 1 but not enough to drop everything right now and build it myself.

below, for purposes of illustration, the three modes of display:

---

#### Right now: Locale-based separators
now

#### With this PR: half-space separators everywhere
this

#### Bitcoin master: only use half-space separators before the decimal separator
all

**Comment by rnicoll** [comment]
Okay, going to close this, and we can re-address it later if needed.

**Pull request closed without merging**
