### PR TITLE
LICENSE: Update year to 2023

### PR DESCRIPTION
**Pull request by NinVoido**
Happy new year, Dogecoin core team! 2022 was sure a hell of a year, hope 2023 will be better. Stay strong and doge<3

░░░░░░░░░▄░░░░░░░░░░░░░░▄
░░░░░░░░▌▒█░░░░░░░░░░░▄▀▒▌
░░░░░░░░▌▒▒█░░░░░░░░▄▀▒▒▒▐
░░░░░░░▐▄▀▒▒▀▀▀▀▄▄▄▀▒▒▒▒▒▐
░░░░░▄▄▀▒░▒▒▒▒▒▒▒▒▒█▒▒▄█▒▐
░░░▄▀▒▒▒░░░▒▒▒░░░▒▒▒▀██▀▒▌
░░▐▒▒▒▄▄▒▒▒▒░░░▒▒▒▒▒▒▒▀▄▒▒▌
░░▌░░▌█▀▒▒▒▒▒▄▀█▄▒▒▒▒▒▒▒█▒▐
░▐░░░▒▒▒▒▒▒▒▒▌██▀▒▒░░░▒▒▒▀▄▌
░▌░▒▄██▄▒▒▒▒▒▒▒▒▒░░░░░░▒▒▒▒▌
▌▒▀▐▄█▄█▌▄░▀▒▒░░░░░░░░░░▒▒▒▐
▐▒▒▐▀▐▀▒░▄▄▒▄▒▒▒▒▒▒░▒░▒░▒▒▒▒▌
▐▒▒▒▀▀▄▄▒▒▒▄▒▒▒▒▒▒▒▒░▒░▒░▒▒▐
░▌▒▒▒▒▒▒▀▀▀▒▒▒▒▒▒░▒░▒░▒░▒▒▒▌
░▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒░▒░▒▒▄▒▒▐
░░▀▄▒▒▒▒▒▒▒▒▒▒▒░▒░▒░▒▄▒▒▒▒▌
░░░░▀▄▒▒▒▒▒▒▒▒▒▒▄▄▄▀▒▒▒▒▄▀
░░░░░░▀▄▄▄▄▄▄▀▀▀▒▒▒▒▒▄▄▀
░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▀▀

### CODE REVIEW

**Comment by NinVoido** [comment]
Will fix ASAP!

**Comment by NinVoido** [comment]
Done:D

**Review by chromatic — APPROVED** [review]
We have #3191 on deck now, so I'm comfortable approving this to get the 24 hour clock started. Thanks for the contribution, @NinVoido !

**Comment by NinVoido** [comment]
So sorry, didn't see your comment. Do you want me to amend the bitcoin year fix to the first commit?

**Comment by chromatic** [comment]
@NinVoido Yes, exactly that. Squash the second commit into the first so there's only one commit and we should be good to go. Thanks!

**Comment by NinVoido** [comment]
Done! Sorry, was kinda busy yesterday:)

**Comment by chromatic** [comment]
Re-tested, re-ACK from me. Given Patrick's approval yesterday, I'll merge in a couple of hours (unless someone gets to it first, after our 24 hour window has passed).

**Comment by abosaleh82** [comment]
Hi my bro,, can you help me to work with you will give me for my task the
knwleg that i need to be one of your team

**Pull request merged**
