### PR TITLE
Fix boost 1.63 MACOS Big Sur

### PR DESCRIPTION
**Pull request by micaelmalta**
`make -C depends` is failing on MACOS Big Sur

**Current behavior:**
```
Extracting boost...
Preprocessing boost...
Configuring boost...
Building Boost.Build engine with toolset darwin... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details
make: *** [./depends/work/build/x86_64-apple-darwin20.5.0/boost/1_63_0-368f0866e9f/./.stamp_configured] Error 1
```

**bootstrap.log**
```
 error: implicit declaration of function 'out_flush' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

**Expected behavior**
Success build

**Steps to reproduce:**
make -C depends boost

### CODE REVIEW

**Comment by patricklodder** [comment]
Could you please provide a description of why you recommend to patch up dependencies for what seems to be compiling without using the rest of the depends system?

**Comment by micaelmalta** [comment]
> Could you please provide a description of why you recommend to patch up dependencies for what seems to be compiling without using the rest of the depends system?

I added a description to the PR

For some reason, the command `make -C depends` do not check if libraries are not already setup. So even though boost is already installed on your system, it s gonna build it anyway and fail. Same things for all the packages on depends

**Comment by patricklodder** [comment]
> For some reason, the command `make -C depends` do not check if libraries are not already setup. So even though boost is already installed on your system, it s gonna build it anyway and fail. Same things for all the packages on depends

This is correct. The purpose of the depends system is to build a full set of dependencies independent of system libraries and then use that by setting `--prefix` to `depends/<triplet>` when running ./configure, so that these tested versions are used for compilation. Building outside of the depends system serves another purpose, for example, if someone does not like boost 1.63 for whatever reason (package manager not supporting it, CVEs), they can build with another version until we change the dependency (can be hard to achieve sometimes.) We support that best-effort, as long as tested versions don't break. See for example 41406bf, where Dogecoin code was updated to also support boost 1.78.

The only known case to me where this causes portability issues is with bdb5.1, which is why I do think that the solution in #2398 is okay. But for this one, I'm not entirely sure, yet, because it should be straightforward to use another boost version and not have to be bound to depends, without repercussions. What boost version comes with macports/brew? Are there integration issues with it?

**Comment by micaelmalta** [comment]
IMO, `make -C depends` should be the universal way to build dependencies for all the platforms we support. Otherwise, we start to make assumptions that the depends tool is provided just in case something don't work. It make it then harder to test it on CI

**Comment by patricklodder** [comment]
So from a process of this repository and its releases, all the releases are cross-compiled using gitian. Supporting other platforms is not policy and is solely supported on a best-effort basis, so that a release will never be blocked by integration with non-release tooling. We do not develop Dogecoin Core for developers really, we develop it as a binary release for shibes to use, and this has always been the primary use case. Just look at the stats:

Release downloads for 1.14.3:

| artifact | downloads |
| :------ | -----: | 
| dogecoin-1.14.3-arm-linux-gnueabihf.tar.gz | 439 |
| dogecoin-1.14.3-win32.zip | 919 |
| dogecoin-1.14.3-aarch64-linux-gnu.tar.gz | 1387 |
| dogecoin-1.14.3-win64.zip | 7545 |
| dogecoin-1.14.3-i686-pc-linux-gnu.tar.gz | 12125 |
| dogecoin-1.14.3-x86_64-linux-gnu.tar.gz | 42360 |
| dogecoin-1.14.3-win32-setup-unsigned.exe | 94491 |
| dogecoin-1.14.3-osx.dmg | 164680 |
| dogecoin-1.14.3-win64-setup-unsigned.exe | 431777 |

versus [cloning traffic](https://github.com/dogecoin/dogecoin/graphs/traffic):

Cloning counts

Additionally, the recommended way to compile Dogecoin Core is by cross-compiling on Ubuntu (currently trusty, but I'd like that to be focal) using the depends system, which is made easy by all the docker tooling available today. The fact that we can fall back to using the depends system for compiling bdb5.1 on Big Sur outside of that process due to wallet incompatibility is really a beneficial coincidence rather than as-intended.

**Comment by micaelmalta** [comment]
I understand but if we want to encourage more developers to join us to contribute, we need to ease the way to build and currently, it's not straight forward.

Based on my early experience, it took me almost 1 month to have something working on my laptop :(

Example of post where a developer as issue with MacOS: https://github.com/dogecoin/dogecoin/issues/1948

**Comment by patricklodder** [comment]
I just checked and compilation works fine for me out of the box with `brew install boost` (and not the source install as quoted in the doc as needed for 1.67) - probably fixed by a more recent boost, currently 1.76 is installed by default.

**Pull request closed without merging**
