### PR TITLE
upgraded qt to v5.15.2

### PR DESCRIPTION
**Pull request by fmhc**
https://github.com/dogecoin/dogecoin/issues/2338
Unit tests successful
image
image
image
RPC tests successful
image

working dogecoin-qt

image

and typing with the Keyboard works again:
image

### CODE REVIEW

**Review by AbcSxyZ — COMMENTED** [review]
Nice work, change looks good, I checked the url change. Hash are also correct, I confirm the following : 
```
0eb522ff6c2194f9690cbdcd5b33e803  qtbase-everywhere-src-5.15.2.tar.xz
739403634e1326a3d52902a835015a4b  qttools-everywhere-src-5.15.2.tar.xz
9b66cdb64402e8fd9e843f8a7120abb1  qttranslations-everywhere-src-5.15.2.tar.xz
```

I'm learning about how to use `depends` folder, wasn't able to test compilation right now. Will try in the following days to run unit tests on my side.

**Comment by patricklodder** [comment]
Note: this needs gitian checks. Adding do not merge label for now.

**Comment by fmhc** [comment]
sorry i guess i commited the wrong version here for v5.12.11 and not v5.15.2:

image

**Comment by fmhc** [comment]
This leads me to the question why i could compile it while the sums were wrong

**Comment by rnicoll** [comment]
I'm noting Bitcoin hasn't gone past `5.12.11` (https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk) and I wonder if they know something. In brighter news, I can see a few broken download URLs but they're easier to fix.

**Comment by rnicoll** [comment]
The answer to why it worked locally is that it _normally_ uses the locally available version of Qt, it's only for CI, Gitian and a few other cases that it uses specific fixed versions.

**Comment by rnicoll** [comment]
> I'm noting Bitcoin hasn't gone past `5.12.11` (https://github.com/bitcoin/bitcoin/blob/master/depends/packages/qt.mk) and I wonder if they know something. In brighter news, I can see a few broken download URLs but they're easier to fix.

Looks like it was just a timing issue: https://github.com/bitcoin/bitcoin/pull/22054

**Comment by rnicoll** [comment]
I had a go at fixing the CI breakage, but we're going through so many versions here it's hard to work out what patches we'll need. Potentially this is too ambitious a jump to do all at once. I've put my work in progress into a PR in case it helps, but don't anticipate completing it myself: https://github.com/katzenmalen/dogecoin/pull/1

**Comment by micaelmalta** [comment]
The upgrade is not so simple: See https://github.com/bitcoin/bitcoin/pull/21376/files

**Comment by patricklodder** [comment]
removed from 1.14.4 target milestone, qt (and openssl) dependency updates will have to target 1.14.5

**Comment by patricklodder** [comment]
Closing this for now. Foreign keyboard support has been fixed with 1.14.5's libxkb inclusion, and 5.15 is unmaintained

**Pull request closed without merging**
