### PR TITLE
Add dogechain and chain.so as default block explorers

### PR DESCRIPTION
**Pull request by Sporklin**

### CODE REVIEW

**Comment by rnicoll** [comment]
So... not sure quite where they've put the explorer menu options, but I can't find them with or without this patch :-/

**Comment by D3m0nKingx** [comment]
Gonna go all the way and also rename the bitcoin files to dogecoin?: 

>./src/bitcoin-cli.cpp
./src/script/bitcoinconsensus.h
./src/script/bitcoinconsensus.cpp
./src/config/bitcoin-config.h.in
./src/config/bitcoin-config.h
./src/qt/bitcoinunits.cpp
./src/qt/bitcoinaddressvalidator.h
./src/qt/bitcoin_locale.qrc
./src/qt/res/src/bitcoin.svg
./src/qt/res/icons/bitcoin.icns
./src/qt/res/icons/bitcoin.ico
./src/qt/res/icons/bitcoin.png
./src/qt/res/bitcoin-qt-res.rc
./src/qt/bitcoin.cpp
./src/qt/bitcoinunits.h
./src/qt/bitcoingui.h
./src/qt/bitcoin.qrc
./src/qt/bitcoinamountfield.h
./src/qt/bitcoinaddressvalidator.cpp
./src/qt/bitcoin.moc
./src/qt/bitcoingui.cpp
./src/qt/bitcoinstrings.cpp
./src/qt/bitcoinamountfield.moc
./src/qt/bitcoinamountfield.cpp
./src/qt/locale/bitcoin_de.qm
./src/qt/locale/bitcoin_de.ts
./src/qt/locale/bitcoin_be_BY.ts
./src/qt/locale/bitcoin_et.ts
./src/qt/locale/bitcoin_ka.ts
./src/qt/locale/bitcoin_cy.qm
./src/qt/locale/bitcoin_mn.ts
./src/qt/locale/bitcoin_ca_ES.qm
./src/qt/locale/bitcoin_hr.qm
./src/qt/locale/bitcoin_sq.qm
./src/qt/locale/bitcoin_ro_RO.ts
./src/qt/locale/bitcoin_es.ts
./src/qt/locale/bitcoin_zh_HK.qm
./src/qt/locale/bitcoin_fi.ts
./src/qt/locale/bitcoin_pam.qm
./src/qt/locale/bitcoin_es_MX.ts
./src/qt/locale/bitcoin_et.qm
./src/qt/locale/bitcoin_es_UY.qm
./src/qt/locale/bitcoin_nb.ts
./src/qt/locale/bitcoin_sv.ts
./src/qt/locale/bitcoin_uk.ts
./src/qt/locale/bitcoin_bs.qm
./src/qt/locale/bitcoin_da.qm
./src/qt/locale/bitcoin_sq.ts
./src/qt/locale/bitcoin_zh_CN.ts
./src/qt/locale/bitcoin_he.ts
./src/qt/locale/bitcoin_lv_LV.ts
./src/qt/locale/bitcoin_fr_CA.qm
./src/qt/locale/bitcoin_it.qm
./src/qt/locale/bitcoin_kk_KZ.qm
./src/qt/locale/bitcoin_ach.qm
./src/qt/locale/bitcoin_ro_RO.qm
./src/qt/locale/bitcoin_pl.qm
./src/qt/locale/bitcoin_sk.ts
./src/qt/locale/bitcoin_fa.qm
./src/qt/locale/bitcoin_es_DO.ts
./src/qt/locale/bitcoin_sk.qm
./src/qt/locale/bitcoin_cmn.qm
./src/qt/locale/bitcoin_fa_IR.ts
./src/qt/locale/bitcoin_hu.qm
./src/qt/locale/bitcoin_eu_ES.qm
./src/qt/locale/bitcoin_kk_KZ.ts
./src/qt/locale/bitcoin_lv_LV.qm
./src/qt/locale/bitcoin_ru.ts
./src/qt/locale/bitcoin_nb.qm
./src/qt/locale/bitcoin_ka.qm
./src/qt/locale/bitcoin_el_GR.qm
./src/qt/locale/bitcoin_ja.ts
./src/qt/locale/bitcoin_ca.ts
./src/qt/locale/bitcoin_sah.ts
./src/qt/locale/bitcoin_ko_KR.ts
./src/qt/locale/bitcoin_la.qm
./src/qt/locale/bitcoin_vi_VN.qm
./src/qt/locale/bitcoin_fr.ts
./src/qt/locale/bitcoin_fa.ts
./src/qt/locale/bitcoin_bs.ts
./src/qt/locale/bitcoin_sr.ts
./src/qt/locale/bitcoin_ms_MY.ts
./src/qt/locale/bitcoin_eu_ES.ts
./src/qt/locale/bitcoin_zh_TW.ts
./src/qt/locale/bitcoin_hi_IN.qm
./src/qt/locale/bitcoin_pam.ts
./src/qt/locale/bitcoin_th_TH.ts
./src/qt/locale/bitcoin_uk.qm
./src/qt/locale/bitcoin_it.ts
./src/qt/locale/bitcoin_gl.qm
./src/qt/locale/bitcoin_es.qm
./src/qt/locale/bitcoin_es_MX.qm
./src/qt/locale/bitcoin_lt.ts
./src/qt/locale/bitcoin_ja.qm
./src/qt/locale/bitcoin_gl.ts
./src/qt/locale/bitcoin_ko_KR.qm
./src/qt/locale/bitcoin_eo.qm
./src/qt/locale/bitcoin_hu.ts
./src/qt/locale/bitcoin_pt_BR.qm
./src/qt/locale/bitcoin_en.qm
./src/qt/locale/bitcoin_sv.qm
./src/qt/locale/bitcoin_es_CL.qm
./src/qt/locale/bitcoin_af_ZA.qm
./src/qt/locale/bitcoin_nl.ts
./src/qt/locale/bitcoin_zh_TW.qm
./src/qt/locale/bitcoin_id_ID.ts
./src/qt/locale/bitcoin_be_BY.qm
./src/qt/locale/bitcoin_es_DO.qm
./src/qt/locale/bitcoin_ca_ES.ts
./src/qt/locale/bitcoin_eo.ts
./src/qt/locale/bitcoin_cy.ts
./src/qt/locale/bitcoin_ar.ts
./src/qt/locale/bitcoin_ca@valencia.qm
./src/qt/locale/bitcoin_ach.ts
./src/qt/locale/bitcoin_fr_CA.ts
./src/qt/locale/bitcoin_gu_IN.qm
./src/qt/locale/bitcoin_ca.qm
./src/qt/locale/bitcoin_th_TH.qm
./src/qt/locale/bitcoin_sah.qm
./src/qt/locale/bitcoin_zh_CN.qm
./src/qt/locale/bitcoin_hr.ts
./src/qt/locale/bitcoin_zh_HK.ts
./src/qt/locale/bitcoin_ru.qm
./src/qt/locale/bitcoin_id_ID.qm
./src/qt/locale/bitcoin_es_CL.ts
./src/qt/locale/bitcoin_sl_SI.qm
./src/qt/locale/bitcoin_tr.qm
./src/qt/locale/bitcoin_cmn.ts
./src/qt/locale/bitcoin_da.ts
./src/qt/locale/bitcoin_fr.qm
./src/qt/locale/bitcoin_lt.qm
./src/qt/locale/bitcoin_pt_PT.ts
./src/qt/locale/bitcoin_ca@valencia.ts
./src/qt/locale/bitcoin_ky.ts
./src/qt/locale/bitcoin_uz@Cyrl.ts
./src/qt/locale/bitcoin_en.ts
./src/qt/locale/bitcoin_pl.ts
./src/qt/locale/bitcoin_ms_MY.qm
./src/qt/locale/bitcoin_af_ZA.ts
./src/qt/locale/bitcoin_fi.qm
./src/qt/locale/bitcoin_la.ts
./src/qt/locale/bitcoin_mn.qm
./src/qt/locale/bitcoin_ar.qm
./src/qt/locale/bitcoin_el_GR.ts
./src/qt/locale/bitcoin_cs.ts
./src/qt/locale/bitcoin_bg.qm
./src/qt/locale/bitcoin_sl_SI.ts
./src/qt/locale/bitcoin_cs.qm
./src/qt/locale/bitcoin_ur_PK.ts
./src/qt/locale/bitcoin_gu_IN.ts
./src/qt/locale/bitcoin_bg.ts
./src/qt/locale/bitcoin_hi_IN.ts
./src/qt/locale/bitcoin_fa_IR.qm
./src/qt/locale/bitcoin_vi_VN.ts
./src/qt/locale/bitcoin_vi.qm
./src/qt/locale/bitcoin_uz@Cyrl.qm
./src/qt/locale/bitcoin_vi.ts
./src/qt/locale/bitcoin_sr.qm
./src/qt/locale/bitcoin_pt_PT.qm
./src/qt/locale/bitcoin_he.qm
./src/qt/locale/bitcoin_nl.qm
./src/qt/locale/bitcoin_pt_BR.ts
./src/qt/locale/bitcoin_es_UY.ts
./src/qt/locale/bitcoin_tr.ts
./src/qt/locale/bitcoin_ur_PK.qm
./src/qt/locale/bitcoin_ky.qm
./src/secp256k1/src/java/org/bitcoin
./src/secp256k1/build-aux/m4/bitcoin_secp.m4
./src/bitcoind-res.rc
./src/test/bitcoin-util-test.py
./src/test/data/bitcoin-util-test.json
./src/bitcoin-tx.cpp
./src/bitcoin-cli-res.rc
./src/bitcoin-tx-res.rc
./src/bitcoind.cpp
./contrib/bitcoin-qt.pro
./build-aux/m4/bitcoin_subdir_to_include.m4
./build-aux/m4/bitcoin_qt.m4
./share/pixmaps/bitcoin128.xpm
./share/pixmaps/bitcoin.ico
./share/pixmaps/bitcoin64.png
./share/pixmaps/bitcoin-bc.ico
./share/pixmaps/bitcoin16.png
./share/pixmaps/bitcoin128.png
./share/pixmaps/bitcoin16.xpm
./share/pixmaps/bitcoin256.png
./share/pixmaps/bitcoin64.xpm
./share/pixmaps/bitcoin32.xpm
./share/pixmaps/bitcoin32.png
./share/pixmaps/bitcoin256.xpm
./doc/bitcoin_logo_doxygen.png
./doc/release-notes/bitcoin

**Comment by langerhans** [comment]
No as that would create a huge mess of merge errors later down the line.

**Comment by rnicoll** [comment]
Specifically, because we rebuild each major Dogecoin Core release from the most recent Bitcoin Core, any changes we make have to re-introduced each time, so we keep the change set minimal. Even if we did it the other way, merging changes to Bitcoin Core into Dogecoin Core, we'd still have massive issues with mismatching file names.

As it stands, Bitcoin has a couple of orders of magnitude more developer time available, so we have to build around being able to integrate those changes.

**Comment by nurazhar** [comment]
why does the founder abandon dogecoin? i mean charlie didn't abandoned litecoin

**Pull request merged**
