### PR TITLE
1.15.0 dev improve random upstream cherry picks

### PR DESCRIPTION
**Pull request by chromatic**
This is a work in progress to cherry-pick some upstream randomization improvements (see #3229 for context).

### CODE REVIEW

**Comment by patricklodder** [comment]
I benched this on both an x86_64 Intel I7 and an arm64 Apple M1. Results:

### On i7-970

#### Current FastRandomContext (at 8d4e0bd085)

```csv
#Benchmark,count,min,max,average,min_cycles,max_cycles,average_cycles
FastRandom_1bit,640,0.001588508486748,0.001606859266758,0.001596468687057,5144478,5203874,5170219
FastRandom_32bit,640,0.001587942242622,0.001599781215191,0.001593051850796,5142448,5180947,5159149
```

#### New FastRandomContext (at 9c33a274e4)

```csv
#Benchmark,count,min,max,average,min_cycles,max_cycles,average_cycles
FastRandom_1bit,576,0.001762509346008,0.001951079815626,0.001785520878103,5707967,6318597,5782466
FastRandom_32bit,88,0.011499375104904,0.011546224355698,0.011518229137767,37241032,37393131,37302139
```

### On Apple M1

#### Current FastRandomContext

```csv
#Benchmark,count,min,max,average,min_cycles,max_cycles,average_cycles
FastRandom_1bit,416,0.002500720322132,0.002539746463299,0.002514704488791,0,0,0
FastRandom_32bit,416,0.002498909831047,0.002532906830311,0.002507672860072,0,0,0
```

#### New FastRandomContext

```csv
#Benchmark,count,min,max,average,min_cycles,max_cycles,average_cycles
FastRandom_1bit,1280,0.000798149034381,0.000805476680398,0.000799535214901,0,0,0
FastRandom_32bit,160,0.006616741418839,0.006684437394142,0.006653493642807,0,0,0
```

**Comment by xanimo** [comment]
Everything is looking good so far. Tested successfully on x86_64-pc-linux-gnu jammy.

```
FastRandom_1bit,768,0.001310061663389,0.001355305314064,0.001322269439697,3270081,3383005,3300558
FastRandom_32bit,120,0.008004248142242,0.010467499494553,0.008429358402888,19979437,26128340,21040796
```

**Comment by chromatic** [comment]
I can't seem to reproduce a clean cherry-pick like you mention, @patricklodder . Did you reproduce from [9c33a2](https://github.com/dogecoin/dogecoin/pull/3487/commits/9c33a274e465b1a864a50837641d994fd49622b8) or is there another commit? I get conflicts around `noexcept` for `FastRandomContext::FastRandomContext()`.

**Comment by xanimo** [comment]
> Everything is looking good so far. Tested successfully on x86_64-pc-linux-gnu jammy.
> 
> ```
> FastRandom_1bit,768,0.001310061663389,0.001355305314064,0.001322269439697,3270081,3383005,3300558
> FastRandom_32bit,120,0.008004248142242,0.010467499494553,0.008429358402888,19979437,26128340,21040796
> ```

@chromatic This [one](https://github.com/xanimo/dogecoin/tree/1.15.0-dev-chacha20) is a bit further down the road but in comparison here are my results with those cherry-picks @patricklodder mentioned:
```
FastRandom_1bit,832,0.001286000013351,0.001319061964750,0.001300879969047,3209897,3292369,3247008
FastRandom_32bit,128,0.007689073681831,0.008537530899048,0.008067343384027,19191829,21310164,20136173
```

**Comment by xanimo** [comment]
Running on a i5-10300H*

**Comment by patricklodder** [comment]
this, and others, got merged through #3511 and the unroll is addressed in #3523 - I'm closing this one.

**Pull request closed without merging**
