### PR TITLE
Fixed minor markdown / heading errors

### PR DESCRIPTION
**Pull request by jahaanjain**
It's the small things, right?

### CODE REVIEW

**Comment by scrpatlolla** [comment]
Can you add a preview screenshot?

**Comment by jahaanjain** [comment]
Before: https://i.imgur.com/y69Vf7X.png and https://i.imgur.com/2xrV2QA.png

After: https://i.imgur.com/W7nmpUD.png and https://i.imgur.com/JxxGLLP.png

**Comment by rnicoll** [comment]
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

```
git fetch origin
git rebase -i origin/1.14.4-dev
```

It will then bring up an editor. If you remove the 3 commits before the one you want. Please check the result then force push it, and it should just change the document.

Thanks.

**Comment by jahaanjain** [comment]
Just did it @rnicoll !

**Comment by rnicoll** [comment]
Still seems to have "Update .github/ISSUE_TEMPLATE.md" and "Mention wallet recovery" mixed in with the expected commit.

**Comment by jahaanjain** [comment]
My mistake. I've just reverted the "Update .github/ISSUE_TEMPLATE.md" and "Mention wallet recovery" commits.

**Comment by patricklodder** [comment]
This was fixed with #2111

**Pull request closed without merging**
