### PR TITLE
 [improvement] This code is unreachable. Deleted.

### PR DESCRIPTION
**Pull request by ReverseControl**

### CODE REVIEW

**Comment by patricklodder** [comment]
Do we know WHY this function was always returning a single script variant for something that was supposed to be random between 3 different types? (Even though random in tests is awful.) I.e. are we deleting dead code, or are we deleting incubating code?

New function does not do what the name implies as much as the old one didn't ☹️

**Comment by AbcSxyZ** [comment]
Take a look at https://github.com/bitcoin/bitcoin/pull/21081.

I'm not sure if taproot is enabled in dogecoin (it is ?), but look like the first return of `random_checksig_style` function was a mistake.

**Comment by AbcSxyZ** [comment]
And for all of your factorization PR from #2533 to #2545, isn't it interesting to do requests on bitcoin repo, and then merge it into doge ?

Idk how you may deal with merging btc code in this situation @patricklodder @rnicoll, but it may be the most appropriate place for this kind of changes.

Can bring improvement to both bitcoin and Dogecoin at once, bitcoin source code is where the problem come from.
Just my opinion.

**Comment by ReverseControl** [comment]
@AbcSxyZ I havent looked at the Bitcoin repo at all. I am of the opinion solving problems should be as painless as possible. I don't know that going through bitcoin first is better, it might be. If we do the work of improving things here they are free to take our improvements and merge it to their code. 

I am just beginning to learn about the details of our code base so as we go along I will be able to address more things.

And thanks. It seems bitcoin already addressed this. I don't know what ``taproot``  is or if we use it. We should look into that and decide accordingly. If we do use it, we should merge that btc commit to ours and reject this one. If not, do the reverse.

**Comment by patricklodder** [comment]
> I'm not sure if taproot is enabled in dogecoin

Nope. It can't just be "enabled" like that. And the code being there without the activation is a risk that we've ran into with some wallet providers before, where Dogecoin Core does unexpected things. I've flagged issues with this in some prior 1.21 PRs, but it's not really getting picked up. We'll see what's what when 1.21-dev gets into a state where it's actually testable.

**Comment by rnicoll** [comment]
Merged in Bitcoin Core 0.21.2 which resolves the unreachable code, so the test now executes properly. Thanks for flagging this though, good to have it checked.

**Pull request closed without merging**
