### PR TITLE
1.14.5 dev wallet.h change from bitcoin to dogecoin #ifndef

### PR DESCRIPTION
**Pull request by victorsk2019**
Changed from BITCOIN_WALLET... to DOGECOIN_WALLET... in header file's #ifndef and #define definitions.  Will change other files if accepted.

https://github.com/victorsk2019/dogecoin/commit/19535f715b9b937132a3ad0cd25f71e39b28839b

### CODE REVIEW

**Comment by patricklodder** [comment]
Hi, 

This is a header guard, so it has no function other than to prevent a compiler from including the definitions twice. 

In the past, we have always held the strategy that things that are written by Bitcoin developers, even when we amend these, can just keep referring to Bitcoin as long as there's no exposure to the end user. So this is why this currently says "bitcoin" instead of "dogecoin".

Since also your commit is not included in this PR, I'm going to close this, but I'll leave the comments open in case you wish to discuss further.

**Comment by victorsk2019** [comment]
> Hi,
> 
> This is a header guard, so it has no function other than to prevent a compiler from including the definitions twice.
> 
> In the past, we have always held the strategy that things that are written by Bitcoin developers, even when we amend these, can just keep referring to Bitcoin as long as there's no exposure to the end user. So this is why this currently says "bitcoin" instead of "dogecoin".
> 
> Since also your commit is not included in this PR, I'm going to close this, but I'll leave the comments open in case you wish to discuss further.

Thank you for addressing this PR.  I am aware of the purpose of header guards in the header file, however, although it's meant for internal use, the upper-cased "bitcoin_wallet..." text for Dogecoin Core project stands out too much for me not to propose this change.  Thanks.

**Comment by patricklodder** [comment]
> the upper-cased "bitcoin_wallet..." text in the Dogecoin Core project stands out too much for me not to propose this change.  

Why does it bother you exactly?

**Comment by victorsk2019** [comment]
> > the upper-cased "bitcoin_wallet..." text in the Dogecoin Core project stands out too much for me not to propose this change.
> 
> Why does it bother you exactly?

It is a Dogecoin Core wallet that's being worked on not Bitcoin Core?

**Comment by patricklodder** [comment]
The file in question `src/wallet/wallet.h` came from Bitcoin Core. Out of the 1080 lines ported from Bitcoin Core, 111 were changed, so roughly 10%, and most of that are deletions caused by moving `CMerkleTx` from this file into `auxpow.h`, causing 78 deletions, leaving the effective change at 33/1080 = 3%. So in a way, you are looking at Bitcoin Core most of the time when you look at that file.

If you really feel that this should be fixed, feel free to reopen a PR that includes your proposed change, and I'll give you my opinion once more there ❤️

**Comment by victorsk2019** [comment]
Sorry if I sounded too picky, Patrick.  I used to work for a boss (who was a lawyer) and he considered naming things very important, even if it was part of my code and was not public-facing.  So it's now part of my habit too ;)

**Comment by patricklodder** [comment]
No problem! Naming things is important! I get that. 

I'd kept this PR open for others to react on if it was not a merge of 1.14.5-dev from this repo into master on this repo, but a PR of your branch onto 1.14.5-dev. So like I said, if you feel strongly about it, just reopen a new pull request from your branch onto 1.14.5-dev and we can totally have a discussion about it.

**Comment by DemonRx** [comment]
Hi guys, 

Just want to throw my two-cents in where I think there may have been a lil misapplied use of the words exposure and public-facing code. 

Want to point out that this repo is a **public** repo, so slap me silly if the code isn't always exposed and public-facing to the users :) , much different had this been a closed-source software/private repository, then it would (to me anyway) make sense that it wouldn't make much difference the "aesthetics" of the code. Which I think that's all this would be to change the headers gaurds.  

Functionally speaking, it has no effect. 

So what brings into question is how far detracted does and why would one want to make the code from which it was forked ? You can't remove the Bitcoin Copyrights in this repo. (Cause it can be clearly traced back to the original code it was forked from). 

So how important is it to rename anything else? In regards to what the user sees, let's keep it specifically to the GUI, the core (daemon) limited to what output is displayed in the terminal and log files.  Those might be the only places of concern that the the branding name and other elements would be exposed and/or public-facing from the running binaries that  need renaming.  Changing anything internally  seems moot.

**Comment by patricklodder** [comment]
> Want to point out that this repo is a public repo, so slap me silly if the code isn't always exposed and public-facing to the users :)

Ah yes, to clarify, with "end users" I mean people that use the software, not people that use the repository (or clone the repo) to read header files, those would be "developers". (naming things, again 😁)

Historically we've said that since the more we change, the harder it will be to back-port patches from upstream Bitcoin Core, we try to keep changes to a minimum, especially aesthetic changes that are only exposed to developers. This went pretty far, sometimes preventing innovation, so since this year we've loosened this up a bit for 1.14.x because shibes wanted to innovate but were discouraged to (that's why for example we have [Operation Such Frensly](https://github.com/dogecoin/dogecoin/projects/5)) and there's an open discussion that touches on this too at #2273

**Comment by victorsk2019** [comment]
> So what brings into question is how far detracted does and why would one want to make the code from which it was forked ?

There's a handy 'find' unix command I find useful on many occasions that can string occurrences in a given file quickly and effortlessly:
`find *.h -type f -exec sed -i 's/BITCOIN/DOGECOIN/g' {} \;`

As I recall, one of the goals in Rosetta API project was to change all "bitcoin" to "dogecoin" names in the source, in addition to dogecoin-specific functionality.  My understanding is Coinbase, for some reason, seemed to consider having it say "dogecoin" instead of "bitcoin" in source code as something important?

It is a bit irritating for me personally when studying Dogecoin Core source I see "bitcoin" in upper case in various locations.  I understand copyright notice must always stay, but this is a Dogecoin, not a Bitcoin project after all.  Thank you for explaining to me the underlying decisions for keeping bitcoin names in the code.

**Pull request closed without merging**
