### PR TITLE
Add dev fund donation button

### PR DESCRIPTION
**Pull request by whitj00**

### CODE REVIEW

**Comment by whitj00** [comment]
@langerhans @rnicoll @patricklodder Thoughts?

**Comment by langerhans** [comment]
Leaving this open for now as the other things that actually add new things. We want to get the other stuff merged first. Thanks for the suggestion tho!

**Comment by rnicoll** [comment]
As we're getting towards 1.10, thought I should ping people to come back and ponder this. I'm nervous it sends the wrong message, but certainly we could put the donation address in docs more. Happy to merge if others are.

Also happy to handle rebaseing this on 1.10 myself rather than asking for everything to be closed and reopened.

**Comment by patricklodder** [comment]
I'd prefer to not implement this because I'm not comfortable with making donations to us a feature.. Plus it just gives just another incentive for someone to publish this as for example an apt package and redirect the button target.

**Comment by rnicoll** [comment]
Thanks for the work @whitj00 , but I think yes, it sends the wrong message unfortunately, however well meaning.

**Pull request closed without merging**
