### PR TITLE
build: bdb detection and configuration fixes for macOs/brew

### PR DESCRIPTION
**Pull request by patricklodder**
Currently, brew logic in `configure.ac` always adds the default `berkeley-db` path when compiling on macOs. This causes link-time and/or run-time issues when the default version (18.x) is installed on the compiling system, and prevents proper linking when using the `contrib/install_bdb.sh` script. This has been blocking #2686.

This PR fixes that issue by:

1. Updating `dogecoin_find_bdb53.m4` to also check manually specified `BDB_CFLAGS` and `BDB_LIBS`. This prevents link-time and run-time errors by catching the error during configuration.
2. Using the `BITCOIN_FIND_BDB53` m4 macro when using brew for bdb detection instead of appending values to the generic `CPPFLAGS` and `LIBS`, because these are used generically for every binary and can cause issues with libtool archive scope.
3. Only using brew to detect the installed version if no `BDB_CFLAGS` or `BDB_LIBS` is manually given. This is to allow maximum flexibility for custom compiles, while retaining automatic configuration.
4. Detect each version of the `berkeley-db` package, in the order `@5`, `@4` and only then the default version. The reason for this detection order is that 4.x is still fully readable by 5.3.27NC that is distributed by default, and therefore preferred over newer-than 5.x versions.

I've tested this to work on x86_64-linux, arm64-darwin and x86_64-darwin

After applying this patch on top of #3301, configuration on macOs only requires manual specification of boost, i.e.:

```bash
./autogen.sh
./configure --with-boost=`brew --prefix boost`
```

~~Note: this PR is best tested on top of #3301, so it's probably best to rebase this after that, or an alternative fix, gets merged.~~

### CODE REVIEW

**Comment by chromatic** [comment]
ACK, all tests pass on 64-bit x86-Linux and the code changes make sense to me.

I think we should have another test on Mac though. @michilumin can you take this for a spin too?

**Comment by michilumin** [comment]
Yup will do. About a day until I get back to my Mac but yes.

**Review by michilumin — COMMENTED** [review]
Review OK, testing in-situ.

**Comment by michilumin** [comment]
Using brew berkeley-db@5 (vs berkeley-db), configures OK, builds OK, passes all unit tests (Core 2/2, libsec 2/2, univalue 3/3), on x86 Mac OS 13/Ventura build 13.6 (Intel, virgin install to ext SSD.)

**Comment by michilumin** [comment]
wrong button.

**Review by michilumin — APPROVED** [review]
Visually reviewed and tested, looks OK to merge.

**Comment by chromatic** [comment]
With Michi's approval, we're well past the 24 hour merge window so here we go!

**Pull request merged**
