### PR TITLE
bugfix: change asserts into handled failures for cmpctblk

### PR DESCRIPTION
**Pull request by patricklodder**
Replaces `assert()` calls with `if()` statements returning functional failure that can be handled for situations that can be triggered from outside of compiled code - i.e. peers.

Backported from Bitcoin Core's [fuzz target introduction for `blockencoding.cpp`](https://github.com/bitcoin/bitcoin/pull/26898)

### CODE REVIEW

**Review by xanimo — COMMENTED** [review]
looks ok. per original and this one there are some inconsistencies but i'm assuming you're not including:
```
    CheckBlockFn check_block = m_check_block_mock ? m_check_block_mock : CheckBlock;
    if (!check_block(block, state, Params().GetConsensus(), /*fCheckPoW=*/true, /*fCheckMerkleRoot=*/true)) {
```
and the amendments to the blockencodings header for a reason?

**Comment by patricklodder** [comment]
> per original and this one there are some inconsistencies but i'm assuming you're not including _[mockable CheckBlock()]_ and the amendments to the blockencodings header for a reason?

For a simple reason as the linked PR does 2 things:

1. Fix a bug, and
2. Add a fuzz target

I'm only backporting the former in this PR; the header additions and `CheckBlock()` mocking are only to support the fuzz target. Since these actually complicate code, including them is not in favor of doing a clean bug fix and especially not in favor of people reviewing it.

I think we should add the fuzz target too, but not with the same urgency as fixing an actual (inherited) bug.

**Comment by xanimo** [comment]
> > per original and this one there are some inconsistencies but i'm assuming you're not including _[mockable CheckBlock()]_ and the amendments to the blockencodings header for a reason?
> 
> For a simple reason as the linked PR does 2 things:
> 
> 1. Fix a bug, and
> 2. Add a fuzz target
> 
> I'm only backporting the former in this PR; the header additions and `CheckBlock()` mocking are only to support the fuzz target. Since these actually complicate code, including them is not in favor of doing a clean bug fix and especially not in favor of people reviewing it.
> 
> I think we should add the fuzz target too, but not with the same urgency as fixing an actual (inherited) bug.

makes sense. ack.

**Review by chromatic — APPROVED** [review]
ACK, all tests pass on x86-64 Linux. The code changes make sense to me too; better to be explicit and recover where we can with existing mechanisms.

**Comment by Pollo456yhhyuuuyvvbjj** [comment]
> looks ok. per original and this one there are some inconsistencies but i'm assuming you're not including:
> ```
>     CheckBlockFn check_block = m_check_block_mock ? m_check_block_mock : CheckBlock;
>     if (!check_block(block, state, Params().GetConsensus(), /*fCheckPoW=*/true, /*fCheckMerkleRoot=*/true)) {
> ```
> and the amendments to the blockencodings header for a reason?

**Pull request merged**
