### PR TITLE
depends: reduce Qt footprint

### PR DESCRIPTION
**Pull request by patricklodder**
This PR reduces the footprint of Qt in `depends` by:

1. Removing all image support except `png`
2. Disabling all unused features
3. Removing the dbus package completely because it is not used anywhere
4. Removing libX11 and its dependencies from the build system and configure Qt to not export it.

This is needed because we cannot use newer versions of Qt without dropping compatibility for older MacOS and Windows, which prevents a path for those users to get security updates within the 1.14.x series of releases. This smaller scope reduces maintenance pressure for 1.14.x significantly, and because there will be a lot less Qt code to worry about in terms of inherited bugs, and because 5 packages in `depends` will no longer be needed:

 - dbus
 - libX11
 - libXext
 - xextproto
 - xtrans

This PR is an alternative for the package updates in #3351 and #3346 and needs a Gitian comparison.

### CODE REVIEW

**Comment by chromatic** [comment]
This PR compiles and passes tests on 64-bit x86 Linux. I'll review the changes next.

We need to compare multiple gitian build outputs from multiple people before we can accept this (that's what the "gitian check needed" label means, if you haven't seen it before).

**Comment by xanimo** [comment]
tested on x86_64-pc-linux-gnu jammy and everything is working fine. additionally built gitian via docker:
```
9e1e7004cbfcb3c79012e0f66e5f8e12e72d2bca16e8ec67db66366a488b88a9  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
d14643080bc9bd5ffa83eeedd9a7e39ccdf2d420699c4cd9eef700d8578a80cd  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
508515c5e14e3c1027b4bb2dd3d16546460914ca5fb39ba5dccd8171e4eb39c9  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
a23cd1217e75f16da9a81562d5f3881b149c35df0e9b5e4bae6f9a632b0cc690  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
f7ba0db5ca41e332ffadaef409efae00e6aad7ab6d39aa22239efeca41255d3e  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
79e6039f2efefc94d28db3ff6e718c24653b6b84d851ff5fe402d4b3b4b208a6  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
93b5e982df544bd91c9888a5bb9142d7d4c2781ded3be3a984698c9a988e74ce  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
53b76ce2d7d92cc74a7122e7a7cfd0df337da0e13fded3893b1a241bc0b4ccaf  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
cfce5522ffcf6263300472b9d0b6a9a70271ef00a96532b82b789f7180eec468  dogecoin-1.14.7-win-unsigned.tar.gz
85f73547986a1492f77ee7b61eadfd9d3d47be4494a512443e134637cd0cefd5  dogecoin-1.14.7-win32-debug.zip
2a3e71a806866137e5f4611681b63760ee37b30b0747f154f2d70c8c7d73b028  dogecoin-1.14.7-win32-setup-unsigned.exe
4350664a997afa4ec2dead336746c4b1d165187121ccfcca43913e9fb534af2b  dogecoin-1.14.7-win32.zip
9fed21b7d101e4b0f2547c384848dd1dbc90d5f6f281f7e27bc68746b7a994a1  dogecoin-1.14.7-win64-debug.zip
484e9d5d5a770ac854dc0086e8adfc96c944c0160460a2433fc10de12eb7d2ae  dogecoin-1.14.7-win64-setup-unsigned.exe
43613ff60e64fda77fa732c55c85531e50a18505b534fe6a982fe1906bbe499d  dogecoin-1.14.7-win64.zip
fb71042bcbd22ff7d718543e2b488df62ba942b5813c3a73e7347fe3988cd099  dogecoin-1.14.7-osx-unsigned.dmg
a7036963518422458d42c557844b1cc15804b98d87caa78fe83b9aac8866cdcb  dogecoin-1.14.7-osx-unsigned.tar.gz
85cd5e91fca4665b1606d87aa54e10804c5118f0bc4a4a9dee2305c25d7aa74d  dogecoin-1.14.7-osx64.tar.gz
```

**Comment by patricklodder** [comment]
For reference only: my LXC gitian shasums match the docker ones above:

```
9e1e7004cbfcb3c79012e0f66e5f8e12e72d2bca16e8ec67db66366a488b88a9  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
d14643080bc9bd5ffa83eeedd9a7e39ccdf2d420699c4cd9eef700d8578a80cd  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
508515c5e14e3c1027b4bb2dd3d16546460914ca5fb39ba5dccd8171e4eb39c9  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
a23cd1217e75f16da9a81562d5f3881b149c35df0e9b5e4bae6f9a632b0cc690  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
f7ba0db5ca41e332ffadaef409efae00e6aad7ab6d39aa22239efeca41255d3e  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
79e6039f2efefc94d28db3ff6e718c24653b6b84d851ff5fe402d4b3b4b208a6  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
fb71042bcbd22ff7d718543e2b488df62ba942b5813c3a73e7347fe3988cd099  dogecoin-1.14.7-osx-unsigned.dmg
a7036963518422458d42c557844b1cc15804b98d87caa78fe83b9aac8866cdcb  dogecoin-1.14.7-osx-unsigned.tar.gz
85cd5e91fca4665b1606d87aa54e10804c5118f0bc4a4a9dee2305c25d7aa74d  dogecoin-1.14.7-osx64.tar.gz
cfce5522ffcf6263300472b9d0b6a9a70271ef00a96532b82b789f7180eec468  dogecoin-1.14.7-win-unsigned.tar.gz
85f73547986a1492f77ee7b61eadfd9d3d47be4494a512443e134637cd0cefd5  dogecoin-1.14.7-win32-debug.zip
2a3e71a806866137e5f4611681b63760ee37b30b0747f154f2d70c8c7d73b028  dogecoin-1.14.7-win32-setup-unsigned.exe
4350664a997afa4ec2dead336746c4b1d165187121ccfcca43913e9fb534af2b  dogecoin-1.14.7-win32.zip
9fed21b7d101e4b0f2547c384848dd1dbc90d5f6f281f7e27bc68746b7a994a1  dogecoin-1.14.7-win64-debug.zip
484e9d5d5a770ac854dc0086e8adfc96c944c0160460a2433fc10de12eb7d2ae  dogecoin-1.14.7-win64-setup-unsigned.exe
43613ff60e64fda77fa732c55c85531e50a18505b534fe6a982fe1906bbe499d  dogecoin-1.14.7-win64.zip
93b5e982df544bd91c9888a5bb9142d7d4c2781ded3be3a984698c9a988e74ce  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
53b76ce2d7d92cc74a7122e7a7cfd0df337da0e13fded3893b1a241bc0b4ccaf  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
dde946511f5d66be25bf9e643ea056ad73914372732898c2831beddb02f3830a  dogecoin-1.14.7.tar.gz
```

**Comment by chromatic** [comment]
My signatures:

```
9e1e7004cbfcb3c79012e0f66e5f8e12e72d2bca16e8ec67db66366a488b88a9  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
d14643080bc9bd5ffa83eeedd9a7e39ccdf2d420699c4cd9eef700d8578a80cd  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
508515c5e14e3c1027b4bb2dd3d16546460914ca5fb39ba5dccd8171e4eb39c9  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
a23cd1217e75f16da9a81562d5f3881b149c35df0e9b5e4bae6f9a632b0cc690  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
f7ba0db5ca41e332ffadaef409efae00e6aad7ab6d39aa22239efeca41255d3e  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
79e6039f2efefc94d28db3ff6e718c24653b6b84d851ff5fe402d4b3b4b208a6  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
fb71042bcbd22ff7d718543e2b488df62ba942b5813c3a73e7347fe3988cd099  dogecoin-1.14.7-osx-unsigned.dmg
a7036963518422458d42c557844b1cc15804b98d87caa78fe83b9aac8866cdcb  dogecoin-1.14.7-osx-unsigned.tar.gz
85cd5e91fca4665b1606d87aa54e10804c5118f0bc4a4a9dee2305c25d7aa74d  dogecoin-1.14.7-osx64.tar.gz
cfce5522ffcf6263300472b9d0b6a9a70271ef00a96532b82b789f7180eec468  dogecoin-1.14.7-win-unsigned.tar.gz
85f73547986a1492f77ee7b61eadfd9d3d47be4494a512443e134637cd0cefd5  dogecoin-1.14.7-win32-debug.zip
2a3e71a806866137e5f4611681b63760ee37b30b0747f154f2d70c8c7d73b028  dogecoin-1.14.7-win32-setup-unsigned.exe
4350664a997afa4ec2dead336746c4b1d165187121ccfcca43913e9fb534af2b  dogecoin-1.14.7-win32.zip
9fed21b7d101e4b0f2547c384848dd1dbc90d5f6f281f7e27bc68746b7a994a1  dogecoin-1.14.7-win64-debug.zip
484e9d5d5a770ac854dc0086e8adfc96c944c0160460a2433fc10de12eb7d2ae  dogecoin-1.14.7-win64-setup-unsigned.exe
43613ff60e64fda77fa732c55c85531e50a18505b534fe6a982fe1906bbe499d  dogecoin-1.14.7-win64.zip
93b5e982df544bd91c9888a5bb9142d7d4c2781ded3be3a984698c9a988e74ce  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
53b76ce2d7d92cc74a7122e7a7cfd0df337da0e13fded3893b1a241bc0b4ccaf  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
dde946511f5d66be25bf9e643ea056ad73914372732898c2831beddb02f3830a  dogecoin-1.14.7.tar.gz
```

**Comment by chromatic** [comment]
Gitian signatures match and code changes look sensible. All that's left is a couple of people doing manual exploratory testing of the built binaries. I'll click through a few things myself. @xanimo can you do the same?

**Comment by chromatic** [comment]
Click-through testing worked fine in 64-bit x86 Linux. I'll hold for a day or two for others to try as well.

**Comment by xanimo** [comment]
> Gitian signatures match and code changes look sensible. All that's left is a couple of people doing manual exploratory testing of the built binaries. I'll click through a few things myself. @xanimo can you do the same?

yeah sure. will post my results shortly.

**Comment by xanimo** [comment]
compiled on x86_64-pc-linux-gnu jammy and everything passes. clicked through qt and can't find anything glaring or worth mentioning as it syncs. :+1: 

everything looks fine but lmk if you need me to test any binaries on mac and/or windows.

**Review by chromatic — APPROVED** [review]
ACK, code changes are sensible and match backports. All tests pass. Signatures match independent Gitian builds. Click-through tests look fine.

Anyone who wants to test Mac/Windows click-through is welcome. I think further testing will help us track things down (but the Linux dbus configuration is the one I wanted to test the most, so we appear to be good there).

**Pull request merged**
