### PR TITLE
Partial Translations for Korean

### PR DESCRIPTION
**Pull request by dogespacewizard**
not a coder, ive added some translations for some lines that weren't translated, for alot of the untranslated code i dont understand some of the stuff so i've left these untouched

by searching
type="unfinished"

you should be able to find the untranslated lines

### CODE REVIEW

**Review by steve-cw-chung — APPROVED** [review]
Translations look okay.

**Comment by patricklodder** [comment]
Thank you @dogespacewizard and @steve-cw-chung! Appreciate it!

**Review by patricklodder — APPROVED** [review]
utACK

**Comment by dogespacewizard** [comment]
from my count there was i think 59 lines that still need translation, ill try to teach myself some of these coding terms once time allows and return if possible to finish them off

hopefully another korean speaker who is actually a coder can get to these

**Pull request merged**
