### PR TITLE
Change key derivation path to be correct for Dogecoin

### PR DESCRIPTION
**Pull request by micaelmalta**

### CODE REVIEW

**Comment by patricklodder** [comment]
As noted in #2489: needs a solution for the installed base - any specific reason to put this in 1.14.x and not 1.21.x?

**Comment by micaelmalta** [comment]
@patricklodder All good for backward compatibility.

Old wallet will continue using the old derivation aka `m/0'/0'` and any new wallet will use `m/0'/3'`

**Comment by micaelmalta** [comment]
How did I test it:

1/ Create a brand new wallet with 1.14.4 version
2/ ./src/dogecoin-cli getnewaddress ""
3/  ./src/dogecoin-cli validateaddress xxx
    "hdkeypath": "m/0'/0'/1'"

4/ Compile with the new derivation 
5/ ./src/dogecoin-cli getnewaddress ""
6/  ./src/dogecoin-cli validateaddress xxx
    "hdkeypath": "m/0'/0'/2'"

**Comment by patricklodder** [comment]
Needs a rebase as #2487 fixed the (unrelated) whitespace issue already. After that I can approve & merge (have tested)

**Comment by micaelmalta** [comment]
Done!

**Review by patricklodder — APPROVED** [review]
ACK. Tested on a large 16k address wallet, works as advertised. I do think we need to document this fix somewhere, as there are now 3 years worth of clients out there with a deviation in their BIP44 path, but that can be picked up separately.

**Pull request merged**
