### PR TITLE
Disable UI elements for selecting zero-fee

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by langerhans** [comment]
BitcoinAmountField should allow to set a minimum of 1. Maybe that will be less confusing if anyone tries to use the custom fee amount field. Otherwise selecting 0 gives 1 fee, selecting 1 gives 1 fee, 2=2...  

Talking about `<widget class="BitcoinAmountField" name="customFee"/>`

**Comment by patricklodder** [comment]
@rnicoll this needs a rebase

**Comment by rnicoll** [comment]
Rebased!

**Comment by rnicoll** [comment]
Pushed an incomplete solution to the minimum fee field, for others to look at. Will try fixing it tomorrow (right now it appears the minimum property isn't set correctly)

**Comment by rnicoll** [comment]
Minimum field fixed, please test and let me know if there's any issues.

**Comment by patricklodder** [comment]
Works for me, ACK

**Pull request merged**
