### PR TITLE
Backport Bitcoin's share/rpcauth/rpcauth.py in rpcuser.py

### PR DESCRIPTION
**Pull request by Anish-M-code**
I simply backported changes from Bitcoin to modernize rpcuser.py , no new functionalities were introduced. This Pull request aims to close feature request https://github.com/dogecoin/dogecoin/issues/3352

### CODE REVIEW

**Comment by slightlyskepticalpotat** [comment]
After deleting the rpc authentication `.cookie` and using the script to generate a `rpcauth=` to add to my `dogecoin.conf` file, I'm able to use the provided rpc username/password with `dogecoin-cli. Using an incorrect password errors out. 

Everything appears to be working, tested on Ubuntu 22.04.
image

**Review by patricklodder — COMMENTED** [review]
Tested on arm64 macOS. Could use a squash, otherwise good to go.

@Anish-M-code do you want me to squash it for you?

**Comment by Anish-M-code** [comment]
@patricklodder , i would like if you could squash my pull request. can you please explain me how to squash commits in Github web UI or do you use git commandline to squash git commits.

**Comment by patricklodder** [comment]
>  i would like if you could squash my pull request

Done!

> do you use git commandline to squash git commits.

This. But I will have a look at what options we have inside the GitHub web UI once we're done with the release

**Comment by slightlyskepticalpotat** [comment]
Hey, any updates on this?

**Comment by chromatic** [comment]
This one is on my list next up, and I hope to get to it before the weekend.

**Review by chromatic — APPROVED** [review]
ACK; this addresses my concerns. Thank you, @Anish-M-code ! I appreciate this.

**Pull request merged**
