### PR TITLE
Combined multiple typo fixes

### PR DESCRIPTION
**Pull request by Sporklin**
Combined multiple typos fixes into one PR.

Devsnacks pls

### CODE REVIEW

**Comment by Sporklin** [comment]
Rebased

**Comment by rnicoll** [comment]
For some reason I can't get the tests to complete with these patches. I think it's the same 7 test we had issues with, with Travis. Will try again in the morning, probably just doing something daft.

**Comment by langerhans** [comment]
I'll give it a try

**Comment by langerhans** [comment]
Built from this branch:   
```
max@ubuntu:~/dogecoin$ ./src/test/test_dogecoin 
Running 124 test cases...

*** No errors detected

max@ubuntu:~/dogecoin$ ./src/qt/test/test_dogecoin-qt 
********* Start testing of URITests *********
...
Totals: 3 passed, 0 failed, 0 skipped
********* Finished testing of URITests *********
********* Start testing of PaymentServerTests *********
...
Totals: 3 passed, 0 failed, 0 skipped
********* Finished testing of PaymentServerTests *********
********* Start testing of BitcoinUnitsTests *********
...
Totals: 4 passed, 0 failed, 0 skipped
********* Finished testing of BitcoinUnitsTests *********
max@ubuntu:~/dogecoin$ 

```

**Comment by rnicoll** [comment]
ACK from me apart from the transaction tests, so looks good. Think I must have just been on the old version

**Pull request merged**
