### PR TITLE
Update block height used to determine relevant parameters

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by rnicoll** [comment]
Addresses https://trello.com/c/NtbVBsxm - have done a reindex on testnet, although should do a full resync just to be entirely certain.

**Comment by patricklodder** [comment]
utACK. Synched until 200k before i ran out of diskspace, can re-test tomorrow but hoping someone will beat me to it :)

**Comment by langerhans** [comment]
Did a reindex of mainnet with this on Windows. This causes a crash reproducible when reindexing block 849229. Last line I see in my debug.log is:


```
2015-09-08 19:32:57 UpdateTip: new best=cdf976f1c545e7840fcd8ca92fd60afae91209845a7a6fec3c0a38833d60df0d  height=849229  log2_work=64.902892  tx=20359087  date=2015-08-26 06:34:29 progress=0.963939  cache=5.0MiB(1915tx)
```

Block: https://chain.so/tx/DOGE/bddaf38f02f4e5c75b4d1d09b3ab10b1dc29d59537e856d4e3dcc7deec009a9d  
The only thing interesting about this block is that it is a v1 block. But iirc we had more than one v1 blocks after AuxPoW start. (I don't think that 40MM DOGE tx has anything to do with it?) Error code thrown is `0xC0000005` which is a memory access violation.  

Reverting this change allows me to reindex all the way to the end.

**Comment by rnicoll** [comment]
Turns out the lookup works 99.9% of the time, but breaks sometimes. Going to have to fix it at zero; should have a better way of ensuring we differentiate height-sensitive and height-insensitive consensus parameters to ensure we can't accidentally break this later.

**Comment by langerhans** [comment]
The needed params here are correct at height 0. So guess this is acceptable.

**Pull request merged**
