### PR TITLE
[Auto] Bitcoin PR batch Mon Feb 16 11:30:32 2015

### PR DESCRIPTION
**Pull request by rnicoll**
Contains:

`getrawchangeaddress` should fail when keypool exhausted + add tests
getblocktemplate: longpolling support (v2)
Bugfix: make CCoinsViewMemPool support pruned entries in underlying cache
Add missing FindNode prototype to net.h

### CODE REVIEW

**Comment by langerhans** [comment]
Needs rebase

**Comment by langerhans** [comment]
*pokes @rnicoll with a stick*

**Comment by rnicoll** [comment]
Rebased

**Comment by langerhans** [comment]
ACK

**Pull request merged**
