### PR TITLE
Update secp256k1 subtree

### PR DESCRIPTION
**Pull request by patricklodder**
WARNING: CONSENSUS CRITICAL -> so be careful!

This is the subtree we haven't updated since 1.14.0. I have been reluctant mostly because this is consensus critical code and risky because of that, and late last year after we updated the other ones I didn't think we could get enough eyes on it for this to go through. I think now we do. Additionally, the problem of not updating this grows the longer we wait, so this is the lets-bite-the-bullet proposal.

I picked bitcoin-core/secp256k1@44c2452fd3 as the target because:
1. This is at the time of writing the latest merged into Bitcoin Core's `master` branch, and
2. I didn't find any commits between this commit and bitcoin-core/secp256k1's master branch at the time of writing that were significant enough to take on more exposure than Bitcoin Core does. (I have not seen any related issues opened on Bitcoin Core's GitHub repo about this so far, but will continue to monitor.)

Additionally, because of that last commit, `44c2452fd3`, we will break ASLR on Windows (as we already do for `dogecoin-cli` - bad, but now also for dogecoin-qt - really bad) so I have backported a workaround from bitcoin/bitcoin@fbae8c59 into this PR as well.

Since the squash is huge, I think we need to do 3 things:

1. Review - or at least glance over - the changes done upstream
2. If we're satisfied with the results, merge this into 1.14.7-dev
3. Assess fitness for release before we push out 1.14.7: if we would push that out after a week or 2, we'll probably have to revert, but if we can incorporate this into a month or more of testing, CI runs and gitian builds, I think we're fine.

Open to change the approach.

### CODE REVIEW

**Comment by patricklodder** [comment]
Note to reviewers: you can verify the result of the squash by running something like this:

```bash
git clone https://github.com/bitcoin-core/secp256k1.git
git clone https://github.com/dogecoin/dogecoin.git
pushd secp256k1
git checkout 44c2452fd3
popd
pushd dogecoin
gh pr checkout 3082
diff -dur ../secp256k1 src/secp256k1
popd
```

**Comment by patricklodder** [comment]
(force pushed the last commit because I forgot to commit a typo fix)

**Comment by chromatic** [comment]
I've reviewed the ASLR changes and they look good. This'll take a while to get through the rest.

**Comment by patricklodder** [comment]
After talking with @chromatic I did some work on sifting through the subtree and where it was used in Bitcoin Core releases. I compared to Litecoin too, but Litecoin tags match bitcoin tags and subtree commits, so that didn't provide any additional information - I have omitted it.

Below is the release history of Bitcoin Core wrt the secp256k1 subtree between `8225239` that we have now, until `44c2452` that this PR proposes. 

- `subtree` is the commit on `bitcoin-core/secp256k1`
- `merge` is the merge commit of that subtree on `bitcoin/bitcoin`
- `release` is the first Bitcoin Core release tag that contained that commit
- `rls date` is the date of the release on `bitcoin/bitcoin`'s release page
- `days since` shows how many days the commit has been part of a Bitcoin Core release at the time of writing
- `commit delta` shows how many (non-merge) commits have been introduced on the subtree since the previous merge

| subtree | merge   | release   | rls date   | days since | commit delta
| :------ | :------ | :-------- | :--------- |  --------: | ------------:
| 44c2452 | [`913b1f2`](https://github.com/bitcoin/bitcoin/commit/913b1f2) | (master)  | -          | -          | 96
| 0559fc6 | [`dff0596`](https://github.com/bitcoin/bitcoin/commit/dff0596) | `v23.0`   | 2022-04-25 | 97         | 120
| efad350 | [`a5a447a`](https://github.com/bitcoin/bitcoin/commit/a5a447a) | `v22.0`   | 2021-09-14 | 320        | 64
| 3967d96 | 5803f5f | `v0.21.0` | 2021-01-15 | 562        | 272
| 0b70241 | 999968e | `v0.16.0` | 2018-02-26 | 1616       | 8
| 84973d3 | 5252827 | `v0.15.0` | 2017-09-14 | 1781       | 18
| 8225239 | 547a53d | `v0.14.0` | 2017-03-08 | 1971       | -

**Review by CryptoUnchained — APPROVED** [review]

**Comment by chromatic** [comment]
Confirmed with a modified version @patricklodder 's test script, and going through the commits now for one last check.

**Comment by patricklodder** [comment]
I'll start a gitian build then

**Comment by chromatic** [comment]
I skimmed the commits and they look valid per the subtree. I can't get a local test to pass without something like PR #3079 though, so I'm going to try working with that.

A rebase on 1.14.7-dev gave me a lot of broken pieces, so I'll try a different approach.

**Comment by chromatic** [comment]
Cherry picking the commit from #3079 sorted out the tests. We can compare guix builds and I think this will be ready for final review then.

**Comment by patricklodder** [comment]
> Cherry picking the commit from https://github.com/dogecoin/dogecoin/pull/3079 sorted out the tests. We can compare guix builds and I think this will be ready for final review then.

Subtree merges break the default rebase automation but should work with `--preserve-merges`. Let's see if we have matching gitian hashes and if we do, I'll do a clean rebase.

**Comment by patricklodder** [comment]
Hashes from my gitian build with LXC backend

```
8789bd657ab85821fb7c3928839b2ed97e0212c7d9ef23d0b1c41fd1f97059a2  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
42163610c8c1bf2be7244e3d6b96108296d2df7c25cc77e9644f99d9b26a4072  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
ccde8de16f30a69a68b5759bdf45a5f4cb1bc4aba4b30190b5728ffab3a3ef53  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
26eebdffded534cce79d9c7f78a32ca3db6410e06ed9453507a46c0aa6856ad5  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
5327d8627252a4606258a537dc4ce2230707bd6995c05327b3948ec1f9025943  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
bb88a06ef0f24f1f0beb50074a56253357fef64a39013e3a8528932b01f68dff  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
0de9f55956356257dc9702fb84f782ccf893ca19797c703c9fab4a20f47b7a91  dogecoin-1.14.7-osx-unsigned.dmg
99e91c15156fecee38b4c75b19e2f8cb3ed7e3953f2d38323573bd618d938df1  dogecoin-1.14.7-osx-unsigned.tar.gz
a0fe00af188153b7bea50616b1486a99d06f58385885420b45abac5233557a4a  dogecoin-1.14.7-osx64.tar.gz
d7db2ee72912c17098d01449e8a8922ca8123f34fc52b1b67c7b44f348fb81b4  dogecoin-1.14.7-win32-debug.zip
dd7bf8d7f23ca9409fe664fc685213a05d06208f6496d92a4445a4fff70ebfa9  dogecoin-1.14.7-win32.zip
87c602f9136226af81119b333266aef426a03e81fd2f287ad51a390bbe0b65e6  dogecoin-1.14.7-win64-debug.zip
275115bf710203f4b22ff1a48aae47ab16d97d477206542e2dabe592e4309d44  dogecoin-1.14.7-win64.zip
5b37f9ca3cf707f6b426156ba43f55fe051159e8cfc45b90aee5b2858d5b1926  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
66058f5e1f4e0b0edd2c1598e027953c996dbf3efa732d3fc9582ae34eb5c4c9  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
28efeb7a4b97ea854180c81156cb4b90c34f540595fe8f33195e770be3743566  dogecoin-1.14.7.tar.gz
```

**Comment by chromatic** [comment]
What command did you use to produce the gitian build? I used `./gitian-build.sh --docker --setup --build --verify -c 3099928b6a4350ee57add61a704ffd2edeb0e168` but want to make sure we're targeting the same commit/branch/ref.

**Comment by patricklodder** [comment]
I don't use that script so that we get a more broad comparison, but I think you should add my repo as `url` and you don't need `--verify`?

```
./gitian-build.sh --docker --setup --build -u https://github.com/patricklodder/dogecoin -c 3099928b6a4350ee57add61a704ffd2edeb0e168
```

If the hashes don't match, it's possible that this is another round of lxc issues - I'll run a docker build in the meantime.

**Comment by chromatic** [comment]
Here are my signatures from my invocation. I'll try your variant next to see if I did something unexpected:

```
778275e314180cdb6151eea4b94b9d62f4ee864899bbb722145f713d955858c6  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
271ca4f784c1d219089964b49d5da48b98150f3ffbcdf89f11dafe1057df1ea2  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
b4f1bc806dfc4b037f8f5a704feb435ee8809cc98c78560af29e6cd0dc752932  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
390880bd9f403a96fbd19d231c2d3d2451e95bf585b4c62fede9da79ea5f6319  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
f283b0cfd50cb457318bbd13cf18624572ea136a42d43be8208a528925cdbff4  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
aebc2d97d95d6218627dde5c5bfc8f026d5590c47a2113525c504f50f45d5a88  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
071c25a9e86fb083002f9f88f2c4845dd490eae15431751104ed67698a4769c3  dogecoin-1.14.7-osx64.tar.gz
c354b56962cd9d49282719f963b557778b97bb713678f6de50389c821a75972b  dogecoin-1.14.7-osx-unsigned.dmg
4bf258871c597b51545f822b765e95b075c731c88c40b4f9b5dac7c5db0755df  dogecoin-1.14.7-osx-unsigned.tar.gz
e166b2a62dadbd836c175eab8c3256ccb5bc5f3f9d874cb2282a1a5f0b4a2505  dogecoin-1.14.7-win32-debug.zip
0cc3ec9431483244e41770595fc555bd3abdaab5c6531c38ea0c0e64ce495844  dogecoin-1.14.7-win32-setup-unsigned.exe
583ad43c8a8bcbbb2d6fdf632ee966644f988c472e0e8998fbb645648c18120b  dogecoin-1.14.7-win32.zip
b1ffc4e42e552f72517be5e72e22538c3b3dd98607d6897939cefef75f8c5713  dogecoin-1.14.7-win64-debug.zip
eabf36bfe73f97fac54057a669d65e85bef8eb46fe7dbd5d4deed28df83104cb  dogecoin-1.14.7-win64-setup-unsigned.exe
dcb8fc8d8d88d4ee2983cc083796720f55e4ab31667192288aa1b0dd06a07eb4  dogecoin-1.14.7-win64.zip
f533d5f1c16679b51cf40175942cea1b33db2e25980be6e2aaefece09d03602c  dogecoin-1.14.7-win-unsigned.tar.gz
a906640c61e4ac7070413969cf268f044d81bb1b9615094d1d68e52f37289516  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
1bb7600cf4acf800b6c55f1a24ab31c3ce2fe1878affab337d952fe9db0e5e0e  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
432ffb797620b64b681b368d2d01ffa4f1ac16b7ac2dd3b99d5e5617d3a5ce9c  dogecoin-linux-1.14-res.yml
5ea194961cd8d2b7f7d24c1b2aa5f79d8ffd738c9c29f9331118ada6502a9a19  dogecoin-osx-1.14-res.yml
5f04cc530c64caac7bbfd8c9afe4c6416fc21d2913da9bc4d6a13df2215481fc  dogecoin-win-1.14-res.yml
49f7661153fa43e7a49ce8bd2d560875e568db5410b17292743b897e8cd2aef0  src/dogecoin-1.14.7.tar.gz
```

**Comment by xanimo** [comment]
```
778275e314180cdb6151eea4b94b9d62f4ee864899bbb722145f713d955858c6  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
271ca4f784c1d219089964b49d5da48b98150f3ffbcdf89f11dafe1057df1ea2  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
b4f1bc806dfc4b037f8f5a704feb435ee8809cc98c78560af29e6cd0dc752932  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
390880bd9f403a96fbd19d231c2d3d2451e95bf585b4c62fede9da79ea5f6319  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
f283b0cfd50cb457318bbd13cf18624572ea136a42d43be8208a528925cdbff4  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
aebc2d97d95d6218627dde5c5bfc8f026d5590c47a2113525c504f50f45d5a88  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
a906640c61e4ac7070413969cf268f044d81bb1b9615094d1d68e52f37289516  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
1bb7600cf4acf800b6c55f1a24ab31c3ce2fe1878affab337d952fe9db0e5e0e  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
f533d5f1c16679b51cf40175942cea1b33db2e25980be6e2aaefece09d03602c  dogecoin-1.14.7-win-unsigned.tar.gz
e166b2a62dadbd836c175eab8c3256ccb5bc5f3f9d874cb2282a1a5f0b4a2505  dogecoin-1.14.7-win32-debug.zip
0cc3ec9431483244e41770595fc555bd3abdaab5c6531c38ea0c0e64ce495844  dogecoin-1.14.7-win32-setup-unsigned.exe
583ad43c8a8bcbbb2d6fdf632ee966644f988c472e0e8998fbb645648c18120b  dogecoin-1.14.7-win32.zip
b1ffc4e42e552f72517be5e72e22538c3b3dd98607d6897939cefef75f8c5713  dogecoin-1.14.7-win64-debug.zip
eabf36bfe73f97fac54057a669d65e85bef8eb46fe7dbd5d4deed28df83104cb  dogecoin-1.14.7-win64-setup-unsigned.exe
dcb8fc8d8d88d4ee2983cc083796720f55e4ab31667192288aa1b0dd06a07eb4  dogecoin-1.14.7-win64.zip
49f7661153fa43e7a49ce8bd2d560875e568db5410b17292743b897e8cd2aef0  src/dogecoin-1.14.7.tar.gz
```

I'm using a custom script as well that is using docker but for some reason osx didn't finish compiling so I've just started an additional standalone run for those. Will post results shortly.

**Comment by xanimo** [comment]
```
c354b56962cd9d49282719f963b557778b97bb713678f6de50389c821a75972b  dogecoin-1.14.7-osx-unsigned.dmg
4bf258871c597b51545f822b765e95b075c731c88c40b4f9b5dac7c5db0755df  dogecoin-1.14.7-osx-unsigned.tar.gz
071c25a9e86fb083002f9f88f2c4845dd490eae15431751104ed67698a4769c3  dogecoin-1.14.7-osx64.tar.gz
```

**Comment by chromatic** [comment]
Looks like lxc is still the odd duck out then. Hm.

**Comment by xanimo** [comment]
> Looks like lxc is still the odd duck out then. Hm.

Yeah I had tried running lxc with both the gitian-build.sh script and a custom script and it kept erroring out when reaching the step that invokes `make-base-vm` in gitian-builder. I did get a little farther on one run but encountered the 'user ubuntu is not found' error. 😥

**Comment by patricklodder** [comment]
I've re-ran using lxc on a clean VM and everything matches -- except `dogecoin-1.14.7-x86_64-linux-gnu.tar.gz` and its debug tarball. I've also done docker on the same host, with the same result. This feels like an LXC or host configuration issue to me - would either of you be so kind to share your x86_64 linux debug tarball with me, so that I can do a binary compare?

In the meantime, I'll run this on metal to make sure that it's the environment causing this, and not the PR's code.

**Comment by chromatic** [comment]
I'll send you a download link out of band.

**Comment by xanimo** [comment]
I unfortunately only saved the *-res.yml files. If seeing the linux output would be useful let me know and I can throw in a gist.

**Comment by patricklodder** [comment]
Difference between my hashes and the ones listed above are caused by host configuration, not LXC this time. I am still investigating this in the background but it shouldn't be blocking for this PR:

1. when I built on a Xen-orchestrated host instead of an LXD-orchestrated one, my hashes match
2. It only exhibits on dogecoin-qt, all other binaries in the tarball match 

Binary compare below; the upper pane is my gitian-built binary on an LXD host, the lower one is @chromatic's:

bin diff dogecoin-qt

Because the changes for this PR are generic and would also change `dogecoind`, my gitian result is unlikely to be related to this PR - I'll create a separate issue for this once I get further along with investigating.

New build results from Xen host:

```
778275e314180cdb6151eea4b94b9d62f4ee864899bbb722145f713d955858c6  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
271ca4f784c1d219089964b49d5da48b98150f3ffbcdf89f11dafe1057df1ea2  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
b4f1bc806dfc4b037f8f5a704feb435ee8809cc98c78560af29e6cd0dc752932  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
390880bd9f403a96fbd19d231c2d3d2451e95bf585b4c62fede9da79ea5f6319  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
f283b0cfd50cb457318bbd13cf18624572ea136a42d43be8208a528925cdbff4  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
aebc2d97d95d6218627dde5c5bfc8f026d5590c47a2113525c504f50f45d5a88  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
f533d5f1c16679b51cf40175942cea1b33db2e25980be6e2aaefece09d03602c  dogecoin-1.14.7-win-unsigned.tar.gz
e166b2a62dadbd836c175eab8c3256ccb5bc5f3f9d874cb2282a1a5f0b4a2505  dogecoin-1.14.7-win32-debug.zip
0cc3ec9431483244e41770595fc555bd3abdaab5c6531c38ea0c0e64ce495844  dogecoin-1.14.7-win32-setup-unsigned.exe
583ad43c8a8bcbbb2d6fdf632ee966644f988c472e0e8998fbb645648c18120b  dogecoin-1.14.7-win32.zip
b1ffc4e42e552f72517be5e72e22538c3b3dd98607d6897939cefef75f8c5713  dogecoin-1.14.7-win64-debug.zip
eabf36bfe73f97fac54057a669d65e85bef8eb46fe7dbd5d4deed28df83104cb  dogecoin-1.14.7-win64-setup-unsigned.exe
dcb8fc8d8d88d4ee2983cc083796720f55e4ab31667192288aa1b0dd06a07eb4  dogecoin-1.14.7-win64.zip
a906640c61e4ac7070413969cf268f044d81bb1b9615094d1d68e52f37289516  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
1bb7600cf4acf800b6c55f1a24ab31c3ce2fe1878affab337d952fe9db0e5e0e  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
```

All match.

**Review by chromatic — APPROVED** [review]
Based on review of the commits, cross-checking against Bitcoin's adoption of this subtree, and Gitian hashes, good to go from me.

We'll leave this PR open for at least 24 hours before merging, per policy.

**Pull request merged**
