### PR TITLE
Enable importprivkey, importpubkey, importaddress in pruned mode 

### PR DESCRIPTION
**Pull request by victorsk2019**
Greetings!

This PR aims to "unlock" `importprivkey`, `importpubkey`, `importaddress` RPC methods in pruned mode mentioned in #3631.  

The testing I did (in addition to `rpc-tests` and boost test runs) was as follows: have 3 Dogecoin Core installations A (full blockchain version 1.14.8) , B (pruned mode `-prune=2201` from 'master' with this implementation), C (same as B).  I would send small funds from A to B, then import private key, public address, or public key from B into C.  Then send funds back from C to A (having some amount also debited from B because B and C share a private key and address when C is generating input for TX) and do this in circle several times at each code change I did and the RPC methods worked every time.  Here is the relevant excerpt from from `debug.log` (with added printout for debugging) for C:

```
...
2024-09-18 00:29:56 LoadBlockIndexDB: last block file = 1123
2024-09-18 00:29:56 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=1291, size=93637696, heights=5381480...5382771, time=2024-09-17...2024-09-17)
2024-09-18 00:29:56 Checking all blk files are present...
2024-09-18 00:29:57 LoadBlockIndexDB(): Block files have previously been pruned
2024-09-18 00:29:57 LoadBlockIndexDB: transaction index disabled
2024-09-18 00:29:58 LoadBlockIndexDB: hashBestChain=d75d305e6a9a548a8e479b2b9691ee6e9327d3398ea67ec045981444150f7480 height=5382771 date=2024-09-17 23:59:29 progress=0.999978
2024-09-18 00:29:58 init message: Rewinding blocks...
2024-09-18 00:30:09 init message: Verifying blocks...
2024-09-18 00:30:09 Verifying last 6 blocks at level 3
2024-09-18 00:30:09 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2024-09-18 00:30:09 No coin database inconsistencies in last 7 blocks (249 transactions)
2024-09-18 00:30:09  block index           36461ms
2024-09-18 00:30:09 init message: Loading wallet...
2024-09-18 00:30:09 nFileVersion = 1210000
2024-09-18 00:30:09 Keys: 0 plaintext, 6028 encrypted, 6035 w/ metadata, 6028 total
2024-09-18 00:30:09  wallet                   60ms
2024-09-18 00:30:09 setKeyPool.size() = 1993
2024-09-18 00:30:09 mapWallet.size() = 27
2024-09-18 00:30:09 mapAddressBook.size() = 36
2024-09-18 00:30:09 Unsetting NODE_NETWORK on prune mode
2024-09-18 00:30:09 init message: Pruning blockstore...
2024-09-18 00:30:09 mapBlockIndex.size() = 5382791
2024-09-18 00:30:09 nBestHeight = 5382771
2024-09-18 00:30:09 torcontrol thread start
2024-09-18 00:30:09 AddLocal([2001:569:50fd:cd00:f8fd:b0be:653b:2716]:22556,1)
2024-09-18 00:30:09 Discover: IPv6 wlp59s0: 2001:569:50fd:cd00:f8fd:b0be:653b:2716
2024-09-18 00:30:09 AddLocal([2001:569:50fd:cd00:fce0:614e:fe2d:137e]:22556,1)
2024-09-18 00:30:09 Discover: IPv6 wlp59s0: 2001:569:50fd:cd00:fce0:614e:fe2d:137e
2024-09-18 00:30:09 init message: Loading addresses...
2024-09-18 00:30:09 Imported mempool transactions from disk: 1 successes, 0 failed, 0 expired
2024-09-18 00:30:09 Loaded 24401 addresses from peers.dat  63ms
2024-09-18 00:30:09 init message: Loading banlist...
2024-09-18 00:30:09 init message: Starting network threads...
2024-09-18 00:30:09 net thread start
2024-09-18 00:30:09 dnsseed thread start
2024-09-18 00:30:09 addcon thread start
2024-09-18 00:30:09 opencon thread start
2024-09-18 00:30:09 init message: Done loading
2024-09-18 00:30:09 msghand thread start
2024-09-18 00:30:09 GUI: Platform customization: "other"
2024-09-18 00:30:10 receive version message: /Shibetoshi:1.14.8/: version 70015, blocks=5382799, us=50.92.239.94:38084, peer=0
2024-09-18 00:30:20 Loading addresses from DNS seeds (could take a while)
2024-09-18 00:30:20 75 addresses found from DNS seeds
2024-09-18 00:30:20 dnsseed thread exit
2024-09-18 00:30:24 UpdateTip: new log2_work=76.272804 tx=350348918 date='2024-09-18 00:29:07' progress=0.999999 
...
cache=1.6MiB(2314tx)
2024-09-18 00:30:30 -> current chainActive.tip() height: 5382799 
2024-09-18 00:30:30 -> value of starting rescan index: 5347545 
2024-09-18 00:30:36 AddToWallet debaa0697b1c87fb3915d9bef55a0890084c7465af737a6e26fbb18eb3943202  
2024-09-18 00:30:39 AddToWallet 26936d475cdc3fce4e7004c918a546c06b50d0b768298c35e57e978112d2ae48  
2024-09-18 00:30:39 AddToWallet f1a7316a8aa6ce378f9cd934743d85885995f016221e8f79c8f70436eebffd87  
2024-09-18 00:30:39 AddToWallet c98e104f27475966e7dc37fd30c2e5d87cde90f4ae3efe1fb0146b32856d8882  
2024-09-18 00:30:40 AddToWallet 01f5a3fc5ddbbe4b4e39c04caa7069c233852fb23965c1a2c248bdb5a11d43e4  
2024-09-18 00:30:41 AddToWallet cba15455727d97f042a7853e2f2dfa1ea65ef15a973196dbb4008d04d0d4f607  
2024-09-18 00:30:58 AddToWallet e505aae05353c6c6721a238d9b8be98542b38997a31b5794a98b7a5ec35faa65  
2024-09-18 00:30:58 AddToWallet e6ef8c66b89f9fe25b37555c3e73e144d9b2b67f8433bdf18d047c6ecc5ffee2  
2024-09-18 00:30:58 AddToWallet a1e2c7fa9c4098a43cb79fbebc1e97d2bc374eba4e11dd62a8cdade3e065eaaf  
2024-09-18 00:30:58 AddToWallet 4ebb0f50b3ff949eb11e78e3e7be3e55351499ccca6905f9f3590e660cb35435  
2024-09-18 00:31:00 AddToWallet 48aaa8cf391c06508e724aa22eb2f9062b0f7b7c767e643562db749bad1791ea  
2024-09-18 00:31:01 AddToWallet 4155d46facd9e5d871cfd315d76312e89484df987497d355c8aefa1594b71014  
2024-09-18 00:31:03 AddToWallet 1e93422f3641d7f3fdd75e6ac09daaaee3d528da143fed035668d6064c047f60  
2024-09-18 00:31:03 AddToWallet dfe1383efa73ed7705ae0d61a7efbe39c69e55561ab7f7d4f23d474f6c5c9758  
2024-09-18 00:31:03 AddToWallet 10d45ceaff5c381bb54792713e51ac17339743853fe42a589eb19e7ad3546bdb  
2024-09-18 00:31:03 AddToWallet 5ea3d74c24eb4dc7ade2ec4a6d9328d9eb6ba10cd0beb2edb34e6edf06e26c21  
2024-09-18 00:31:03 AddToWallet 60152e80e962d41138b9e580553cf7d24ea23ef0e642663085d11736f4138f0c  
...
```
This implementation works thanks to the loop in `GetHeightForRescan() ` function implemented previously by other developers which also terminates at the cut off point of a pruned blockchain and the block index can serve as a starting index for rescanning.  If this approach is accepted, then maybe we introduce additional scanning functionalities in pruned mode suggested previously?  "small moves"  🙂  Thank you.

### CODE REVIEW

**Comment by slightlyskepticalpotat** [comment]
I will try to give this a test sometime next week as my wallet is usually `-prune=2200`.

**Comment by victorsk2019** [comment]
Quick update: I did 2 more additional tests in pruned mode with random height `-prune=5687` (synchronizing and pruning from the beginning), all tests successful.  

I also considered an "edge-case" with using `importprivkey` when there is nothing to re-scan.  In this scenario someone may want to import private key into a newly installed Dogecoin Core right away but with no internet connection, say, WiFi is not connected.  I used `-prune=10123`, launched new installation of Dogecoin Core in pruned mode with no internet connection, and imported private key.  So the `nHeight` value of `chainActive.Tip()` is 0 and the while-loop terminating condition also works - it evaluates to `false` immediately and the body of the loop not executed and `GetHeightForRescan()` returns 0.  Once the block synchronization with pruning was done, I got correct balance for imported private key I did at the start of synchronization: 14.99774000 DOGE 😊.  I then again successfully tested with different values for `importprivkey`, `importpubkey`, `importaddress` for `-prune=10123`.  Thanks.

**Comment by patricklodder** [comment]
@victorsk2019 what happens when I have an utxo from a block height lower than the lowest non-pruned block?

**Comment by victorsk2019** [comment]
@patricklodder

Hi.  Thank you for bringing this up.  I tested importing private key with utxo from block `4,325,516` using `-prune=2201` but didn't get my 3 doges imported from that address 🙁.  Seems that I erroneously assumed that when chaintip is reached after re-scanning in pruned mode the correct balance would always appear up to date.

**Comment by victorsk2019** [comment]
> @victorsk2019 what happens when I have an utxo from a block height lower than the lowest non-pruned block?

Well, based on what I just learned I could suggest adding general warning message when `importprivkey` is run stating that utxo balances will not appear if they are included in non-pruned blocks.  This is similar to the message that appears during synchronization process on full blockchain installation: "Recent transactions may not yet be visible, and therefore your wallet's balance might be incorrect".

Another possibility is to examine functions like `AddToWalletIfInvolvingMe()` and possibly implement a TX counter which would count transactions for the address being imported and, if it is 0, then issue this warning message and also advise to perhaps increase the pruned block size.  Or, close this PR since this test scenario is not met 🙂

Thank you.

**Comment by patricklodder** [comment]
> [..] applied to not being able to retrieve wallet TXs that go beyond non-pruned blocks, not the actual balance.

This is actually a correct assumption but the code isn't there to scan the utxo db too and create incomplete (!!!) entries in the wallet for it. So here's what I'd propose:

1. Implement a function that scans the utxoset for a set of keys that can be called by the wallet
2. Implement a wallet function to call this specific function
3. Create a separate rpc method to call the wallet function
4. Release that, with a warning, and document the behavior well - prevent getting a gazillion issues.
5. if that works in the field and any bugs found are fixed, we can see if we can integrate this into rescan, to make the user experience a bit more seamless (including this pull request)

Thoughts?

As it stands right now, without a solution like that, I'd give this a concept NAK because it removes safety constraints without solving the issue why they are there in the first place: the inability to restore at the very least the full balance for a wallet.

**Comment by victorsk2019** [comment]
Hi,

>the code isn't there to scan the utxo db too and create incomplete (!!!) entries in the wallet for it.

Thank you for clarifying this.  One other idea I thought looking into is see, if it is possible, to scan TXs first before doing the actual key importing process.  If the TXs are not found, then issue error message that no TXs are found, key cannot be imported and advise to increase pruned block number.  Thank you.

**Comment by victorsk2019** [comment]
Hi,

Just a quick note, maybe somebody will find this useful, its probably a naïve approach, but per the requirements in https://github.com/dogecoin/dogecoin/pull/3653#issuecomment-2385596777 and implemented a function 

`CAmount CWallet::ScanForWalletUTXO(CBlockIndex* pindexStart)`

which is basically a copy of `ScanForWalletTransactions()` except when iterating over TXs for each block I used `utxo_total` to try and accumulate utxo value like so:

```
for (size_t posInBlock = 0; posInBlock < block.vtx.size(); ++posInBlock) 
{
   utxo_total += GetCredit(*block.vtx[posInBlock],ISMINE_SPENDABLE);
}
```
Then, I implemented an RPC method `gettotalutxoforkey` (a copy of `importprivkey`) that calls `ScanForWalletUTXO()`, tested it for TX with key/address for my 3 Doges contained in TX in block `4,325,516`, and got 0 balance 🙁.

I am also considering a different approach using `CCoinsView` and looking for ideas in `blockchain.cpp` 

`GetUTXOStats(CCoinsView *view, CCoinsStats &stats)`

but the process there also seems to iterate over blocks to retrieve `utxo` information, analogous to what is done in CWallet.  I am not sure if attempting to retrieve utxo values for a specific key (assuming it's possible) using approach with `CCoinsView` and `CCoins` classes instead would be any different?  What I mean is both approaches seem to do the same thing: iterate over TXs in blocks to retrieve `vout` information for utxo.  Or, do classes in `coins.h` have access to more information about TXs? Thanks.

**Comment by victorsk2019** [comment]
Just to add some recent observations I made (some inner workings takes time to figure out) which also answer questions I had in https://github.com/dogecoin/dogecoin/pull/3653#issuecomment-2392636290

To test if I can retrieve balance for address `DMfd7y5q1cQCMQL6Uiq12icVnN7B9CsPuV` in pruned mode `-prune=2201`, I have modified `GetUTXOStats()` function used by `gettxoutsetinfo` RPC method in the for-loop that iterates over `vout` array (about line 900 in `blockchain.cpp`:

```
...
CTxDestination address;
ExtractDestination(coins.vout[i].scriptPubKey, address);
std::string str_address = CBitcoinAddress(address).ToString();
if (str_address == "DMfd7y5q1cQCMQL6Uiq12icVnN7B9CsPuV")
{
    LogPrintf("=> nValue for address DMfd7y5q1cQCMQL6Uiq12icVnN7B9CsPuV: %i\n", coins.vout[i].nValue); 
}
...
```
and got the following in `debug.log`:
```
=> nValue for address DMfd7y5q1cQCMQL6Uiq12icVnN7B9CsPuV: 300000000
```
without unit formatting function applied, of course.

So, I think this functionality can be modified when scanning for utxo for a private key set.  For example: 1) obtain corresponding address to a key set entered 2) scan for utxo value for this address using `CCoins` and `CCoinsView` classes (though I still don't quite understand where this particular data is coming from because tested address didn't seem to show up when scanning pruned blocks 😚).

**Comment by patricklodder** [comment]
> I still don't quite understand where this particular data is coming from

From the utxo database. This doesn't get pruned ever because on a pruned node this is the only way to tell if there is no double spend of a particular coin.

**Comment by victorsk2019** [comment]
Hi,

Some additional notes: I've implemented a work-in-progress [rough draft](https://github.com/victorsk2019/dogecoin/commit/d1aa5d00f7b6c8d5df5a1833e6a5045c3bca8dbe) on a branch in my repository for getutxoforkey` RPC which takes private key as an argument and scans utxo and returns raw unformatted utxo value.  It doesn't have error-checking for arguments or help section yet.

I "cherry picked" some implementations from other RPCs like `gettxoutsetinfo`, its helper function and `importprivkey` because there is some overlap in functionalities.  

This is just to show one possible direction that we can take towards implementing scanning of utxos in pruned mode.  

On Dell XPS i7-8750H CPU @ 2.20GHz, It took 2-6 minutes (depending on private key I tested) for RPC to return.  Its interesting, but it took longer for a key with address created in 2024 to be found than in 2022, which makes me wonder if running time is more efficient than O(n) because, had records been sequential, I think utxo from 2024 would be found faster than in 2022.  There's still a lot to figure out for me but it really is fun because I get to put to use knowledge from C++ and algorithm design courses I took many years ago 😎.  Much obliged.

**Comment by victorsk2019** [comment]
Hi,

I've looked into ways to optimize scanning time of utxo records for this approach and I think the only way to optimize is to introduce additional required height RPC argument.  This could even be better as the user would be able to confirm their utxo value by referencing a block where it is recorded.  

If using this approach, there are a ton of CCoin elements to iterate over, for example, for block `5400082` I had `1722` CCoin elements.  So the solution I implemented is to 1) iterate over entire utxo set and collect and store CCoins elements for a specified height 2) iterate over this subset to retrieve address with its corresponding utxo value.  I tried to skip 2) and apply retrieving utxo for specific height when looping over the entire set, but seemed to be getting higher CPU usage (and had to pull out my laptop cooling pad 😂).    In my humble opinion, first iterating over entire set, storing hight-based CCoins and iterating again over reduced subset for the same height seems to be less resource-intensive.  The time to scan utxo records has significantly improved, but it is always more or less the same because we always scan entire utxo records, plus some variable amount of subset records.

Please, feel free to check my [updated commit](https://github.com/victorsk2019/dogecoin/commit/7a8b02f124ddef66a02a4bbde2e4ea47afb55dfa).  Is this something that could be submitted as a draft PR?

Thank you,
Victor.

**Pull request closed without merging**
