### PR TITLE
Fixate v1.14.4 release

### PR DESCRIPTION
**Pull request by patricklodder**
Fixates the version, sets release flag. To be merged after everything else is in.

### CODE REVIEW

**Review by michilumin — APPROVED** [review]
all number increments appear to be correct.

**Comment by patricklodder** [comment]
This can go in right after #2449 - feel free to merge once that's in.

**Review by jadehamel — APPROVED** [review]

**Comment by Star6654** [comment]
Ok

**Review by macotouenaca — COMMENTED** [review]
ビックマネ

**Review by macotouenaca — COMMENTED** [review]
ビックマネ

**Review by macotouenaca — COMMENTED** [review]
ビッグマネー

**Pull request merged**
