### PR TITLE
Add NODE_BLOOM service bit

### PR DESCRIPTION
**Pull request by langerhans**
Inspired by bitcoin/bitcoin#6579 I thought we should bring back our #361 for compatibility.

Protocol version is already correct so that didn't need a bump.

### CODE REVIEW

**Comment by patricklodder** [comment]
Needs protocol version increase.

Also, am considering NAK-ing this so that we can also have an alt fight :)

**Comment by patricklodder** [comment]
There's a mismatch between 1.8.3 and 1.10 regarding nServices flags:

in 1.8.3, `NODE_BLOOM` is `1 << 1` => `0x02`
in 1.10, `NODE_GETUTXO` is `1 << 1` => `0x02` and `NODE_BLOOM` is `1 << 2` => `0x04`

recommend recoding NODE_BLOOM as `1 << 1` and NODE_UTXO as `1 << 2` for backward compatibility.
see also [the original pr](https://github.com/leofidus/dogecoin/blob/63bd740c8ab8dd9a0a07fb038cd595528eb3d3aa/src/protocol.h#L68)

**Comment by langerhans** [comment]
As far as I have seen, the only implementation of this is in bitcoinj/dogecoinj. And there, it has always been incompatible as it seems, as seen here: https://github.com/langerhans/dogecoinj-new/blob/master/core/src/main/java/com/dogecoin/dogecoinj/core/VersionMessage.java#L37-L40  

Given that we want to move to libdohj instead and I think this part of the library is not overridden by it, I'd argue we break compatibility in this place to actually start being compatible to the client implementations.  

Well, it all kinda depends on if the upstream commit is merged anyway. Cause so far no other implementation actually uses this flag. So it's not really a breaking change overall, is it?

**Comment by patricklodder** [comment]
I think it doesn't really matter what implements it now because as long as it's possible to run a 1.8.0-1.8.2 client (releases that are already out there) and have a valid blockchain (which will be the case for everyone but miners) there are clients out there where the meaning of the 2nd service bit is indicating bloom filter support. I am assuming Dogecoin Core is in fact the reference implementation and not bitcoinj.

---

If we would merge this as-is, future implementations that want to check for the `NODE_NETWORK` bit or the `NODE_GETUTXO` bit will need to check the client version string in order to make a decision which bit means what. This increases risk for errors in whatever someone wants to do with these service bits AND requires an update every time we release a new minor version.

checking `NODE_BLOOM` using something bitcoinj-derived, this would mean:
```java
boolean supportsBloom = false;
VersionMessage peerVersion = peer.getPeerVersionMessage();

// check subVer explicitly
if (peerVersion.subVer.matches("Shibetoshi:1.10")) {
  supportsBloom = (peerVersion.localServices & 0x04) != 0;
} else if (peerVersion.subVer.matches("Shibetoshi:1.8")) {
  supportsBloom = (peerVersion.localServices & 0x02) != 0;
} // else if matches 1.11 ... etc
```

and checking `NODE_GETUTXO`:
```java
boolean supportsGetUtxo = false;
VersionMessage peerVersion = peer.getPeerVersionMessage();

// check subVer explicitly
if (peerVersion.subVer.matches("Shibetoshi:1.10")) {
  supportsGetUtxo = (peerVersion.localServices & 0x02) != 0;
} // else if matches 1.11 ... etc
```

---

If we would increase the protocol version then the implementation would at least be a little bit easier because protocol version 70003 didn't have the `NODE_GETUTXO` flag, so that check can be greatly simplified, plus one doesn't have to parse the "user-agent" to distinguish between bitmasks, just protocol version. This would be a better solution as it enables backward-compatibility in implementations more easily (but the protocol would still not be backward compatible.)

checking `NODE_BLOOM`:
```java
boolean supportsBloom = false;
VersionMessage peerVersion = peer.getPeerVersionMessage();
if (peerVersion.clientVersion >= 70004) {
  supportsBloom = (peerVersion.localServices & 0x04) != 0;
} else if (peerVersion.clientVersion <= 70003) {
  supportsBloom = (peerVersion.localServices & 0x02) != 0;
}
```

and checking `NODE_GETUTXO`:
```java
VersionMessage peerVersion = peer.getPeerVersionMessage();
boolean supportsGetUtxo = peerVersion.clientVersion >= 70004 && 
                          (peerVersion.localServices & 0x02) != 0;
```

---

If we both increase the protocol version and re-order the service bits as i proposed in my previous comment, then the protocol will be backward compatible and any client can query the service string in a straightforward way.

checking `NODE_BLOOM`:
```java
VersionMessage peerVersion = peer.getPeerVersionMessage();
boolean supportsBloom = (peerVersion.localServices & 0x02) != 0;
```

and checking `NODE_GETUTXO`:
```java
VersionMessage peerVersion = peer.getPeerVersionMessage();
boolean supportsGetUtxo = peerVersion.clientVersion >= 70004 && 
                          (peerVersion.localServices & 0x04) != 0;
```

**Comment by langerhans** [comment]
Pulled in your change and rebased.

**Comment by patricklodder** [comment]
Such consensus :)

**Comment by patricklodder** [comment]
ACK for me now. @rnicoll any thoughts?

**Comment by rnicoll** [comment]
Looks good to me!

**Pull request merged**
