### PR TITLE
Update versionbit activation windows to match 1.14

### PR DESCRIPTION
**Pull request by rnicoll**
To review after https://github.com/dogecoin/dogecoin/pull/1802

### CODE REVIEW

**Review by patricklodder — COMMENTED** [review]
Why are these values different from what we actually used in the v4 soft fork?

**Comment by rnicoll** [comment]
So (and I need to double check all of this), it looks the values are meant to be same for both block upgrades, and version bit driven forks. As we ended up with two sets of values, one for block upgrades and one for version forks, my default has been to copy in the version fork numbers as we have no block upgrades coming, at least until I can be sure changing these from 1.14 can't risk a hard fork.

Probably best left alone until I take it out of draft.

**Comment by patricklodder** [comment]
Since we haven't activated BIP9 for versionbits and weren't planning to because it's a nasty fork w/ AuxPoW, last time we talked (documented in #1798 too) and we were planning on doing block updates only - what is the use for keeping version bits?

**Comment by rnicoll** [comment]
I tend not to cut code, simply because it makes it harder to merge upstream changes later, but I'm fairly unfussed either way (and acknowledge cutting it means we avoid any nasty surprises). If that's the preferred option I'll replace this PR later on.

**Comment by rnicoll** [comment]
Okay looks like we should maintain both sets of values independently, to match 1.14.

**Pull request closed without merging**
