### PR TITLE
Made the README Much Wow

### PR DESCRIPTION
**Pull request by WilliamWelsh**
Made the README much wow. Centered the title, logo, and badges. Added two badges that redirect to the website: "dogecoin" and "much wow" and removed the period that was included in the website's hyperlink.
Before & After
image

### CODE REVIEW

**Comment by irvineAlgotrading** [comment]
honestly I think this addition is long overdue!!!

**Comment by Arrow2001** [comment]
Aye, great stuff. Now dogecoin get aff yer arse an add it

**Review by alii — APPROVED** [review]

**Comment by MichelBaie** [comment]
such a good modification !

**Review by itsalb3rt — DISMISSED** [review]
Cool!

**Review by MichelBaie — APPROVED** [review]

**Comment by mnz1988** [comment]
I want to help with translating the dogecoin website and wallet to the Persian language. how can I do that?

**Comment by incognitojam** [comment]
@mnz1988 Open a pull request on the [dogecoin.com repo](https://github.com/dogecoin/dogecoin.com/pulls) with your changes (creating a new file in `assets/i18n` folder), see the other PRs as an example

**Comment by DogecoinBoss** [comment]
I would center the payout schedule as well.

**Comment by Dylan700** [comment]
Definitely a much better layout than before. Love the new badges too 🥇

**Comment by rnicoll** [comment]
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

git fetch origin
git rebase -i origin/1.14.4-dev

It will then bring up an editor. If you remove the 2 commits before the one you want. Please check the result then force push it. Thank you!

**Comment by WilliamWelsh** [comment]
> 
> 
> I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:
> 
> git fetch origin
> git rebase -i origin/1.14.4-dev
> 
> It will then bring up an editor. If you remove the 2 commits before the one you want. Please check the result then force push it. Thank you!

Done 👍

**Review by rnicoll — APPROVED** [review]

**Comment by rnicoll** [comment]
Thank you!

**Comment by MichelBaie** [comment]
Perfect

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________

**Pull request merged**
