### PR TITLE
Fixing indonesian (id_ID) translation

### PR DESCRIPTION
**Pull request by elybin**
Fixing some translation. Really need your help to review the code. Thanks.

Changes in this PR:
- [x] Syncing with `bitcoin_en.ts`
- [x] Replacing `Anda` with `Kamu` for more casual translation 
- [x] Reordering follows `bitcoin_en.ts` order 
- [x] Fixing some typos 
- [x] Finishing `<name>dogecoin-core</name>` section.

### CODE REVIEW

**Comment by elybin** [comment]
Referenced to #1429

**Comment by rnicoll** [comment]
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

```
git fetch origin
git rebase -i origin/1.14.4-dev
```

It will then bring up an editor. If you remove the 3 commits before the one you want. Please check the result then force push it, and it should just change the document.

Thanks.

**Comment by rnicoll** [comment]
Thank you! Trying to find someone who can review, now.

**Comment by patricklodder** [comment]
closing & reopening to retrigger CI.

**Comment by rnicoll** [comment]
I've raised https://github.com/elybin/dogecoin/pull/1 which should fix the compilation issues.

**Comment by elybin** [comment]
> I've raised [elybin#1](https://github.com/elybin/dogecoin/pull/1) which should fix the compilation issues.

@rnicoll Sorry for the late reply, I already merge and fixing some minor issues. 
Also rebasing them with the latest `origin/1.14.4-dev` branch.

**Review by rnicoll — APPROVED** [review]
I've done spot checks on translation, seem fine, certainly a lot better than they were.

**Comment by rnicoll** [comment]
Merging as a significant step in the right direction, and we can refine later.

**Pull request merged**
