### PR TITLE
Issue templates updated to prevent spam in repository

### PR DESCRIPTION
**Pull request by roman-rr**
Issues are pretty messy. Good templates should helps.

### CODE REVIEW

**Review by skoll43 — APPROVED** [review]

**Review by skoll43 — APPROVED** [review]

**Comment by roman-rr** [comment]
@skoll43 Is any ways to fix Travis CI jobs ? I found that PPA is not added for Postgres and Cassandra.

**Comment by roman-rr** [comment]
@skoll43 Ok, then only issues templates in changes and can be merged.

**Comment by Priyesh2109** [comment]
can i get some free dogecoin.

**Comment by davidmroth** [comment]
> can i get some free dogecoin.

No!

**Review by l4p4 — APPROVED** [review]
nice!

**Review by rnicoll — APPROVED** [review]

**Comment by rnicoll** [comment]
Thanks!

**Review by andrp92 — COMMENTED** [review]
Great.!

**Comment by mspaansen** [comment]
😀

**Pull request merged**
