### PR TITLE
Replace OpenSSL hash functions with built-in implementations

### PR DESCRIPTION
**Pull request by rnicoll**
* Introduces the classes CSHA256 and CSHA512 in crypto/sha2.{cpp,h}, CSHA1 in crypto/sha1.{cpp,h} and CRIPEMD160 in crypto/ripemd160.{cpp,h}.
* The HMAC-SHA512 implementation is moved to sha2.{cpp,h} as well, with a similar interface.
* In hash.h, CHash256 (=double SHA256) and CHash160 (SHA256 + RIPEMD160) are added.
* The rest of hash.h is refactored to use those classes.
* The internal miner is also modified to use CHash256 (hiding the inner SHA256 workings).
* The getwork() RPC call is removed.
* The getworkaux() RPC call is removed.

Derived from bitcoin/bitcoin#4100

### CODE REVIEW

**Comment by langerhans** [comment]
Restarted Travis casue it stalled

**Comment by patricklodder** [comment]
I'm doing some tests and expect to have some small, additional patches

**Comment by langerhans** [comment]
Going to give this a try now.  
@patricklodder: I think it would be okay if you submit your patches afterwards in a separate PR. Leaving this here open holds up progress on the spreadsheet of doom ;D

**Comment by langerhans** [comment]
Looks good with the last addition. Merging for now so we can progress further with the other things. Thanks :)

**Pull request merged**
