### PR TITLE
fixate v1.14.6

### PR DESCRIPTION
**Pull request by patricklodder**
Fixates the version, marks as release, sets the year of release.

Blocked until we make final decisions on all open PRs under the 1.14.6 milestone.

### CODE REVIEW

**Review by chromatic — APPROVED** [review]
ACK. Tested on 64-bit x86 Linux. All tests pass. Good to go!

**Comment by chromatic** [comment]
Everything is in, so 1.14.6 is good to go.

**Comment by michilumin** [comment]
Built here on MacOS 12.4 M1 (under Rosetta of course / unfortuantely ) just for a bit of posterity, and looks gtg. much excite.

**Review by CryptoUnchained — COMMENTED** [review]
- 🙏

**Comment by ajsauthor** [comment]
Ajs

**Comment by ajsauthor** [comment]
Ajs

**Review by Imebeez — COMMENTED** [review]
[]()

**Review by jacksonbinh4 — COMMENTED** [review]
Can retrieve my dogecoin back please someone

**Pull request merged**
