### PR TITLE
Added IntelliJ IDEA in .gitignore and removed dot from dogecoin.com link

### PR DESCRIPTION
**Pull request by MikAoJk**
Removed dot from dogecoin.com link

### CODE REVIEW

**Comment by rnicoll** [comment]
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

git fetch origin
git rebase -i origin/1.14.4-dev

It will then bring up an editor. If you remove the 2 commits before the one you want. Please check the result then force push it. Thank you!

**Comment by rnicoll** [comment]
Also am I going crazy or is IntelliJ IDEA Java only?

**Comment by MikAoJk** [comment]
> Also am I going crazy or is IntelliJ IDEA Java only?

 IntelliJ IDEA is probably most adapted for java development. 
 But it supports many other languages

**Comment by rnicoll** [comment]
Can you run a rebase to remove the unneeded commit from this, please? As per https://github.com/dogecoin/dogecoin/pull/2244#issuecomment-854912266

**Comment by MikAoJk** [comment]
> Can you run a rebase to remove the unneeded commit from this, please? As per [#2244 (comment)](https://github.com/dogecoin/dogecoin/pull/2244#issuecomment-854912266)

yes, done now

**Comment by chromatic** [comment]
@MikAoJk Looks like this PR still has an extra commit. Would you mind trying to rebase again? If you run into trouble, I'd be happy to cherry-pick the single commit into a different PR (and give you credit for it).

**Comment by MikAoJk** [comment]
> @MikAoJk Looks like this PR still has an extra commit. Would you mind trying to rebase again? If you run into trouble, I'd be happy to cherry-pick the single commit into a different PR (and give you credit for it).

Will create a new PR

**Comment by MikAoJk** [comment]
> @MikAoJk Looks like this PR still has an extra commit. Would you mind trying to rebase again? If you run into trouble, I'd be happy to cherry-pick the single commit into a different PR (and give you credit for it).

plz have a look at: https://github.com/dogecoin/dogecoin/pull/2455

**Pull request closed without merging**
