### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by omahs**
Update French translation

Single commit related to this PR:
https://github.com/dogecoin/dogecoin/pull/3123

### CODE REVIEW

**Comment by omahs** [comment]
@thisiskeanyvy I had issues, hope that's ok to do it this way

**Comment by thisiskeanyvy** [comment]
@patricklodder The contributor could not squash his commits into a single commit.
I don't think this is a good way to PR on a repository but otherwise the changes are valid on my side.

**Comment by thisiskeanyvy** [comment]
This RP follows the one in #3123, it's the same. It's not really a good way to do it, I think it's up to the other contributors to decide. @omahs

**Review by thisiskeanyvy — DISMISSED** [review]
Follow-up to PR #3123

**Comment by patricklodder** [comment]
We'll just close #3123 in favor of this one, no probs.

**Review by patricklodder — APPROVED** [review]
ACK - based on native speaker review by @thisiskeanyvy and I ran `check-translations.py` against it

**Pull request merged**
