### PR TITLE
Update bitcoin_ko_KR.ts

### PR DESCRIPTION
**Pull request by OpinionDoge**
hello i know some korean so wanted to help, but i am not programmer
i do 7 untranslated lines

image
could not find out what function of %amp; is here so removed, what does this mean? it does not seem to make '&' symbol

image
am not sure what function of %1 is but i guess it represents a changing number

image
do not know function of %s here but treated it as word and moved to make more grammar sense, do not know if that is okay

### CODE REVIEW

**Comment by patricklodder** [comment]
Thanks!

I added `help wanted`: it would be good if someone that speaks Korean can proofread these changes.

**Comment by hwanyoungChoi** [comment]
In this statement, "%s" is a special marker commonly used in string formatting. This indicator indicates that it will be replaced by some value later.
I think it was translated well. Both %1 and %s appear to be dynamically replaced with specific values.

**Comment by patricklodder** [comment]
> i am not sure if we need a review for this pull request to be merged 

All pull requests need reviews. I'm simply giving it some time in case there are any further comments, before submitting my review, because I depend on native speakers with this.

**Comment by patricklodder** [comment]
> sorry i meant that i was wondering if i was supposed to ask the other volunteer who helped leave a pull request review instead of just a comment

No need, a comment is valid too. I can simply quote the comment in my review too - it's no big deal either way because you need maintainer ACK.

Honestly, I'd mostly like to see a confirmation from @hwanyoungChoi that with the corrected assumption about `%s`, it's still all good in their opinion. If we don't hear anything I don't mind signing off on it without, but that'd be a concession and I want to do those sparingly.

**Comment by fonso342** [comment]
> hello i know some korean so wanted to help, but i am not programmer i do 7 untranslated lines
> 
> image could not find out what function of %amp; is here so removed, what does this mean? it does not seem to make '&' symbol
> 
> image am not sure what function of %1 is but i guess it represents a changing number
> 
> image do not know function of %s here but treated it as word and moved to make more grammar sense, do not know if that is okay

[](url)

**Comment by serious-gemini** [comment]
> > Re: `&amp;`
> > According to the comments in #275, the `&amp;` means that the following key is a keyboard shortcut. So, in this case, pressing alt+b would maybe check the box next to "Prune block storage to"
> > Not sure if that's true or not, have never tried it.
> 
> thank you i test and it was correct have edited to have b as shortcut
> 
> image

As

> > Re: `&amp;`
> > According to the comments in #275, the `&amp;` means that the following key is a keyboard shortcut. So, in this case, pressing alt+b would maybe check the box next to "Prune block storage to"
> > Not sure if that's true or not, have never tried it.
> 
> thank you i test and it was correct have edited to have b as shortcut
> 
> image

Korean here. As "&amp;" is used for the symbol '&' in HTML, the original text would be "Prune & block storage to"
And I think translation can improve after considering this. 

I'd like to suggest one myself but I believe you have better context here :)

**Comment by serious-gemini** [comment]
> anyone is free to contribute thank you could you also check this line? I want to see if &s placement is Grammarly wise correct image

I think it's perfect 😊

**Comment by patricklodder** [comment]
> Korean here. As "&" is used for the symbol '&' in HTML, the original text would be "Prune & block storage to"
And I think translation can improve after considering this.

@daank-c was right when he said it was for keyboard shortcuts.

> the &amp; means that the following key is a keyboard shortcut. So, in this case, pressing alt+b would maybe check the box next to "Prune block storage to"

I tried to re-confirm this on my Mac but unfortunately this feature (keyboard shortcuts in dialogs) seems to not be enabled on macOS, also not when compiling with the final qt 5.15 release.

**Could someone with an English Dogecoin Qt Windows install check if this still works?** Can be tested with 1.14.6:

- Press alt-b when you have preferences->main open, and the pruning checkbox should flip on/off
settings/main

PROTIP: Perform this on testnet to have great success while not accidentally pruning or unpruning your active node

**Comment by apgrjm** [comment]
> > > Korean here. As "&" is used for the symbol '&' in HTML, the original text would be "Prune & block storage to"
> > > And I think translation can improve after considering this.
> > 
> > 
> > @daank-c was right when he said it was for keyboard shortcuts.
> > > the & means that the following key is a keyboard shortcut. So, in this case, pressing alt+b would maybe check the box next to "Prune block storage to"
> > 
> > 
> > I tried to re-confirm this on my Mac but unfortunately this feature (keyboard shortcuts in dialogs) seems to not be enabled on macOS, also not when compiling with the final qt 5.15 release.
> > **Could someone with an English Dogecoin Qt Windows install check if this still works?** Can be tested with 1.14.6:
> > 
> > * Press alt-b when you have preferences->main open, and the pruning checkbox should flip on/off
> > 
> > settings/main
> > PROTIP: Perform this on testnet to have great success while not accidentally pruning or unpruning your active node
> 
> tested on windows 1.14.6 alt-b works to check or uncheck the prune block storage to X gb option

If that's the case I think your original translation is accurate.

Sorry for the confusion :)

**Comment by serious-gemini** [comment]
> > > Korean here. As "&" is used for the symbol '&' in HTML, the original text would be "Prune & block storage to"
> > > And I think translation can improve after considering this.
> > 
> > 
> > @daank-c was right when he said it was for keyboard shortcuts.
> > > the & means that the following key is a keyboard shortcut. So, in this case, pressing alt+b would maybe check the box next to "Prune block storage to"
> > 
> > 
> > I tried to re-confirm this on my Mac but unfortunately this feature (keyboard shortcuts in dialogs) seems to not be enabled on macOS, also not when compiling with the final qt 5.15 release.
> > **Could someone with an English Dogecoin Qt Windows install check if this still works?** Can be tested with 1.14.6:
> > 
> > * Press alt-b when you have preferences->main open, and the pruning checkbox should flip on/off
> > 
> > settings/main
> > PROTIP: Perform this on testnet to have great success while not accidentally pruning or unpruning your active node
> 
> tested on windows 1.14.6 alt-b works to check or uncheck the prune block storage to X gb option

If that's the case I think your original translation is accurate.

Sorry for the confusion :)

**Review by patricklodder — APPROVED** [review]
ACK - tested on Ubuntu 22.04

Korean content validated by language reviews from: 

- @hwanyoungChoi
- @fonso342
- @serious-gemini 

Thanks everyone!

**Comment by fonso342** [comment]
Alfonso Flanagan

**Pull request merged**
