### PR TITLE
Added simplified Chinese for the main README doc

### PR DESCRIPTION
**Pull request by lynklody**
- Added a Chinese README file @ the home dir
- Added a language selection bar in the main README file

### CODE REVIEW

**Comment by rnicoll** [comment]
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

git fetch origin
git rebase -i origin/1.14.4-dev

It will then bring up an editor. If you remove the 2 commits before the one you want. Please check the result then force push it, and it should just change the document. Thank you!

**Comment by lynklody** [comment]
My apologies, just loaded your message, super slow Internet haha. I'm on it!

**Comment by rnicoll** [comment]
Is #2132 the same BTW? I realised I've managed to comment on both, but if they're the same we should close one.

**Comment by lynklody** [comment]
Sorry it took me a long time to reload the page. Should I close this one (#2130) since you modified the other one?

**Comment by angelcervantesa** [comment]
will get back to this.

**Comment by lynklody** [comment]
> I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:
> 
> git fetch origin
> git rebase -i origin/1.14.4-dev
> 
> It will then bring up an editor. If you remove the 2 commits before the one you want. Please check the result then force push it, and it should just change the document. Thank you!

Can you double check if the rebase was complete? Thanks!

**Comment by rnicoll** [comment]
> Can you double check if the rebase was complete? Thanks!

You've got one commit too many still, try cutting out "issue template updated to prevent spam in repository", then should be good.

**Comment by lynklody** [comment]
Please see merge request #2145 instead

**Pull request closed without merging**
