### PR TITLE
Upgrade OpenSSL package in depends

### PR DESCRIPTION
**Pull request by edtubbs**
Push the OpenSSL package to at least the next minor version (1.0.2) for 1.14.5.

### CODE REVIEW

**Comment by rnicoll** [comment]
Running Gitian build of this now

**Comment by rnicoll** [comment]
@edtubbs Can you do me a favour, and see if Bitcoin ever used this version? OpenSSL historically a risk of introducing hard forks if it changes how signing works, and while I believe the signing is now done by code Bitcoin Core/Dogecoin Core controls more closely, having established precedent that this is a viable version would help.

**Comment by patricklodder** [comment]
1.0.2 is end of life - any reason why you want to integrate this and not 1.1.1?

**Comment by patricklodder** [comment]
> signing

Signing has been done without OpenSSL since 1.10, and 1.14.0 switched to do signature verification integration from src/secp256k1, so there is no OpenSSL needed on the validation path.

OpenSSL is needed for:
1. Random source
2. Payment requests, also making it a dependency for QT

**Comment by edtubbs** [comment]
> 1.0.2 is end of life - any reason why you want to integrate this and not 1.1.1?

It should be possible, I'll work on it today.

**Comment by rnicoll** [comment]
I'm in favour of doing this iteratively, given the nightmares we've had with trying to jump up several versions at once. Counterpoint if Bitcoin Core has worked out the patching that'd definitely help.

**Comment by patricklodder** [comment]
Don't mind doing it iteratively, but then there has to be an overarching plan. Right now, this feels as a competing alternative to #2482 but it doesn't fix the concern voiced on that PR: the hardware CVE exists regardless of using OpenSSL or a direct call.

I raised #2501 to ease dependency updates, because we don't need to worry about the broken trusty mingw toolset anymore and can use gcc 7 then, which reduces the amount of patches we need to write on 3rd party dependencies. Plus, a passing or failing CI suddenly will mean something again then. Trying to make this work on trusty will be a headache.

Where's the plan?

**Comment by edtubbs** [comment]
> Don't mind doing it iteratively, but then there has to be an overarching plan. Right now, this feels as a competing alternative to #2482 but it doesn't fix the concern voiced on that PR: the hardware CVE exists regardless of using OpenSSL or a direct call
>
I think the concern could mitigated if the build doesn't use the RDSEED as a source by default; OpenSSL is a source of NIST validated random whether or not RDSEED is used. 

> Where's the plan?
>
Upgrade OpenSSL to at least the next minor version to address inclusion of rdseed in the OpenSSL NIST complaint source.

**Comment by patricklodder** [comment]
Could you point me to the code in OpenSSL then where a different decision is made for inclusion of RDSEED as a source than what is proposed by #2482? Because what 2482 proposes is:

512 bits of OS seed, 512 bits of OpenSSL seed, and optionally 512 bits of RDSEED. So what does OpenSSL improve then? Also, 1.21 doesn't have OpenSSL - do you propose bringing that back not only for BIP70 but to also re-introduce it as a seed source? Why?

**Comment by edtubbs** [comment]
I think its reasonable to assert OpenSSL random is "good enough" without it, but if we're inclined to include it it seemed prudent to rely on their NIST validation of it's implementation.  What's the downside?

**Comment by patricklodder** [comment]
> What's the downside?

The downside of OpenSSL is that it is hard to understand all the code and spot issues (there have been big issues in the past, through for example buggy ASN.1 implementation, which is touching a lot of higher-level crypto features), tough to integrate with and get deterministic binaries, it's a struggle to disable all the functionality we don't use to reduce what we link in because it does everything possible and then some, and it's hard to upgrade - basically, it's a bit of a  monster - which is why Bitcoin Core got rid of it. So we want to depend on it as little as possible. 

If we can retain BIP70 functionality without OpenSSL in 1.21 that would be the ideal situation. Creating tighter dependencies to it however can bite us back later, which is why I didn't challenge your Intel dependency even though they advised you to use OpenSSL instead, and I am now reviewing that code and trying to find ways to minimize our exposure to that, to not create yet another dependency that puts us in jeopardy. Mind you that crypto used for establishing TLS sessions is transient, but for a cryptocurrency it is not - it's persistent and it's a chain. If in 50 years I have a utxo I made with Dogecoin 1.5 that was valid back then, it still needs to be valid at that time. Until I spend it. Bugs in crypto libraries are terrifying for us and on this software, we cannot screw around, because it is the foundation that guards the storage of value for the entire asset.

> It's optionally included with configuration parameters --with-rand-seed rdcpu.

So by not setting that in the default build, it's never used on our binary releases. Which was exactly my question here: https://github.com/dogecoin/dogecoin/pull/2482#discussion_r703027787 and I was taking your recommendation under advisement (but still, I do not have enough arguments pro or con to make a decision on what I would feel best about in terms of risk management.) Since that means there will be no RDSEED in OpenSSL, what does this add? I haven't found an issue with OpenSSL's 1.0.1 random source - am I missing something?

It's okay if we don't have all the answers yet, it just means we have to figure it out.

**Comment by ReverseControl** [comment]
@edtubbs For reference, I would like to note that RDSEED by itself is also NIST compliant as a Non-deterministic random bit generator:  SP 800-90B & C.  ( See https://software.intel.com/content/www/us/en/develop/blogs/the-difference-between-rdrand-and-rdseed.html, also see https://www.ic.unicamp.br/cans2013/slides/cans2013_keynote1_georgecox.pdf).

**Comment by rnicoll** [comment]
Well. FWIW 1.0.2 seems to reindex fine. I acknowledge everything has moved past this now.

**Comment by patricklodder** [comment]
> FWIW 1.0.2 seems to reindex fine

Because OpenSSL is not used for validation, [as I mentioned here, in this PR's thread](https://github.com/dogecoin/dogecoin/pull/2555#issuecomment-914151497), reindexing is not touching that at all, so that is as expected even if OpenSSL would be returning 0x00 on all ECDSA signatures, as we don't use that functionality anymore since years. If you wanted to manually test this PR, you'd want to check the seed source when creating wallets (write some tests that iteratively create a couple million wallet seeds?) and testing payment requests handling: iirc Bitpay uses BIP70 rather than BIP21, so that would allow you to mainnet test this.

As an intermediate upgrade to 1.1.1 this can be at least a step in the right direction (given that we actually test it, not test something else) but it does not provide an alternative solution to #2482. This doesn't mean we don't want this, especially if this enables us to do easier upgrades to an actually maintained version. Please explain how that is the case. 

This is why I asked for an overarching plan because this PR alone isn't good enough to keep 1.14 alive long-term. I guess there is none, so I'll write one.

**Comment by edtubbs** [comment]
@patricklodder using an established FIPS crypto engine like OpenSSL with cryptographic algorithm primitives that require independent validation buys down a tremendous amount of inherent risk in crypto applications in general.  The risk of fork is greater in the case you're not using an independently validated implementation.  Granted, the trappings of the engine aren't insignificant; but the value in their implementation is clearly evident.

**Comment by edtubbs** [comment]
> @edtubbs For reference, I would like to note that RDSEED by itself is also NIST compliant as a Non-deterministic random bit generator: SP 800-90B & C. ( See https://software.intel.com/content/www/us/en/develop/blogs/the-difference-between-rdrand-and-rdseed.html, also see https://www.ic.unicamp.br/cans2013/slides/cans2013_keynote1_georgecox.pdf).

Unfortunately, as we've all seen, not even Intel recommends using it without mitigation. The advantage OpenSSL has is that it draws entropy for multiple sources itself, as opposed to relying on a single instruction  as well as it requires no mitigation if a vulnerable source isn't used.

**Comment by ReverseControl** [comment]
> > @edtubbs For reference, I would like to note that RDSEED by itself is also NIST compliant as a Non-deterministic random bit generator: SP 800-90B & C. ( See https://software.intel.com/content/www/us/en/develop/blogs/the-difference-between-rdrand-and-rdseed.html, also see https://www.ic.unicamp.br/cans2013/slides/cans2013_keynote1_georgecox.pdf).
> 
> Unfortunately, as we've all seen, not even Intel recommends using it without mitigation. ...

Not true, in fact, see https://software.intel.com/content/www/us/en/develop/articles/software-security-guidance/best-practices/srbds-mitigation-impact-intel-secure-key.html:

`The first technique is to turn off the SRBDS mitigation. This can be done through setting the RNGDS_MITG_DIS4 bit (bit 0) of IA32_MCU_OPT_CTRL MSR (address 123H). Setting IA32_MCU_OPT_CTRL[0] (RNGDS_MITG_DIS) to 1 for a logical processor disables the mitigation for RDRAND and RDSEED executed outside of an Intel® Software Guard Extensions (Intel® SGX) enclave on that logical processor.`

There are three cases where Intel suggest disabling the SRDBDS mitigation.

**Comment by patricklodder** [comment]
Alright so do you recommend adding the FIPS module? Because honestly, that is currently not built in, also not in this PR, it is also not maintained anymore (does not port to 1.1.1), and the certification is dependent on architecture and OS, where, since it is outdated, I do not expect many people to run the particular systems certified (i.e. Ubuntu 12.04, [link](https://www.openssl.org/docs/fips/SecurityPolicy-2.0.16.pdf)) as those would bring other security issues and I would not want to recommend anyone to actually run 12.04 in production.

Besides, as the attack vectors other than the random seed used for the wallet are far greater than the exposure towards bad seed data, can we agree that: 
- If you're a custodial service, you should not use the Dogecoin Core's wallet to begin with, but use an HSM (preferably more than one and multisig coins in custody) for all key operations.
- If you're a shibe and you worry about the security of your personal keys, you're probably better off using one of the hardware wallets than relying on Dogecoin Core's wallet functionality

... where in both cases Dogecoin Core can perfectly be used as a block validator.

In any case, to bring this PR forward and do an OpenSSL step-in-the-right-direction upgrade, could you at the very least:

- undo the 1.1.1 changes right now and revert this PR to 1.0.2
- fixate the suffix to `u` as that is currently the last release for 1.0.2

Then, this can be tested independently. Since #2482 retains OpenSSL as a source of entropy, I expect no issues on that PR?

Finally: can we count on you to bring OpenSSL back to 1.21 as a source of entropy?

**Comment by edtubbs** [comment]
>
> There are three cases where Intel suggest disabling the SRDBDS mitigation.

I don't believe the first two "opt out" conditions apply to this application given the target environment, and the third is technically another mitigation against the vulnerable instructions.

**Comment by edtubbs** [comment]
> Alright so do you recommend adding the FIPS module? Because honestly, that is currently not built in, also not in this PR, it is also not maintained anymore (does not port to 1.1.1), and the certification is dependent on architecture and OS, where, since it is outdated, I do not expect many people to run the particular systems certified (i.e. Ubuntu 12.04, [link](https://www.openssl.org/docs/fips/SecurityPolicy-2.0.16.pdf)) as those would bring other security issues and I would not want to recommend anyone to actually run 12.04 in production.
> 
> Besides, as the attack vectors other than the random seed used for the wallet are far greater than the exposure towards bad seed data, can we agree that:
> 
> * If you're a custodial service, you should not use the Dogecoin Core's wallet to begin with, but use an HSM (preferably more than one and multisig coins in custody) for all key operations.
> * If you're a shibe and you worry about the security of your personal keys, you're probably better off using one of the hardware wallets than relying on Dogecoin Core's wallet functionality
> 
> ... where in both cases Dogecoin Core can perfectly be used as a block validator.
> 
> In any case, to bring this PR forward and do an OpenSSL step-in-the-right-direction upgrade, could you at the very least:
> 
> * undo the 1.1.1 changes right now and revert this PR to 1.0.2
> * fixate the suffix to `u` as that is currently the last release for 1.0.2
> 
> Then, this can be tested independently. Since #2482 retains OpenSSL as a source of entropy, I expect no issues on that PR?
> 
> Finally: can we count on you to bring OpenSSL back to 1.21 as a source of entropy?

I generally agree and also expect the reference implementation to provide basic assurance. I had considered adding the FIPS object module, but believe it should be installed in OpenSSL 2.0 or higher at this point.  1.0.2 pedigree does reflect a mature product and process nevertheless, and it should be possible to build 2.0+ on ci targets with the next incremental update.

**Comment by patricklodder** [comment]
@edtubbs I opened edtubbs#1 to keep `libcrypto.a` small

**Review by patricklodder — CHANGES_REQUESTED** [review]
I did some further build tests and even though rc4 implementation changed a bit, we can still set `no-rc4`, so I'd recommend restoring that line.

We can probably disable further features, but we can do that in a separate PR because it takes a lot of time to test the entire build end-to-end iteratively.

If you could bring back `no-rc4` and squash your work into a single commit, rebased on top of the current `1.14.5-dev` branch, we can run a gitian compare and if we get matching hashes, we can then merge this in.

**Comment by edtubbs** [comment]
> I did some further build tests and even though rc4 implementation changed a bit, we can still set `no-rc4`, so I'd recommend restoring that line.
> 
> We can probably disable further features, but we can do that in a separate PR because it takes a lot of time to test the entire build end-to-end iteratively.
> 
> If you could bring back `no-rc4` and squash your work into a single commit, rebased on top of the current `1.14.5-dev` branch, we can run a gitian compare and if we get matching hashes, we can then merge this in.

@patricklodder, ok that sounds good; after those changes pass checks I’ll squash and force push.

**Pull request closed without merging**
