### PR TITLE
Consensus fixes

### PR DESCRIPTION
**Pull request by rnicoll**
This patch set introduces the remaining consensus changes for Dogecoin, and enables syncing. I haven't fully synced the blockchains yet, but wanted to open this for review now.

This patch includes the AuxPoW commits as they're a pre-requisite, however I intend to rebase this PR once the AuxPoW changes are merged independently.

### CODE REVIEW

**Comment by rnicoll** [comment]
Synced to 155,000 height on main chain now

**Comment by rnicoll** [comment]
Full sync completed on main chain. While there's still plenty of rough edges to smooth off, I think it's worth merging this as-is rather than layering more stuff onto it.

**Comment by patricklodder** [comment]
@rnicoll for some reason my mainnet dir is sitting in `~/.dogecoin/testnet3`, do you have the same issue?

**Comment by patricklodder** [comment]
Mainnet syncs fine, but testnet only syncs until block 1231 currently. I remember @rnicoll had an issue at this same block when you were porting toshi last year, any idea what caused it? 

All I get in log for block 1232 is: `2015-07-18 14:12:11 ERROR: ContextualCheckBlockHeader: incorrect proof of work`

**Comment by rnicoll** [comment]
Looking at testnet now

**Comment by rnicoll** [comment]
Basic problem is that the difficulty reset rules for testnet are a complete mess. I've managed to recreate them by cutting & pasting, but they could do with cleaning up (in code) and frankly I'd rather like to reset the whole mess.

The attached commits sync testnet fully for me, I'm re-confirming main net, will be done by morning.

**Comment by rnicoll** [comment]
Gave in and cleaned up a bunch of legacy stuff from AuxPoW merging, to make it fit more cleanly into the height-based consensus architecture. Synced against testnet, rechecking main net now, suggest you do the same (sorry). Have merged in #1202 as seems worthwhile. Once you're happy, let me know, I'll squash the height commits together.

**Comment by patricklodder** [comment]
tested & ack. thanks for this, merging.

**Pull request merged**
