### PR TITLE
Simple edit README.md and README_zh_CN.md

### PR DESCRIPTION
**Pull request by motahharm**
In README.md I put the icon above the subject
And in README_zh_CN.md I put the subject and the icon in the middle

### CODE REVIEW

**Review by patricklodder — APPROVED** [review]
I'm okay with this change - it is more aesthetically pleasing to me.

**Comment by patricklodder** [comment]
Would like to know more opinions. If we decide to go with this, then let's just keep this as the standard.

**Review by patricklodder — APPROVED** [review]

**Comment by motahharm** [comment]
Hey @patricklodder 
Thank you
that is ok

**Comment by chromatic** [comment]
:+1: from me too.

**Pull request merged**
