### PR TITLE
Enable CodeQL scanning

### PR DESCRIPTION
**Pull request by hashtagcyber**
Github provides a free static code analysis tool (CodeQL) for public repositories. It's[ free](https://github.blog/2020-09-30-code-scanning-is-now-available). This workflow file configures the scanner to build the latest version on PR/Push to master with the --disable-wallet and --without-gui flags.

Results of the scan will show up in the Security tab.

### CODE REVIEW

**Comment by gabaod** [comment]
a PR shouldnt have multiple commits to a single file, id suggest redo so you have just the 1 commit.

**Comment by lukaesch** [comment]
@hashtagcyber Isn't it possible to squash the commits?

**Comment by patricklodder** [comment]
closing & reopening for CI.

**Review by michilumin — APPROVED** [review]
don't see a reason why we shouldn't be running this, no harm only benefit.

**Comment by patricklodder** [comment]
@hashtagcyber It would be great if you could squash these commits using `git rebase -i 1.14.4-dev`, mark the bottom 3 commits for squashing, and force push once using `git push -f origin master`

**Comment by patricklodder** [comment]
Squash merging this instead of waiting on the author to squash.

**Pull request merged**
