### PR TITLE
Skip auxpow checks when reading blocks from disk

### PR DESCRIPTION
**Pull request by barrystyle**
As per discussion in https://github.com/dogecoin/dogecoin/pull/1676

### CODE REVIEW

**Comment by shibe2** [comment]
As I said in the discussion of my PR, I don't like it being opt-in. We need as much nodes serving blockchain data as possible. If most nodes will have this optimization disabled, total bandwidth will not be enough to feed all new nodes, and we will have the same problem again.

**Comment by barrystyle** [comment]
The problem is, the small number of nodes with all blocks online right now - are getting hammered by all the other nodes attempting to perform a full sync. Once the general node count increases, it wont be a problem and we can leave the check running.

**Comment by shibe2** [comment]
It's not just right now. The same situation was with every major price movement, and it will likely happen again. I'd like it if we try solving it for good.

If you look at how BitTorrent works, you'll understand why it is important. As soon as one peer receives and verifies a piece of data, it serves it to other peers. That way the network achieves good download speeds using home internet connections and maybe cheap seed boxes. If we don't use new peers as new sources, we'll not get decent speed for everyone.

**Comment by shibe2** [comment]
VerifyDB and LoadExternalBlockFile call code that can be disabled here. Should checking AuxPoW be forced in these cases?

**Comment by patricklodder** [comment]
Preliminary results I'm seeing running this on mainnet are that this patch adds another ~10% throughput on low-connection nodes (eg maxconnections=50) and up to 15% when I keep max connections at default 125, compared to #1676

I will continue to run both patches in parallel.

**Comment by patricklodder** [comment]
Update: I'm currently seeing x3 throughput on a full 125 connection node with this patch now that it went through a load of header sync and is actually full-time sending out blocks.

**Comment by patricklodder** [comment]
> As I said in the discussion of my PR, I don't like it being opt-in.

Looking at how everyone only ever runs the default, I would also have opt-out for this rather than opt-in. Operators can switch it off for derisking potential ban score when bad things happen on disk.

> VerifyDB and LoadExternalBlockFile call code that can be disabled here. Should checking AuxPoW be forced in these cases?

Yes, I think it should. Where I'm at, the solution lies in he middle between both candidate PRs.

**Comment by shibe2** [comment]
> Update: I'm currently seeing x3 throughput on a full 125 connection node with this patch now that it went through a load of header sync and is actually full-time sending out blocks.

Is it 3x compared to my version? I wonder, where the performance difference comes from. I put a counter in CheckAuxPowProofOfWork, and in my version it's called like 2 times per minute. Maybe we need a better benchmark, because network speed depends on kind of requests.

**Comment by patricklodder** [comment]
> Is it 3x compared to my version?

On that particular node, yes, but only when it reached over 100 incoming full clients and went into full-scale block sync after most of the headers were synchronized on those nodes. The 10% increase I saw during the time when it was still synchronizing headers a lot can be explained by restarting the node and it actually being of similar performance. Over a set of 10+10 nodes the average increase I see is 2x. But I haven't used a deterministic build for either because while we are doing this, I really need all the nodes out there to sync faster too.

> Maybe we need a better benchmark, because network speed depends on kind of requests.

I will recompile both using the same Dockerfile, and restart all the nodes. My sample set of 20 nodes is still too small and too uniform though.

**Comment by patricklodder** [comment]
We've merged #1676 in favor of this PR as the final performance gain of eliminating all the checks across the board is negligible for the goal we set to achieve (less compute when serving blocks to peers) whilst the risk of running into more non-recoverable scenarios outside of networking with this PR is greater due to there being no AuxPoW checks against what stored on the local disk.

Thank you for the research, discussion, support and ideas. It's very much appreciated!

**Pull request closed without merging**
