### PR TITLE
Upgrade OpenSSL package in depends

### PR DESCRIPTION
**Pull request by edtubbs**

### CODE REVIEW

**Comment by edtubbs** [comment]
@patricklodder, this PR replaces #2555

**Comment by edtubbs** [comment]
Thanks @patricklodder and @rnicoll !
Gitian check.. https://cirrus-ci.com/build/5673511386611712

**Comment by patricklodder** [comment]
There's an issue with the gitian build in linux under https://cirrus-ci.com/task/4743721297117184?logs=build#L6121 when checking for portability issues.

I have been able to reproduce this. Am investigating.

**Comment by patricklodder** [comment]
Switched gitian check label to do not merge yet label. If gitian check passes on #2581 then we can merge this.

**Comment by patricklodder** [comment]
I missed that there was also an issue with the macOS build: https://cirrus-ci.com/task/5306671250538496?logs=build#L4534 - I think this should be simply a case of adding some build environment configuration to `Configure`.

If this is an easy fix, we can do this with trusty still and not make the inter-PR dependencies crazy. If not, we need the bionic upgrade from #2501 first (according to the CI, this problem does not exist on bionic, so that gives hope)

**Comment by patricklodder** [comment]
If I get determinism back between docker and lxc gitian builds using https://github.com/patricklodder/dogecoin/commit/21439f8a87d4267a0b2174146df1953877aca3bb, I will add that commit to #2581 and then that can take care of merging this PR, solving the macOS issue.

**Comment by edtubbs** [comment]
> If I get determinism back between docker and lxc gitian builds using [patricklodder@21439f8](https://github.com/patricklodder/dogecoin/commit/21439f8a87d4267a0b2174146df1953877aca3bb), I will add that commit to #2581 and then that can take care of merging this PR, solving the macOS issue.

Ok, that looks good. Thanks @patricklodder!

**Comment by patricklodder** [comment]
I've validated that patch to work, @edtubbs are you okay to close this PR?

**Comment by edtubbs** [comment]
> I've validated that patch to work, @edtubbs are you okay to close this PR?

@patricklodder excellent, good to close.

**Pull request closed without merging**
