### PR TITLE
[build] Add Dockerfile to build on an Ubuntu image

### PR DESCRIPTION
**Pull request by p-j01**
# Description 

Add Dockerfile to build on an Ubuntu image and documentation on how to use Dogecoin from the container.

### CODE REVIEW

**Comment by AbcSxyZ** [comment]
I do not run a node myself and honestly just tried a couple of commands, but there is probably some configuration to do.

Some configuration with the environnement variables, how to give some files if needed, how to backup. If I'm not wrong it need also credentials ?

It have to be generic.

**Comment by rnicoll** [comment]
Closing and re-opening to trigger Travis.

**Comment by rnicoll** [comment]
> Some configuration with the environment variables, how to give some files if needed, how to back up. If I'm not wrong it need also credentials ?
> @rnicoll @patricklodder What would be the default settings to consider to run a node ?

I haven't dug into this in depth yet, but my intuition is it should have the entire data directory mounted into the Docker container (as in persisted outside Docker), so the configuration is provided/editable from the host. Let me know if that seems crazy?

**Comment by mmicael1** [comment]
@p-j01 Globally seems okay globally but the COPY will take a long time because of qa-assets.
IMO, We should do the compile on an ENTRYPOINT

**Comment by AbcSxyZ** [comment]
Agree that using mounting data directory is a (quick) way to configure the node, but for me a docker way would be to use environment variables.

Actually, I think it really depends on the end user of `dogecoind`, who are they, and what are their needs ? 
Is it a small user with his GUI and his buck to send to his friends (I guess main dogecoin user use other solution like exchanges ?), a miner, a mining pool, anyone/any organization who want to validate transaction by his own (custodial services), a developer who want to code, etc.

Depending on that, the configuration might really change, from a small change in RPC credentials, to specific settings designed for a complex network, with or without backup/wallets (aka volumes). **The docker install can probably bring more flexibility.**

For example, in the current `Dockerfile`,  `dogecoin-qt` is created by default, some user won't need GUI by default (is it cross-platform, windows compatible?).

**Comment by p-j01** [comment]
> > Some configuration with the environment variables, how to give some files if needed, how to back up. If I'm not wrong it need also credentials ?
> > @rnicoll @patricklodder What would be the default settings to consider to run a node ?
> 
> I haven't dug into this in depth yet, but my intuition is it should have the entire data directory mounted into the Docker container (as in persisted outside Docker), so the configuration is provided/editable from the host. Let me know if that seems crazy?

**Comment by p-j01** [comment]
> I haven't dug into this in depth yet, but my intuition is it should have the entire data directory mounted into the Docker container (as in persisted outside Docker), so the configuration is provided/editable from the host. Let me know if that seems crazy?

@rnicoll Which directory are you referencing?

>@p-j01 Globally seems okay globally but the COPY will take a long time because of qa-assets.
IMO, We should do the compile on an ENTRYPOINT

@mmicael1 Where is located `qa-assets` ?

**Comment by AbcSxyZ** [comment]
I made a Dockerfile from scratch, see https://github.com/dogecoin/dogecoin/pull/2337

**Comment by p-j01** [comment]
Why

**Comment by AbcSxyZ** [comment]
It was simple base, the design of the other version is different and nothing was reused. Using release instead of sources, adding user, manage volume permission, using variable for image build, entrypoints... The `docker-entrypoint.py script`.  
Wasn't able to reuse, starting from scratch made sense.

**Comment by evaluationcopy** [comment]
I suggest updating the documentation to urge users using dogecoind to create a volume for their data directory.

Each time a user casually performs a docker run, their data directory will be lost.  This will initiate a new download of the blockchain data which can take days or weeks, and unnecessarily pulls resources from the nodes on the network.  To a user of the docker image, the internal directory structure of the docker image is not known - they won't know where to point a volume.

My method of urging users to do so was to only give an example of running the image with a volume.  #2578

**Comment by patricklodder** [comment]
I have created https://github.com/dogecoin/docker and seeded it with #2337.

**Pull request closed without merging**
