### PR TITLE
Utils and libraries: Update ZMQ to 4.3.4

### PR DESCRIPTION
**Pull request by sabotagebeats**
work in progress

### CODE REVIEW

**Comment by sabotagebeats** [comment]
😅 close button on mobile app closes the pr and not the app, woops

**Comment by rnicoll** [comment]
fixes https://github.com/dogecoin/dogecoin/issues/2149

**Comment by rnicoll** [comment]
Did a full reindex to verify the result is stable, and seems fine. If @Polve can verify this fixes their issue, I think it's good to merge.

**Comment by Polve** [comment]
4.1.8 is a very old and unmantained version.
I need a recent one (4.3.4 is the latest) to fix the issue.

**Comment by patricklodder** [comment]
> I need a recent one (4.3.4 is the latest) to fix the issue.

According to CVE databases I browsed, [like this one](https://www.cvedetails.com/vulnerability-list/vendor_id-14186/Zeromq.html), there are some serious issues pre 4.3.3. So I'm a fan of trying for 4.3.4 too!

@sabotagebeats could you try for that?

**Comment by sabotagebeats** [comment]
Will do!

**Comment by sabotagebeats** [comment]
It seems that the build failed. It's possible this package has changed some arguments or possibly no longer requires patches. 

Researching. 👀

**Comment by sabotagebeats** [comment]
this looks like it's an issue with the patch. 

```
Preprocessing zeromq...
patching file configure.ac
patch unexpectedly ends in middle of line
Hunk #1 FAILED at 265.
1 out of 1 hunk FAILED -- saving rejects to file configure.ac.rej
make: *** [/home/travis/build/dogecoin/dogecoin/depends/work/build/arm-linux-gnueabihf/zeromq/4.3.4-9dfef218a5e/.stamp_preprocessed] Error 1
make: Leaving directory `/home/travis/build/dogecoin/dogecoin/depends'
The command "make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS" failed and exited with 2 during .
```


I am able to build fine on my local machine with `./configure --disable-wallet`

How can I ensure I'm testing the zeromq library?

**Comment by sabotagebeats** [comment]
looks like patches are out of date with new library. Will try removing them and then pushing again. 

https://github.com/zeromq/libzmq/blob/3070a4b2461ec64129062907d915ed665d2ac126/configure.ac#L346

**Comment by sabotagebeats** [comment]
I'm stumped on this one 

```
make[1]: *** No rule to make target `libzmq.la'.  Stop.
make[1]: Leaving directory `/home/travis/build/dogecoin/dogecoin/depends/work/build/arm-linux-gnueabihf/zeromq/4.3.4-7f1c61fcd50'
make: *** [/home/travis/build/dogecoin/dogecoin/depends/work/build/arm-linux-gnueabihf/zeromq/4.3.4-7f1c61fcd50/./.stamp_built] Error 2
make: Leaving directory `/home/travis/build/dogecoin/dogecoin/depends'
The command "make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS" failed and exited with 2 during .
Your build has been stopped.
```

**Comment by sabotagebeats** [comment]
https://github.com/zeromq/libzmq/issues/1516

**Comment by sabotagebeats** [comment]
I am able to see the `libzmq.la file` in `4.1.8` after `make`

I now need to confirm the same file exists in `4.3.4` after `make`

**Comment by sabotagebeats** [comment]
`./src/libzmq.la` file does exist after `make` in `4.3.4`

**Comment by sabotagebeats** [comment]
it looks like some tests are passing and some are failing. I will do more research into why this is.

**Comment by sabotagebeats** [comment]
`error: ‘SOCKADDR_INET’ does not name a type`

https://github.com/zeromq/libzmq/issues/4047

**Comment by sabotagebeats** [comment]
If I'm understanding correctly it looks like all the Linux builds are passing but some of the windows builds and the osx build are failing.

**Comment by DeerSpotter** [comment]
> If I'm understanding correctly it looks like all the Linux builds are passing but some of the windows builds and the osx build are failing.

show us what you are seeing when it is failing. Ape strong together.

**Comment by DeerSpotter** [comment]
sdk URL no longer Valid? 

image
image

**Comment by rnicoll** [comment]
Restarting CI after the move to GitHub Actions

**Review by dgs2019 — APPROVED** [review]

**Comment by sabotagebeats** [comment]
@rnicoll it looks like the builds are passing now.

**Review by patricklodder — CHANGES_REQUESTED** [review]
1. Could you please remove `depends/patches/zeromq`? We don't seem to need these patches anymore.
2. Please `git rebase -i 1.14.4-dev` and squash all commits into one

Other than that, this is good to go.

**Comment by sabotagebeats** [comment]
Is the squash done with the merge? When I'm trying to squash it says (nothing to squash)Already up to date.`

**Review by sabotagebeats — COMMENTED** [review]
this looks good to me. Awaiting feedback from core developers.

**Comment by patricklodder** [comment]
> Is the squash done with the merge? When I'm trying to squash it says `(nothing to squash)Already up to date.`

You may need to add this repository as "upstream" if you haven't yet, so you get something like:

```
git checkout fix/issues/2149
git remote add upstream https://github.com/dogecoin/dogecoin.git
git fetch upstream
git rebase -i upstream/1.14.4-dev
git push -f origin fix/issues/2149
```

during interactive rebase, change `pick` into `squash` for your commits except the first one and delete all commits that aren't part of this PR, if any.

Finally you'll get to write a new commit message for the squashed commit - this is where you get to do all the fun :-)

**Comment by sabotagebeats** [comment]
@patricklodder let me know if this looks like what you requested, or if I need to make any more changes

**Comment by patricklodder** [comment]
CI passes, needs gitian check.

I'm still trying to get macOS to x-compile on Ubuntu 20.04, but since @rnicoll is already doing gitian checks on other PRs, we could make a batch and do a couple more of these. Open to suggestions.

**Review by patricklodder — DISMISSED** [review]

**Comment by sabotagebeats** [comment]
> I'm still trying to get macOS to x-compile on Ubuntu 20.04
I'm developing (compiling and building) on Ubuntu 20.04 LTS on windows 10 with WSL2 if that helps
I am using BerkeleyDB 5.3 and `./configure --with-incompatible-bdb`
I have synced to block 2289067 so far.

**Comment by sabotagebeats** [comment]
@rnicoll I have never done a gitian build before but I will give it a shot and see if I have similar results as you.

**Comment by sabotagebeats** [comment]
@rnicoll this might be helpful for you since I am guessing you're building on OSX and seeing this error? 

https://sourceforge.net/p/fink/mailman/message/37184789/

**Comment by sabotagebeats** [comment]
@rnicoll this looks like a bug in zmq but I can't test it since I don't have OSX

**Comment by Star6654** [comment]
Sent from the all new AOL app for iOS


On Sunday, July 11, 2021, 12:12 AM, Doggo ***@***.***> wrote:




@rnicoll this looks like a bug in zmq but I can't test it since I don't have OSX

**Comment by patricklodder** [comment]
> @rnicoll this looks like a bug in zmq but I can't test it since I don't have OSX

It's because clang implements stricter checks on things than gcc does out of the box. I'd recommend making a patch with [the fix described on the libzmq issue](https://github.com/zeromq/libzmq/issues/4231#issuecomment-875068706) and applying it on depends to unblock this.

**Comment by sabotagebeats** [comment]
@rnicoll @patricklodder I have merged both of your pulls, if you can just take a look at the files changed and make sure that looks good and it passes all checks after approval then I think that we can probably begin the next round of testing gitian builds

**Comment by sabotagebeats** [comment]
reverted the 2n'd PR since it was failing checks: https://github.com/sabotagebeats/dogecoin/commits/fix/issues/2149

**Comment by patricklodder** [comment]
> reverted the 2n'd PR since it was failing checks: https://github.com/sabotagebeats/dogecoin/commits/fix/issues/2149

The 1st PR solves the clang error issue differently than the 2nd, so you were merging duplicate fixes. What I don't like about it is that it only works because we're using clang for osx compilation, but it still won't work if we use clang for non-osx compilation. The recommendation you got on the zmq repo was much cleaner (as it doesn't introduce yet another platform check)

**Comment by sabotagebeats** [comment]
@patricklodder I can revert the 1st PR and you can re-request with your branch?

**Comment by patricklodder** [comment]
> @patricklodder I can revert the 1st PR and you can re-request with your branch?

I think you need the other patches of the 1st PR though... they come from bitcoin/bitcoin

I'll rebase on top of your current branch and swap those parts out.

**Comment by sabotagebeats** [comment]
ah now i've broken it? 😅

**Comment by patricklodder** [comment]
> ah now i've broken it? 😅

No sweat - I got you. Give me a bit.

**Comment by sabotagebeats** [comment]
@patricklodder the checks were passing so I merged your commits and it should be ready for your CI checks now :)

**Comment by patricklodder** [comment]
Windows build for gitian was failing under trusty because of mingw 3.1.0 headers, so I opened https://github.com/sabotagebeats/dogecoin/pull/4 to fix that. That patch can be removed once I have gitian building ready under focal but as I'm not there yet, this will enable merge now.

**Comment by sabotagebeats** [comment]
https://github.com/sabotagebeats/dogecoin/pull/4 has passed checks and been merged. now awaiting workflow checks and gitian checks for dogecoin core :)

**Comment by patricklodder** [comment]
@sabotagebeats could you please rebase once against 1.14.4-dev and force push to get rid of the merges? Then I think we're good to give this a go with gitian.

**Comment by patricklodder** [comment]
tagged 36bde0e as patricklodder/dogecoin v1.14.4-zmq - building gitian now.

**Comment by patricklodder** [comment]
```
129e55117020d7b6a1e27b482997fede893febae2f017d70f0a1ab007cbb2483  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
009856b128160b79b34d10e176fe8e60d61f999868dfd45aa980dad3cff45e55  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
b9ccdddfa74d7d7b0ff8dfa7bc6a6b3c5fc321fd13bb121b4a0ffbb3e95fe961  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
06fdf0807197010513f3ee0d6b98fc3da879dd69ed026a3e81e76a27a3f731a9  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
79a926c8b82ac747ac9a74e200ad072220b1414c1fc10ee600cfe4816e8bcd90  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
6eca4a6ac490ff7f7029bb04839f53a45ff697c376eec50c31e9c5984bbed6ec  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
c97a1eaebdf0c791949bac10595c8dabb99eb054bf3d58791e5266ff718a8367  dogecoin-1.14.4-osx-unsigned.dmg
fc9dac15503ac33d50ba63e96fb0221199456e167da7080bb8bc0d2a00386e37  dogecoin-1.14.4-osx-unsigned.tar.gz
478bd0dcde9c36f7e0d760644b16672b9074998f0973c8b525229ad93eb081e6  dogecoin-1.14.4-osx64.tar.gz
123736720e26ea53ebe26919b2abfafd1a757826a7f8421d4da7c343ed1cfc0d  dogecoin-1.14.4-win32-debug.zip
cc5c77ea1f52b5dc9241f4242e38752abe26079ab1638b5dd991c6e4c1b18553  dogecoin-1.14.4-win32.zip
80e9babb5b89b27a71e34c71161745db369ea8c6d7d01f58759caeee5b21f957  dogecoin-1.14.4-win64-debug.zip
d6f4f73b31eb229617a70a6fb3212d46ce27fec44f5e6d7d5221ebb64480a908  dogecoin-1.14.4-win64.zip
843824fd359108bc65bc2c768585eb0b58b7d533b98cd2df1022e229e076dddb  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
0c483145a9fff370c0b099291fec7bb70ea78bb8599737e35ffddd66bbecc5bd  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Comment by Polve** [comment]
If there is a link where to download the updated builds I would gladly test them to see if I see any problems

**Comment by patricklodder** [comment]
@Polve you should be able to get an unsigned binary from the last CI build on this PR here: https://github.com/dogecoin/dogecoin/actions/runs/1043282233

**Comment by Polve** [comment]
> @Polve you should be able to get an unsigned binary from the last CI build on this PR here: https://github.com/dogecoin/dogecoin/actions/runs/1043282233

Thanks for the link, the problem is that there is missing the only one I need: dogecoin-1.14.4-x86_64-linux-gnu.tar.gz

There is dogecoin-65b1e767bf4b7a66a9961d6040b8f66023abb1f6-x86_64-linux-nowallet  but I need the wallet for integration tests

**Comment by patricklodder** [comment]
[dogecoin-1.14.4-x86_64-linux-gnu.tar.gz](https://github.com/dogecoin/dogecoin/files/6841740/dogecoin-1.14.4-x86_64-linux-gnu.tar.gz) uploaded from my gitian build

**Comment by Polve** [comment]
Very preliminary tests are fine for me

**Comment by sabotagebeats** [comment]
@patricklodder is there anything left for me still to complete for now or is it just waiting for the rest of the checks to be manually performed?

**Comment by patricklodder** [comment]
>  is there anything left for me still to complete for now or is it just waiting for the rest of the checks to be manually performed?

Unless there's an issue w/ the build, I think you're done. Thanks! 

If we find any additional issues from a functional p.o.v. it'll unlikely be solved by downgrading the dependency, so we'd add a patch or change integration code. I now just need one matching gitian check - can be from anyone really - to make sure the build stays deterministic, and then I'll ACK & merge.

**Comment by michilumin** [comment]
For verification, my gitian hashes on it

```
129e55117020d7b6a1e27b482997fede893febae2f017d70f0a1ab007cbb2483  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
009856b128160b79b34d10e176fe8e60d61f999868dfd45aa980dad3cff45e55  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
b9ccdddfa74d7d7b0ff8dfa7bc6a6b3c5fc321fd13bb121b4a0ffbb3e95fe961  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
06fdf0807197010513f3ee0d6b98fc3da879dd69ed026a3e81e76a27a3f731a9  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
79a926c8b82ac747ac9a74e200ad072220b1414c1fc10ee600cfe4816e8bcd90  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
6eca4a6ac490ff7f7029bb04839f53a45ff697c376eec50c31e9c5984bbed6ec  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
478bd0dcde9c36f7e0d760644b16672b9074998f0973c8b525229ad93eb081e6  dogecoin-1.14.4-osx64.tar.gz
c97a1eaebdf0c791949bac10595c8dabb99eb054bf3d58791e5266ff718a8367  dogecoin-1.14.4-osx-unsigned.dmg
fc9dac15503ac33d50ba63e96fb0221199456e167da7080bb8bc0d2a00386e37  dogecoin-1.14.4-osx-unsigned.tar.gz
7ef337488c149fffb6754e78fb3c39ff26283db0d8a1bfc62b89ad9b36602db4  dogecoin-1.14.4.tar.gz
123736720e26ea53ebe26919b2abfafd1a757826a7f8421d4da7c343ed1cfc0d  dogecoin-1.14.4-win32-debug.zip
cc5c77ea1f52b5dc9241f4242e38752abe26079ab1638b5dd991c6e4c1b18553  dogecoin-1.14.4-win32.zip
80e9babb5b89b27a71e34c71161745db369ea8c6d7d01f58759caeee5b21f957  dogecoin-1.14.4-win64-debug.zip
d6f4f73b31eb229617a70a6fb3212d46ce27fec44f5e6d7d5221ebb64480a908  dogecoin-1.14.4-win64.zip
843824fd359108bc65bc2c768585eb0b58b7d533b98cd2df1022e229e076dddb  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
0c483145a9fff370c0b099291fec7bb70ea78bb8599737e35ffddd66bbecc5bd  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Review by patricklodder — APPROVED** [review]
ACK. Passes basic tests and passes gitian checks. 🥳

**Pull request merged**
