### PR TITLE
Fixing Persian Translation; mainly repalcing Bitcoin with Dogecoin

### PR DESCRIPTION
**Pull request by jadijadi**
This fixes the issue #2530 by running the `lupdate` and then reviewing the
strings; mainly:

1. replacing references to Bitcoin with Dogecoin
2. fixing some minor typos
3. translating some new strings (like tips)

### CODE REVIEW

**Comment by patricklodder** [comment]
Am investigating the CodeQL result - this is not introduced by this PR.

**Comment by chromatic** [comment]
I looked into that failure/alert too. Best I can tell that code has been there untouched for years. Is this a new alert category CodeQL is throwing?

I've opened a doc-only PR I've been noodling with to see if it occurs there too.

**Comment by patricklodder** [comment]
> Is this a new alert category CodeQL is throwing?

It looks like this is an update to the CodeQL backend where it is now catching this vs previously it wasn't. CodeQL is not set-up to be blocking for merge, so we'll be fine either way.

**Comment by patricklodder** [comment]
**Added "help wanted": it would be great if a native Persian speaker could give this a quick review.**

If that takes too long, since this is still a work-in-progress translation, I propose that we can merge it into 1.14.6-dev and then any corrections can be made at a later time in a separate PR.

**Comment by ZeeAmini** [comment]
Bitcoin whitepaper translator here; I've just reviewed this translation & it is legit.

**Review by ZeeAmini — APPROVED** [review]

**Comment by patricklodder** [comment]
Re: the CodeQL alert. I have marked it as "wont fix", because this is a weakness of Socks5, not Dogecoin Core. This will allow us to merge this PR now. 

I'd prefer to do this after #2882 so that the CI won't throw on the aarch64 experimental build.

**Review by patricklodder — APPROVED** [review]
utACK based on @ZeeAmini's review

The CodeQL alert is not caused by this PR and has been suppressed.

**Comment by HAJRAN786** [comment]
Johhnn pl.










Jkblknbnn jhkkwhkipebohjbeiphogojvkdk663563+++

**Comment by ZachOlivier** [comment]
I find it contradictory to have a 'do not merge yet' label on a PR that has been merged. I see patricklodder added a 'blocked' and removed it before merging, perhaps this label could be removed prior to merging as well.

**Pull request merged**
