### PR TITLE
1.14.4 suggested changes for 2297

### PR DESCRIPTION
**Pull request by ReverseControl**
Implemented the changes requested by @rnicoll. 

Of interest, https://github.com/dogecoin/dogecoin/blob/c196c4f74cd793c30c02dbe57a00014a46b8ffbc/src/validation.cpp#L2652-L2659:

By construction, that is, by the code as written, all children in this loop are invalid(L2655), hence the comment that "(note this may not be all descendants)." is either incorrect, or the code does not do what it should do. I assumed the former and remnoved that comment said comment at line 2653.

### CODE REVIEW

**Comment by ReverseControl** [comment]
@patricklodder Could you please take a look and approve the workflows?

**Comment by patricklodder** [comment]
> By construction, that is, by the code as written, all children in this loop are invalid(L2655), hence the comment that "(note this may not be all descendants)." is either incorrect, or the code does not do what it should do. I assumed the former and removed that comment said comment at line 2653.

The way I read that comment is: all the children in this loop are invalid, but, there may be other descendants that we do not loop over, because the chain tip structure on top of the invalid block can be a tree itself, but we just loop from one leaf branch to the root invalid block and do not consider any competing chain tips within that tree.

**Comment by ReverseControl** [comment]
@patricklodder Understood. Do we need anything else to resolve #2297?

**Comment by patricklodder** [comment]
Just for illustration. Assuming `b1` is valid and `b2` is the invalid block, and we walk until `k`, this is what it means:

```
a-+-b1---c---d----e---f---g [active]
  |
  +-b2---h-+-i1---j---k     [looped over]
           |
           +-i2---l         [not touched]
```

So block `i2` and `l` aren't marked, but if someone were to submit block `m` on top of `l`, that gets traversed at that time anyway, so it doesn't really matter much - eventually, all will be right.

**Comment by ReverseControl** [comment]
@patricklodder Thanks! That helps. Do we need anything else? And, can we get the other folks to look at the #2446 for approval?

**Comment by patricklodder** [comment]
>  Do we need anything else to resolve #2297?

We need a test. I saw that https://github.com/xanimo/dogecoin/commit/f97167743ca42a4ffcb7e015dfdc73920b48d845 was getting close but there are some issues with the version of the python test framework code that code was back ported from (there's a commit on the top that tries to sync up some missing functions from bitcoin's later evolution but it's not looking good yet, and I really don't want to burn ourselves with a larger framework update this late in the cycle.)

I'm looking at it in-depth now.

**Comment by rnicoll** [comment]
Also credit where credit's due, I thought Patrick was heading up the changes on 2297

**Comment by ReverseControl** [comment]
@patricklodder Can we can move this to the next release 1.14.5 ? It does seem like a reasonable amount of work. 
@rnicoll Thank you, Sir. Thanks for taking a look at 2446.

**Comment by patricklodder** [comment]
> Can we can move this to the next release 1.14.5 ? It does seem like a reasonable amount of work.

I am 99.9% sure the test will pass and I am confident that this code is good, just it's currently my word and not provable. Which is a terrible thing to work off and I really don't want to set that precedent. Since I anyway want to take a little time to do some field tests with a 1.14.4 that has the fee rounding changes.

As this patch hardens 1.14 nodes against future effups / contention / hostile peers and as there ...

- has been contention towards the 1.21 softfork plan, and
- is a significant increase in people forking this repo and doing less than optimal things to the code under a different coin name
- I have yet to be enabled to run a 1.21 node off the dev branch here so I really don't know what kind of trouble that will bring 

... I don't want to risk someone forking off this repo, doing something stupid, and then 1.14.4 relays and service leaf nodes have problems in the field later on. So this PR is pretty important.

So here's my counterproposal to postponing:

1. I stage a target 1.14.4 including this and the other still open PRs, and start the field trials right now
2. I work on the test - should really be a couple of hours because the only thing I would do is rip out the disconnect detection and recode it bespoke
3. If I get the test to work in any form, I can ACK and merge this and raise the test PR separately, then others can shoot on the test.

**Comment by rnicoll** [comment]
@patricklodder That sounds good to me BTW, and I'll make sure I have time for the test review in the morning.

**Comment by ReverseControl** [comment]
@patricklodder I strongly support that view.  

As for the counter-proposal: fire away. Once you are done with your part,  I will do all I can to provide support with testing.

**Review by patricklodder — CHANGES_REQUESTED** [review]
Hi! Thank you for this fix. I need 2 changes:

1. All instances of LogPrint need to be changed to LogPrintf because the former takes a debug category as first argument and we don't want that here, and currently this code will run into a runtime error because it interprets the second argument as the format string. 
2. Needs a rebase (to get up-to-date p2p-acceptblock test from there) & squash - could you please:
    - rebase against latest 1.14.4-dev from dogecoin/dogecoin, and
    - do that interactively, squashing:
        - 331a46f01 and c196c4f74 into f347aa9, and
        - [commit that fixes logprint] and 713de16a3 into 56b880fec
    - and then force pushing that commit set?

Thank you!

**Comment by ReverseControl** [comment]
@patricklodder Done!

**Review by patricklodder — APPROVED** [review]
ACK. Tested on Ubuntu 20.04 and 21.04 - QA tests will be taken care of by #2458

**Pull request merged**
