### PR TITLE
Make low-s verification mandatory for standard script verification

### PR DESCRIPTION
**Pull request by patricklodder**
This change makes a node only accept transactions with low-s signature encoding for relay and mining, but allows transactions with high-s signature encoding in mined blocks (no blocks will be rejected)

I'm intending this to be applied against 1.10.0 as we have a soft-fork in there, so older (Dogecoin Core) clients will get reminders about being on an outdated version because of that anyway, which should result in better adoption. We could also consider doing the softfork now, together with BIP66, to not have to do a consensus fork every other release. Thoughts?

Pros:
- If deployed by all miners, this will eliminate this particular malleability attack.
- There is no impact on consensus

Cons:
- Wallets that do not implement low-s signature encoding will see their transactions be rejected by growing numbers of peers and ultimately not be able to get any transaction mined.

Follow ups:
- Eventually, this verification needs to be confirmed through a consensus rule (enforcement of BIP62 for block validation) which will probably be another soft-fork

---
Constraints for hard implementation:
- [x] Majority of "standard" libraries should implement low-s
  - [x] bitcoinj (since 0.11)
  - [x] bitcoinjs (since 1.0.0)
  - [x] bitcoin-ruby (since 0.0.7)
  - [x] python-bitcoinlib
  - [ ] bitcoin-lib-php (not implemented)
- [x] Majority of wallets should implement low-s
  - [x] Dogecoin Core (since 1.7)
  - [x] Multidoge (since 0.1.5)
  - [x] Android
  - [x] Doughwallet (iOS)
  - [x] Web-wallets
    - [x] dogechain.info
    - [x] block.io
    - [x] redeempaper.com
    - [x] dogeparty wallet => live wallet updated, patch submitted to upstream
- [x] 95% of transactions over last 100k blocks must have low-s encoding

### CODE REVIEW

**Comment by langerhans** [comment]
Well, I'm certainly okay with forking less, even with "just" soft forks ;)  

Let's see how our typical adoption process goes and what it means. Usually we see some early birds updating right away. But as we remember from 1.8, even after weeks and an impending hard fork we saw 50-60% adoption. Given that 1.10 won't be a hard fork but somehow required either way I'd still not assume an adoption anywhere near to it. We will see 1.8 peers and continue to see them.
Looking at miners and assuming many probably run custom clients which need to be updated and that needs care and blah, I'm not so sure how fast they will upgrade, but if they do, it'll lead to a rather quick (super-)majority (5 largest pools make up 96% of the hashrate).

If that happens and older clients won't be able to get their transactions mined anymore, that's bad.

So points to consider I see additionally:   
* Will 1.8 nodes get a warning early enough?  
* How about the light wallets? Do they already send low-s, or do they need an update?

**Comment by patricklodder** [comment]
Added checklist to verify if those wallets encode low-s:

- Dogecoin core does this since 1.7
- bitcoinj has been doing this for a long time, but doesn't hurt to check the versions android and multidoge have been linked against
- we should check the ruby/py/php libs

**Comment by patricklodder** [comment]
bitcoin-ruby and android wallet check out, added redeempaper.com as that's often used.

**Comment by tanukifu** [comment]
Probably not a bad idea to add this -> but wouldn't it be a good idea to also add code to the core to just intentionally mal. a high-s variant to low-s so it can be relayed and/or mined by a node rather than simply rejected?

**Comment by langerhans** [comment]
@tanukifu That would defeat the whole purpose of it, besides the fact that you can't change the signatures of other's transactions :open_mouth:

**Comment by patricklodder** [comment]
@langerhans unfortunately you can change signatures of transactions you do not have the key for, for this particular weakness (and afaik all others mentioned in bip62). Making a pseudo node that performs this attack on every transaction it sees takes 8-10 lines of non-boilerplate code on bitcoinj/libdohj.

@tanukifu the problem i have with it is that we're taking the position: "this is the standard, but if you're not able to follow the standard, we'll accept it anyway and fix it for you." If we'd do that for every protocol change, we'll have a lot more code to maintain.

The only place we've done this before was with historical non-der signatures already on the blockchain, because of a regression in openssl. We didn't have much of a choice there, but that code is also local to a node.

Looking at the wallets and libs that already implement this, we're quite ok, with the exception of multidoge, but I really think I won't have much trouble convincing langerhans that we need an update and worst case I can supply a patch (but it really is not all that hard)

If nobody beats me to it, I will dig into the last 10-100k blocks and check how good our coverage is.

**Comment by tanukifu** [comment]
Ah, looking at it from the perspective of not wanting to set a precedent...  yes, I agree that not including code to automatically change the form in this case makes more sense.

**Comment by patricklodder** [comment]
I propose to set a manual constraint that n% of transactions over m blocks are using low-s encoded sigs is needed for us to merge this quickly, counting from block 907000 (`d9ea8cceed3356792dac20d0b8012d9726b90694ac6ecc1151aac14231a24f0a`) to prevent trolling.

I had n = 95% and m = 100.000 in mind.

**Comment by rnicoll** [comment]
@tanukifu Also, if we take a transaction, modify it and relay the modified version, it looks like we're broadcasting double-spends!

**Comment by tanukifu** [comment]
@rnicoll -> yup, but it would be a version that could be mined and confirmed...  (which is perhaps more useful for the person who intended to send the coins if the tx was built by software not complaint with low-s)

My first thought was along the lines of 'It's simple to just fix the non-compliant software implementations to be less of a hassle for users'...  I did not consider that it could set a precedent that future changes could be expected to cover live weak/deprecated implementations.  That is a very valid reason for me to not just fix certain mal. tx in flight (although I might revisit the idea in the future depending on how this plays out).

**Comment by patricklodder** [comment]
low/high s stats aggregated per 1000 blocks:
low/high s

totals:
totals

I have not yet checked p2sh yet

**Comment by langerhans** [comment]
That could very well be all MultiDoge. Gonna have to setup a dev environment for that tho and figure out again how to properly build it.

**Comment by patricklodder** [comment]
multidoge patched for low-s (0.1.5). check.

**Comment by langerhans** [comment]
Do we need to backport to 1.8.3?

**Comment by patricklodder** [comment]
> Do we need to backport to 1.8.3?

IMHO, yes.

**Comment by patricklodder** [comment]
forgot to check the dogeparty wallet, and unfortunately it's high-s. I'll fix that asap

**Comment by patricklodder** [comment]
seems to me that patching multidoge has fixed this, we've had only 15 high-s signatures out of 124,159 in the past 5000 blocks.

**Comment by patricklodder** [comment]
graph until 921k

**Comment by langerhans** [comment]
Well, then let's get this merged, shall we? :)

**Pull request merged**
