### PR TITLE
Change result from getauxblock to BIP22 validation state

### PR DESCRIPTION
**Pull request by rnicoll**

### CODE REVIEW

**Comment by langerhans** [comment]
This should probably include https://github.com/dogecoin/dogecoin/commit/e2334c99e

**Comment by rnicoll** [comment]
Actually with https://github.com/dogecoin/dogecoin/commit/e2334c99e it's basically no-change isn't it? This adds a more complex return which `e2334c99e` then turns back into a simple one?

This is probably a "Does not need to be applied" in hindsight.

**Comment by langerhans** [comment]
https://github.com/dogecoin/dogecoin/commit/e2334c99e also adds a compatibility method though. I do not know what current pool implementations use so I'd rather have us offer both variants. Or am I missing something here?

**Comment by rnicoll** [comment]
I'll check, but it doesn't look like `getauxblockbip22` is actually exposed anywhere

**Comment by langerhans** [comment]
`getauxblock` decides based on the parameters what to return. So it is kinda exposed.

**Comment by rnicoll** [comment]
Ah, got it! Yup will get that glued on in.

**Pull request merged**
