### PR TITLE
Use C++11 range-based for loops instead of BOOST_FOREACH loop

### PR DESCRIPTION
**Pull request by AjaxPop**
We should prefer C++11 range-based for loops over BOOST_FOREACH loops because they are more efficient and easier to maintain.

### CODE REVIEW

**Comment by chromatic** [comment]
I like this change. There are a lot of files where we could do the same; are you interested in updating several others?

**Comment by AjaxPop** [comment]
> I like this change. There are a lot of files where we could do the same; are you interested in updating several others?

Done

**Comment by AjaxPop** [comment]
I am able to get these errors locally. 
I will keep on working on it

**Comment by AjaxPop** [comment]
It looks like my branch that I was working on did not update to the fixate v1.14.6 #3048 version. Also, it looks like some code in the nMockTime update was removed.

Should I just close this pull request out and try again with a smaller number of files?
@patricklodder

**Comment by AjaxPop** [comment]
Given the large number of files that have been changed and the current issue with setmocktime, I am going to close this.

**Pull request closed without merging**
