### PR TITLE
Refresh baseline language files

### PR DESCRIPTION
**Pull request by rnicoll**
Also fixes the `Makefile` so this is easier to run.

### CODE REVIEW

**Comment by patricklodder** [comment]
Note that there are additional items to be translated in #2654.

**Comment by rnicoll** [comment]
Noticed it's lost translations in the reshuffle.... not sure if that's the correct result, will look at again tomorrow, would appreciate thoughts on whether we keep translations which are now incorrect, or remove them.

**Comment by patricklodder** [comment]
> Noticed it's lost translations in the reshuffle

The only one I see is the one that's actually changed, where instead of measuring against dust, we measure against discard threshold now - which we probably could make a best-guess for in terms of translations, but I think we shouldn't.

While we work on everything up to the actual v1.14.5 tag, which is the final cutoff, there is still time for translators to submit these translations - it's only 6 sentences per language that get added with this, so it's not like this is weeks of work. I can do the Dutch translation if no one else wants to do it.

**Comment by Alirezahaghgoo1** [comment]
If there is anything to translate in "Farsi", I can help with that!

**Comment by rnicoll** [comment]
Okay, lets merge this then and I'll ask for translations to be added in.

**Review by patricklodder — APPROVED** [review]
utACK. Checked the code and translation changes. They're consistent!

**Pull request merged**
