### PR TITLE
Paper wallet dialog warning update

### PR DESCRIPTION
**Pull request by peoplma**
Make it clear in dialog that paper wallet privkeys are not saved.

### CODE REVIEW

**Comment by langerhans** [comment]
This warning only appears when you try to print paper wallets while being connected to any other nodes. Are you sure this is the right place for this warning? But maybe I'm putting too much faith in the users by assuming most of them would actually only generate paper wallets on an air gapped machine ;)

**Comment by peoplma** [comment]
Yeah, people using it offline probably already know what they are doing.  Hmm, maybe get rid of the if statement, change the dialog title to just "warning" and have it show up every time?

**Comment by langerhans** [comment]
Pretty sure, the online warning should stay, I have hopes that people can learn ;)  

Maybe we can put your warning somewhere else? Into the actual dialog? Or, we could check if the user actually clicked the "Print" button before they close the window?

**Comment by peoplma** [comment]
Oh I wasn't suggesting getting rid of the online warning, just showing it no matter if you have connections or not (after all, 0 connections doesn't necessarily mean the computer is offline).  So that the warning shows everytime you open the paper wallet generator.  

But either of those other options would work too :)

**Comment by patricklodder** [comment]
@langerhans do we still want to push this? Needs some rework / conflict resolution for 1.14.3.

**Comment by patricklodder** [comment]
I'm taking this off the critical path for 1.14.3 as this still needs conflict resolution.

**Comment by patricklodder** [comment]
If this still makes sense to change, please reopen against 1.14.4-dev or 1.21-dev.

**Pull request closed without merging**
