### PR TITLE
snap packaging for 1.14.5

### PR DESCRIPTION
**Pull request by slightlyskepticalpotat**
A couple changes:

- Fixed formatting of packaging instructions
- Updated location of dogecoin icon because of c42dba492ba9c12a79a3dcf8526e17b4215c452e  
- Incremented version number
- Notify user if the tests passed/failed
- Improve the security, now instead of checking if the hash exists _somewhere_ in the gitian repo, now the script checks if the hash exists _and_ is for the same file

### CODE REVIEW

**Review by patricklodder — COMMENTED** [review]
For some reason none of my build boxes wants to work with `multipass`, so it'd be great if someone other than me could test this.

utACK on the code changes

**Comment by slightlyskepticalpotat** [comment]
Do you have VT-x/AMD-V/SVM enabled? I previously had problems with Multipass until I enabled virtualisation.

**Comment by patricklodder** [comment]
> Do you have VT-x/AMD-V/SVM enabled?

Correct. The issue is that my build environments are themselves virtualized and I have no idea how to enable it there right now. So, it's quicker if someone else, with actual hardware, tests it :grin:

**Comment by chromatic** [comment]
```
*** No errors detected
+ echo Dogecoin tests passed.
Dogecoin tests passed.
+ echo Installing Dogecoin...
Installing Dogecoin...
+ install -m 0755 -D -t /root/parts/dogecoin-core/install/bin dogecoin-1.14.4/bin/dogecoind
+ install -m 0755 -D -t /root/parts/dogecoin-core/install/bin dogecoin-1.14.4/bin/dogecoin-qt
+ install -m 0755 -D -t /root/parts/dogecoin-core/install/bin dogecoin-1.14.4/bin/dogecoin-cli
+ wget https://raw.githubusercontent.com/dogecoin/dogecoin/master/share/pixmaps/dogecoin128.png
--2021-08-21 11:17:57--  https://raw.githubusercontent.com/dogecoin/dogecoin/master/share/pixmaps/dogecoin128.png
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15289 (15K) [image/png]
Saving to: ‘dogecoin128.png’

dogecoin128.png                                            100%[=====================================================================================================================================>]  14.93K  --.-KB/s    in 0.001s  

2021-08-21 11:17:58 (20.6 MB/s) - ‘dogecoin128.png’ saved [15289/15289]

+ install -m 0644 -D -t /root/parts/dogecoin-core/install/share/pixmaps dogecoin128.png
Building qt4conf 
+ snapcraftctl build
make -j2
make: Nothing to be done for 'all'.
make install DESTDIR=/root/parts/qt4conf/install
install -D -m644 snappy-qt4.conf \
	/root/parts/qt4conf/install/etc/xdg/qtchooser/snappy-qt4.conf
install -D -m755 qt4-launch /root/parts/qt4conf/install/bin/qt4-launch
Staging dogecoin-core 
+ snapcraftctl stage
Staging qt4conf 
+ snapcraftctl stage
Priming dogecoin-core 
+ snapcraftctl prime
Priming qt4conf 
+ snapcraftctl prime
The command 'dogecoind' for 'dogecoind' was resolved to 'bin/dogecoind'.
The command 'dogecoind' has been changed to 'bin/dogecoind'.
The command 'qt4-launch' for 'qt4-launch dogecoin-qt' was resolved to 'bin/qt4-launch'.
The command 'qt4-launch dogecoin-qt' has been changed to 'bin/qt4-launch dogecoin-qt'.
The command 'dogecoin-cli' for 'dogecoin-cli' was resolved to 'bin/dogecoin-cli'.
The command 'dogecoin-cli' has been changed to 'bin/dogecoin-cli'.
Snapping |                                                                                                                                                                                                                    
Snapped dogecoin-core_1.14.4_multi.snap
```

This built fine for me (after I changed `1.14.5` locally to `1.14.4`, so `snapcraft` could download the release from `https://github.com/dogecoin/dogecoin/releases/download/v1.14.5/dogecoin-1.14.5-x86_64-linux-gnu.tar.gz`.

What more verification would you like to see?

**Comment by patricklodder** [comment]
> What more verification would you like to see?

This works for me - 4-eye principle complied with and all that stuff.

THANK YOU!

**Review by patricklodder — APPROVED** [review]
utACK from me on code, tested by @chromatic

**Pull request merged**
