### PR TITLE
should we don't follow DRY principle? here

### PR DESCRIPTION
**Pull request by phyBrackets**
I think We have to follow don't repeat yourself pattern here! But for sure it reduce the readability of code.

### CODE REVIEW

**Comment by patricklodder** [comment]
I expect that changing has a (be it minor) performance impact besides readability, and this is benchmark code that actually measures performance. I'd rather leave it as-is because of that, keep things comparable. Bitcoin Core (where this code comes from 100%) still does this in their latest benchmark code. If you really think it's important, I'd recommend to propose upstream at https://github.com/bitcoin/bitcoin

**Comment by victorsk2019** [comment]
> changing has a (be it minor) performance impact besides readability,

Because these are separate operations with O(1) instead of O(N) in for-loop?

**Comment by patricklodder** [comment]
> Because these are separate operations with O(1) instead of O(N) in for-loop?

Yes, it basically adds a comparison, an addition and a multiplication inside that loop, which is inside the timed portion of the benchmark. If it would increase readability I'd be fine with it, but it doesn't, so I'd recommend to leave it alone unless there is a compelling reason I miss.

**Comment by patricklodder** [comment]
I'm closing this because no one argued why DRY > readability/performance. We can reopen this if someone really thinks we should change the benchmark code.

**Pull request closed without merging**
