### PR TITLE
Update to French-Canadian Translations

### PR DESCRIPTION
**Pull request by daank-c**
This is a fairly large update to the French-Canadian translation file `bitcoin_fr_CA.ts`, as it was almost bare when I started a couple days ago. I filled in about 75% of the translations available, but left the other 25% for another time.

For the most part, the changes I've made here were grabbed from a version of `bitcoin_fr.ts` prior to #3195 . I did make some minor adjustments to wording and added some missing punctuation, but nothing too major.

### CODE REVIEW

**Comment by patricklodder** [comment]
Looks good technically 👍. 

I've added "help wanted": it would be great if a native speaker could review.

**Comment by patricklodder** [comment]
> The [conversation](https://x.com/daanksy/status/1761826607038148873) took place on X. We're still hashing out some technical interpretations in that same conversation.

Noting @John-Inubook as reviewer.

**Comment by patricklodder** [comment]
Could really use a squash. Let me know if you need help or have me do it for you.

**Comment by John-Inubook** [comment]
I'm French Canadian, I've read the work made by Daansky and I shared with him on X the different changes that needed to be done. Glad I could be of any help.

**Review by patricklodder — APPROVED** [review]
ACK - code review ok

Language validation by @John-Inubook

**Pull request merged**
