### PR TITLE
Added pt_PT Readme

### PR DESCRIPTION
**Pull request by qlpqlp**
Added pt_PT Readme

### CODE REVIEW

**Comment by edtubbs** [comment]
I wish I could review these but I can't read Portuguese.  I'll try to find another way to help with it though.

**Comment by qlpqlp** [comment]
eheh, only saw this today. Intense last days for me :P
I will try to again ask any Portuguese reviewers :D

**Comment by qlpqlp** [comment]
> Before we spend a lot of time on reviews, what's the benefit of having both pt-PT and pt-BR?
> 
> Can we choose one that everyone understands?

In a cultural way, some people don't like to read in Brazilian (pt-BR) and others don't like to read Portuguese in (pt_PT) 
It´s ~ like you people listen Canadian people speak vs American people speaking, but the writing and words in Portuguese and Brazilian are completely different, but

Example:

User: Usuário (pt-BR)
User: Utilizador (pt-PT)

Password: Senha (pt-BR)
Password: Palavra-passe (pt-PT)

A greater explanation is in this website : https://www.dicio.com.br/portugues-de-portugal-e-a-diferenca-com-o-portugues-do-brasil/
image

**Comment by qlpqlp** [comment]
> I don't think this repository should be a place to host nationalism. If adding the Brazilian translation is deemed offensive by the 10M people from Portugal then perhaps we made a mistake and we need to consider removing all translations of the README.

I actually see Portuguese from Portugal having a huge impact, so, actually I don't see your comment in anyway constructive to CORE, sorry.

I'm now asking someone from Portugal to review if that is OK with you.

**Comment by patricklodder** [comment]
We'll have a solution for this with the next release.

**Comment by patricklodder** [comment]
I've written a problem statement and proposal to fix re: those readme files in #3436

**Comment by qlpqlp** [comment]
> I've written a problem statement and proposal to fix re: those readme files in #3436

Much thanks @patricklodder

**Comment by patricklodder** [comment]
Please rework this to the structure introduced by #3459, so that this can go in.

**Comment by qlpqlp** [comment]
> Please rework this to the structure introduced by #3459, so that this can go in.

OK, I will, just give me a couple of hours until tomorrow my time
 thanks Patrick <3

**Pull request closed without merging**
