### PR TITLE
Lwllace patch 1 1

### PR DESCRIPTION
**Pull request by lwllace**
i fixed a few issues

### CODE REVIEW

**Comment by lwllace** [comment]
ok

**Comment by patricklodder** [comment]
Hi! Could you please split this PR into 2 different ones, one that adds CodeQL and one that does the fixes?

Also, please do them against branch 1.14.3-dev.

**Comment by lwllace** [comment]
ok i changed the master to 1.14.3-dev

**Comment by lwllace** [comment]
> Hi! Could you please split this PR into 2 different ones, one that adds CodeQL and one that does the fixes?
> 
> Also, please do them against branch 1.14.3-dev.

now how do i split them

**Comment by patricklodder** [comment]
> now how do i split them

```
git checkout -b codeql-config 1.14.3-dev # new branch
git cherry-pick 19dff16 #cherry pick the last commit
git push origin codeql-config # push to GitHub, make PR from there
git checkout lwllace-patch-1-1 # branch for this PR
git reset b2eb6ff # pop off the last commit
rm .github/workflows/codeql-analysis.yml
git push -f origin lwllace-patch-1-1 # force push the branch, this PR will automatically update
```

**Pull request closed without merging**
