### PR TITLE
fix bugs in Chinese translation

### PR DESCRIPTION
**Pull request by randomwalk266**

### CODE REVIEW

**Review by mitchell771 — DISMISSED** [review]

**Comment by patricklodder** [comment]
Thank you! Marked `help wanted` -> we could use a review from a native speaker.

**Review by bobdos — APPROVED** [review]
all translations are correct.

**Review by slightlyskepticalpotat — APPROVED** [review]
Yep, the translations are correct.

**Comment by patricklodder** [comment]
Thank you @bobdos and @slightlyskepticalpotat ❤️

**Review by patricklodder — APPROVED** [review]
utACK on 5866566

- has been community reviewed
- checked with the devtools script:
```console
$ git rev-parse HEAD
586656667e1963426e46e51f64a0be26a96862c2
$ python3 contrib/devtools/check-translations.py 
Checking all translations...
No errors detected.
```

**Comment by randomwalk266** [comment]
> script:

is there still anything i need to do before merge?

**Comment by patricklodder** [comment]
> is there still anything i need to do before merge?

No, I am merging it now ❤️

**Pull request merged**
