### PR TITLE
refactor: improve efficiency and fix all CVEs

### PR DESCRIPTION
**Pull request by SamSamskies**
This should solve all the problems discussed on the dev call that we had with Papa Elon.

### CODE REVIEW

**Review by Tracachang — APPROVED** [review]

**Comment by conradcreel** [comment]
hahahaha

**Review by aspenluxxxy — APPROVED** [review]

**Review by scrpatlolla — CHANGES_REQUESTED** [review]
@rnicoll

**Comment by seanyesmunt** [comment]
LGTM

**Comment by Nirad** [comment]
oh..

**Review by Nirad — APPROVED** [review]

**Review by Nirad — APPROVED** [review]

**Comment by bytebuddha** [comment]
Lol some of the dumbest PR's i've ever seen on github came out of this repository in the past couple days. How is this not closed already seriously? Although it certainly would fix every CVE effecting DOGE

**Comment by slightlyskepticalpotat** [comment]
It took me a while to get the joke, but this PR is still the best out of
the past few PRs because it recognises that it's a joke.

>

**Comment by bytebuddha** [comment]
@slightlyskepticalpotat even better my autistic ass didn't realize it was a joke until you said that

**Comment by rnicoll** [comment]
While I acknowledge this resolves all current and future CVEs, I feel it does so at a perhaps unacceptable loss of user experience 😄

**Pull request closed without merging**
