### PR TITLE
CI: Cirrus Integration

### PR DESCRIPTION
**Pull request by micaelmalta**
Same environments as .travis checks

### CODE REVIEW

**Comment by rnicoll** [comment]
Anyone object to us enabling both Cirrus & GitHub actions? Bit of a resource waste but might find stuff we've missed elsewhere. @langerhans?

**Comment by patricklodder** [comment]
> Anyone object to us enabling both Cirrus & GitHub actions? 

What does it add? Didn't we decide to keep 2 CI implementations in parallel to be able to compare? 

https://github.com/dogecoin/dogecoin/discussions/2302#discussioncomment-870032

**Comment by mmicael1** [comment]
> > Anyone object to us enabling both Cirrus & GitHub actions?
> 
> What does it add? Didn't we decide to keep 2 CI implementations in parallel to be able to compare?
> 
> [#2302 (comment)](https://github.com/dogecoin/dogecoin/discussions/2302#discussioncomment-870032)

@patricklodder  On Cirrus, we are doing tests on windows and it also includes MACOS
PS: Windows and MACOS cross compile are not working with ubuntu 20.04

**Comment by patricklodder** [comment]
> On Cirrus, we are doing tests on windows 

I can give you the same comment as was made on #2322, see https://cirrus-ci.com/task/4607965110992896?logs=test#L1956 - so this is 100% the same build/test as implemented on GH actions.

> and it also includes MACOS

Because it builds on bionic. I personally feel it would be suboptimal to build on 18.04 for gitian builds once we release if we can do a full update to 20.04 and have a modern build environment on both CI and Gitian on the latest LTS that will be good for some years to come. (also for 1.21!)

> PS: Windows and MACOS cross compile are not working with ubuntu 20.04

I got Windows to work on GH actions. Just need to select different apt package and we're working on macOS, this is documented in #2321. You kind of have the same integration ahead of you that I am already putting out with GH Actions, so this feels like duplicate work with no real benefits?

**Comment by mmicael1** [comment]
I m not pushing for one or another but I do feel we are going in inconsistent directions where 1.14 would be using Github Actions while 1.21 might be using Cirrus.

**Comment by patricklodder** [comment]
Once we have built some experience with both, we can make a choice and make it consistent cross-branch again, assuming that 1.14 lives that long. If we see a quick network majority of 1.21, we can simply archive 1.14 and not worry about it.

**Comment by mmicael1** [comment]
I can already add one feedback: GH Actions is way faster than Cirrus! So fast, that it faster to commit and push than test it locally!

**Comment by p-j01** [comment]
Maybe [act](https://github.com/nektos/act) can take the same time without having to commit and push.

**Comment by patricklodder** [comment]
> I can already add one feedback: GH Actions is way faster than Cirrus! So fast, that it faster to commit and push than test it locally!

Do you use ccache locally?

**Comment by patricklodder** [comment]
> I can already add one feedback: GH Actions is way faster than Cirrus! So fast, that it faster to commit and push than test it locally!

Do you use ccache locally?

**Comment by patricklodder** [comment]
> I can already add one feedback: GH Actions is way faster than Cirrus! So fast, that it faster to commit and push than test it locally!

Do you use ccache locally?

**Comment by patricklodder** [comment]
I think it's decision time on this one. 

We've now had GH Actions for a couple of releases. It is in general faster and easier to manage than cirrus at the cost of having to deal with some MS quirks (i.e. #2978) Cirrus offers more customization and makes us less dependent on MS development - and maybe GitHub (?). In my opinion though the worst bug with the CI we've seen so far was #2882, which we'd had on either CI provider, as it was an Ubuntu packaging issue. 

Do we want to switch? If yes, then we need to port most of this to bionic to be closer to gitian builds.

Do we keep this open as a backup? If yes, then we need to refresh the PR sometimes to see if it still works.

Would like to know opinions.

**Comment by xanimo** [comment]
> I think it's decision time on this one.
> 
> We've now had GH Actions for a couple of releases. It is in general faster and easier to manage than cirrus at the cost of having to deal with some MS quirks (i.e. #2978) Cirrus offers more customization and makes us less dependent on MS development - and maybe GitHub (?). In my opinion though the worst bug with the CI we've seen so far was #2882, which we'd had on either CI provider, as it was an Ubuntu packaging issue.
> 
> Do we want to switch? If yes, then we need to port most of this to bionic to be closer to gitian builds.
> 
> Do we keep this open as a backup? If yes, then we need to refresh the PR sometimes to see if it still works.
> 
> Would like to know opinions.

I am personally dealing with some package management issues outside of core that just appeared out of the blue with regards to GH actions and although I'm not certain it's to do with MS or azure apt-repositories, I'm displeased with the frequencies of these errors.

I don't have much of an opinion regarding Cirrus outside it's cost but if that's not an issue I'd say it's probably prudent it's kept as a backup considering recent GH outages. It also makes me wonder if there are any contingency plans for mirroring this repository should such outages become more frequent but is outside the scope of your question and best saved for another discussion. On the other hand if kept, it adds potentially unwarranted overhead for maintenance? I think best answered by maintainers but always good to have a backup plan. :shrug:

**Comment by patricklodder** [comment]
Backup plan = Linus Plan: just mail me your gig-signed patch files 😂

I've actually been looking into the time it takes to move from GitHub to a self-hosted Gitea and the answer is 10 minutes. Excluding all pulls. So I think we're good because the only pulls we'll miss are the ones made in the GH editors. Most pulls can be re-submitted.

However, what we won't have within 10 minutes is a CI. I can have a tailored CI based on [lxd](https://github.com/lxc/lxd) or with a bit of luck, [firecracker](https://github.com/firecracker-microvm/firecracker}, up in a couple of days but yeah that would be stressful. So I don't mind keeping cirrus as the backup plan, but then we'll need to shadow maintain a good CI with it.

**Pull request closed without merging**
