### PR TITLE
Update README_zh_CN.md

### PR DESCRIPTION
**Pull request by MVShishkov**
Hi! Here is the updated Chinese README.md. task number #2688.
I am from Russia and can read, write, speak and listen in the Chinese. Also I am a former electronic and IT developer. My successful projects are LADA Connect, eCall (ERA-GLONASS), Connected FORD, Connected Mercedes and KIA for Motor-Car.
I hope that my knowledge and skills will benefit the community!) Feel free to write me and ask me!)

### CODE REVIEW

**Comment by MVShishkov** [comment]
Minor improvements were done. Please check and merge if OK the last commit

**Comment by patricklodder** [comment]
Thank you!

Help needed: need help with the review from a native speaker.

**Comment by ReverseControl** [comment]
@Mohammedasif786 Have you checked the translation? Feedback would be greatly appreciated.

**Comment by bingoko** [comment]
> Thank you!
> 
> Help needed: need help with the review from a native speaker.

looks to me that the translation is not native, and there are some grammar errors.

**Comment by MVShishkov** [comment]
@bingoko Hi! Can you correct it? It would be great! Therefore, we can see where are mistakes and what is not native. After that, these changes could be applied to the file. 
Thanks in advance!

**Review by Sergio8A1994 — COMMENTED** [review]
MVShishkov:patch-1

**Comment by Mohammedasif786** [comment]
Who are you?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by abapChaoLiu** [comment]
Hi! I'd like to help as a Chinese native speaker. 
Is there a way to make changes directly instead of making comments?
I'm not that familiar with the GitHub review process. Help is needed.

**Comment by patricklodder** [comment]
@MVShishkov are you able to rebase this on the current 1.14.6-dev? There's a merge issue with the logo because its position was changed since the 1.14.5 release, and we need to get rid of the merge commit inside the PR.

Let me know if you need help, I can do it for you.

**Comment by MVShishkov** [comment]
> @MVShishkov are you able to rebase this on the current 1.14.6-dev? There's a merge issue with the logo because its position was changed since the 1.14.5 release, and we need to get rid of the merge commit inside the PR.
> 
> Let me know if you need help, I can do it for you.

Yes please help. As actually i do not able to rebase.

**Comment by MVShishkov** [comment]
@patricklodder also i compared with master branch readme.md and did not find and changes with README_zh_CN.md in logo position. Maybe i am looking not in propped directory? Please help

**Comment by patricklodder** [comment]
> i compared with master branch readme.md

This is because we're merging into 1.14.6-dev, which is ahead of master

> Please help

Done!

**Review by patricklodder — APPROVED** [review]
ACK, as this has become a collaborative PR.

**Comment by MVShishkov** [comment]
@patricklodder Thank you very much!

**Pull request merged**
