### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by fluteds**
Updated the readme for Dogecoin! 

### Changes: 

- Centred the dogecoin photo and title.
- Removed dead image links.
- Updated Travis ci badge link to direct to the master branch and the new Travis website url.
- Added Emojis to headers for clarity and to get the feel of dogecoin for newcomers. 
- Added a section for wallets and linked to the [official dogecoin wallet. ](https://dogecoin.com/getting-started/)
- Bolded some sub headers for clarity. e.g. block reward sections.
- Code formatting.

Branch was taken from the 14.2 dev build.

### CODE REVIEW

**Review by slightlyskepticalpotat — COMMENTED** [review]
The changes in your PR cover more files than just the readme (57 in total). Is there a reason for that? Additionally, the 1.14.3 branch will be merged into master soon anyways, so I don't think making such a drastic change now is a good idea.

**Comment by micheleberardi** [comment]
i would like to be part o f the team

**Comment by DemonRx** [comment]
This PR is against the master, it needs to be set against 1.14.3-dev branch. Too many people making this simple mistake.

**Comment by fluteds** [comment]
I'll close this pull request and redo it against the dev branch for consideration. I didn't notice that it also included changes from other files!

**Comment by fluteds** [comment]
Closing to reopen against 1.14.3-dev for consideration.

**Pull request closed without merging**
