### PR TITLE
build: update AX_CXX_COMPILE_STDCXX to serial 18

### PR DESCRIPTION
**Pull request by patricklodder**
Downloaded the latest version available from https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html at the time of writing. This allows configuring for up to c++20.

Prerequisite for getting c++17 to work because the current version (4) only supports up to c++14.

### CODE REVIEW

**Comment by patricklodder** [comment]
I've added "rebase needed" - although it can be done separately, ideally this goes in after #3492, to run CI over a larger test surface when we touch this kind of stuff.

**Comment by patricklodder** [comment]
rebased to trigger a c++14 CI run

**Comment by patricklodder** [comment]
Note: if we want to solve #3547, we'll need this to enable support for c++17 through autoconf.

**Comment by xanimo** [comment]
utACK. no differences from [](https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx.m4) and [](https://raw.githubusercontent.com/dogecoin/dogecoin/6c3a24b252893a232482c841b6aa5e90ec0675eb/build-aux/m4/ax_cxx_compile_stdcxx.m4)

**Comment by chromatic** [comment]
All tests pass and code looks good, but in my local checkout I see that the name `Jörn` is somehow misrendered. I see the same in the diff as shown on GitHub; is there a missing file encoding we need to add?

**Comment by patricklodder** [comment]
> [..] in my local checkout I see that the name Jörn is somehow misrendered. I see the same in the diff as shown on GitHub; is there a missing file encoding we need to add?

This appears to be an upstream issue, not ours, because the same character sequence is shown in [GNU's repo](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_cxx_compile_stdcxx.m4)

I propose to keep it the same as upstream - we get better traceability that way, and it's not up to us what the copyright line should say anyway.

**Comment by chromatic** [comment]
Agreed on matching upstream.

**Review by chromatic — APPROVED** [review]
ACK, all tests pass on x86-64 Linux. Text matches against upstream (with the caveat of potential encoding oddness, though that also reproduces against upstream Git).

**Pull request merged**
