### PR TITLE
Add paper wallet generator to QT wallet

### PR DESCRIPTION
**Pull request by rnicoll**
I've rebuilt @Andymeows' paper wallet generator around Dogecoin Core 1.10 - this is rough and not yet fully tested, but given the scope of the changes I thought it better to get them in now, than risk further conflicts later.

Testing/code review would be appreciated.

### CODE REVIEW

**Comment by langerhans** [comment]
Tested on Debian 8 and prints fine. Tested on Windows 10 and I can't get the "So Print" button to do anything. Have a feeling might be Qt acting up for some reason again.

**Comment by rnicoll** [comment]
Only idea I've got is that for some reason  the print dialog isn't opening. Everything else should spew clear errors. I don't actually have Dogecoin building for Windows yet... err... can you take a look?

**Comment by langerhans** [comment]
Yes, I'll take a closer look. I think this exact issue popped up before and was fixed. I don't remember how and can't find a PR for it, but it will be fixed eventually ;)

**Comment by rnicoll** [comment]
Wonder if #779 is related perhaps...

**Comment by rnicoll** [comment]
http://stackoverflow.com/questions/17175398/deployed-qt5-application-doesnt-print-or-show-print-dialog Suggests it might be missing the minimal library, but checking against #693 all references seem to be added...

**Comment by rnicoll** [comment]
Wait, was reading wrong branch...

**Comment by langerhans** [comment]
Confirmed working on Windows now, thanks! Icon looks nice too:

**Pull request merged**
