### PR TITLE
Syncing for 1.21 implementation

### PR DESCRIPTION
**Pull request by victorsk2019**
Thought I'd propose this PR, before I forget what I did 😂, for making fully functional synchronization work in 1.21. I think it's important to have 1.21 synchronize fully with network to allow for more testing scenarios like create wallets, send/receive **small** test amounts (which build and run successfully for me in Linux and MacOS environments).

This PR https://github.com/dogecoin/dogecoin/pull/2562 was very helpful starting point to first get headers to sync and then once that got going, implementing complete synchronization turned out to be easier than I thought: it's basically adding `CheckAuxPowProofOfWork()` in `dogecoin.cpp` and modifying other sources to work with this change.

### CODE REVIEW

**Review by CryptoUnchained — APPROVED** [review]

**Review by CryptoUnchained — APPROVED** [review]

**Review by CryptoUnchained — DISMISSED** [review]

**Comment by victorsk2019** [comment]
A few notes.  I use exact proposed changes for `GetDesirableServiceFlags()` in `protocol.cpp` as suggested in PR https://github.com/dogecoin/dogecoin/pull/2562, but I also commented out function arguments passed with `NODE_WITNESS` to see what it was if/when SegWit is added.  I was at first changing values in `protocol.h`, following OOP design principles, but functional tests seem to require original `NODE_WITNESS` value and so the solution proposed in https://github.com/dogecoin/dogecoin/pull/2562 is the only one that works for all circumstances 👍

I had some issues running `rpc_getblockstats.py` tests, and after quickly skimming through the script, I believe that going straight to `self.generate_test_data(test_data)` line allows to run required tests without having to open/read test data file, which could be having some issues there?

**Review by patricklodder — CHANGES_REQUESTED** [review]
First off, thanks!

Concept ACK - could use some work before we can do code review and testing:

1. Needs a rebase on top of 34b08cd
2. Please remove all the segwit related changes - that really needs to be done (carefully) in a separate PR and it *should* not be blocking sync in the first place. If I am wrong and it does, I suggest we look into that prior to enabling auxpow.
3. Please remove the checkpoints that you added - those haven't been vetted and aren't needed as there are plenty of checkpoints listed past block `371337` in there already
4. This needs unit tests so that future errors will be caught - you can probably pick `src/test/auxpow_tests.cpp` from #1974 - I'm okay with doing the functional tests in a next step (because we'd need to add the RPC endpoints for that.)

The result of this PR will then be a software that can accept auxpow blocks, but still lack facilities to produce them and I think that is a good and big enough step forward. This would also solve my biggest headache with #1974 because that is extremely hard to review as it touches everything and at the same time enables us to have a clear path forward for development while manual testing can be performed on testnet in parallel.

**Comment by victorsk2019** [comment]
Hi,

Thank you for the feedback.  Makes sense - I suspected there will be more in-depth concepts to work on.  I've replaced 1.21-dev-sync branch contents with 1.21-dev thereby undoing all the changes in this PR, which is probably best thing to do at this point considering the amount of work that would be needed to rework this PR.  I am not sure why it closed automatically, though 😕

**Comment by patricklodder** [comment]
Github doesn't support deletion of the branch the PR is based on - you can simply re-open a new PR, no probs.

**Pull request closed without merging**
