### PR TITLE
Trivial: Fix Magic Numbers in key and pubkey - fixes #1968

### LINKED ISSUE #1968: Fix magic numbers
Pubkey.cpp and Key.cpp contain 'magic numbers' mainly 33 and 65 representing the size for the signature (vch) COMPRESSED AND UNCOMPRESSED.

Suggest replaching these with constants for easier future maintaince

 static constexpr unsigned int SIZE                   = 65;
static constexpr unsigned int COMPRESSED_SIZE        = 33;

Also add a function that can verify the size

### PR DESCRIPTION
**Pull request by geekwisdom**
This is my proposed fix to the magic numbers in pubkey.h/cpp and key.h/cpp

Thanks.

### CODE REVIEW

**Comment by geekwisdom** [comment]
Hi - updated  the PR to make declaration of the constants in consistent (updated static in key.h to static constexpr unsigned int )

I believe I did use the new constant throughout key.cpp and pubkey.cpp. If I missed some i'm not seeing it sorry.

**Comment by patricklodder** [comment]
closing & reopening because travis is stuck

**Comment by rnicoll** [comment]
Can you rebase please to remoev conflicts? Try:

git fetch origin
git rebase -i origin/1.14.4-dev

It will then bring up an editor. If you remove the first 2 commits before yours. Please check the result then force push it. Thank you!

**Comment by geekwisdom** [comment]
> Can you rebase please to remove conflicts? Try:
> 
> git fetch origin
> git rebase -i origin/1.14.4-dev
> 
> It will then bring up an editor. If you remove the first 2 commits before yours. Please check the result then force push it. Thank you!

I think I redid that correctly? - The rebase only showed me one commit that was not mine, I removed it and did git push -f origin fix_magic_numbers_1968. It told me everything was up to date.

As noted by a previous comment. These changes seem to already be in 1.21-dev. (as it is upstream in bitcoin), so if this change is causing problems, we can just close the PR)

**Comment by rnicoll** [comment]
Sorry, just saw this in my backlog - looks like it still has a rogue commit. Any objections if I just grab the branch, rebase and open a new PR with the commits?

**Comment by patricklodder** [comment]
> Any objections if I just grab the branch, rebase and open a new PR with the commits?

Can you do it against 1.21? No point in making changes like this on a leaf patch branch like 1.14.4?

**Comment by geekwisdom** [comment]
Okay by me. I am sorry if i mangled it

**Comment by rnicoll** [comment]
Turns out 0.21 has addressed the magic numbers itself, so this only makes sense for 1.14.

**Comment by patricklodder** [comment]
Merged with #2249

**Pull request closed without merging**
