### PR TITLE
Refresh checkpoints for 1.14.5

### PR DESCRIPTION
**Pull request by rnicoll**
Full reindex not yet done, will note here when completed, but opening for visibility.

### CODE REVIEW

**Comment by patricklodder** [comment]
CI has an issue with the p2p-policy test (has that about 1 in 8 runs so I'm looking into it) - have hit the re-run button.

**Comment by rnicoll** [comment]
Verified this syncs past the checkpoints on both test & mainnet

**Comment by patricklodder** [comment]
Hashes, timestamps and tx counts match. Waiting for another 1200 blocks on mainnet to be sure it won't get reversed. So far I have no chain tip forks around this across all nodes on mainnet, and only a single orphan on testnet.  Looking good so far.

**Review by patricklodder — APPROVED** [review]
* Mainnet checkpoint is on the active chain with > 1440 confirmations ✅
* There are no large chaintip forks surrounding the checkpoint (only single orphans) ✅
* Block timestamps and # txs match ✅

**Review by jesserobertesparza-sys — COMMENTED** [review]
Cash

**Pull request merged**
