### PR TITLE
trivial: a minor fix in Chinese translation and several styling fixes

### PR DESCRIPTION
**Pull request by creekhu**
This PR fixes 

1. a minor issue in Chinese translation - changing incorrect term `yi' zhi` to `一致` in Chinese
2. several styling fixes

### CODE REVIEW

**Comment by creekhu** [comment]
I'm a very Shiba Inu and Dogecoin lover, and it's my very first contribution to the community. Please let me know if there is anti-pattern against the contribution guide in this PR. Thanks!

**Comment by rnicoll** [comment]
I've switched the base to the 1.14.4-dev branch we're working on. Can you rebase please? Try:

```
git fetch origin
git rebase -i origin/1.14.4-dev
```

It will then bring up an editor. If you remove the 3 commits before the one you want. Please check the result then force push it, and it should just change the document.

Thanks.

**Comment by creekhu** [comment]
@rnicoll Updated. Please have another look.

**Review by rnicoll — APPROVED** [review]

**Comment by rnicoll** [comment]
Thank you!

**Pull request merged**
