### PR TITLE
Added simplified Chinese for the main README doc 

### PR DESCRIPTION
**Pull request by lynklody**
Add simplified Chinese for the main README doc (still under development).
I added a language selection bar in the original README file.
*Other languages are welcome too.

### CODE REVIEW

**Comment by lynklody** [comment]
Oh I see where the problem is now. My apologies that I was trying to merge the dev branch with master. What should I do instead? @Romiko

**Comment by angelcervantesa** [comment]
do we have a README doc for dogecoin_mexico?

**Comment by lynklody** [comment]
Not for the main doc, as far as I know. Please feel free to add one! @angelcervantesa

**Comment by angelcervantesa** [comment]
Got it, just making my rounds through this universe. Beautiful to say the least, but complex. Will start writing soon.

**Pull request closed without merging**
