### PR TITLE
locale: update languages that have no recent updates

### PR DESCRIPTION
**Pull request by patricklodder**
Updates all the remaining languages, but omits all unmaintained dialects unless there only is a dialect, to reduce maintenance pressure on translators.

Excluded language files and their alternatives:

- bg_BG -> bg
- ca@valencia and ca_ES -> ca
- el_GR -> el
- es_AR, es_CL, es_CO, es_DO, es_ES, es_MX, es_UY and es_VE -> es
- et_EE -> et
- fa_IR -> fa
- fr_CA and fr_FR -> fr
- ro_RO -> ro
- ru_RU -> ru
- tr_TR -> tr
- vi_VN -> vi
- zh and zh_HK -> zh_CN

If you're a translator and you want to work on a particular translation that I didn't update now, just let us know and we'll get that updated for you. 

PR 3 of 3.

### CODE REVIEW

**Comment by chromatic** [comment]
How did you generate these? I think I know, but I'd like to try to reproduce this before I finish my review.

**Comment by patricklodder** [comment]
> How did you generate these?

The ugly way 😂

```bash
for lang in `find src/qt/locale -name "bitcoin_*.ts" -printf "%f\n" | grep -v bitcoin_en.ts |sed 's/^bitcoin_//;s/.ts$//'`; do
    make -C src translate language=$lang
done
```

and then only `git add` those that we need (on top of #3010)

**Comment by chromatic** [comment]
Hm, how about `src/qt/locale/bitcoin_ur_PK.ts`? Everything else looks fine to me.

**Comment by patricklodder** [comment]
Adding that! Thanks!

**Comment by patricklodder** [comment]
Added `ur_PK`. Convenience link to compare [`095ae8d..2a0c36b`](https://github.com/dogecoin/dogecoin/compare/095ae8d..2a0c36b)

**Review by chromatic — APPROVED** [review]
Tested on 64-bit Linux. All tests pass, and results are confirmed. ACK.

Merging now per policy, as this has the urgent label.

**Comment by patricklodder** [comment]
@daank-c: That's be awesome.


Re: `fr_CA`
Currently, I have only updated `fr`, and not `fr_FR` or `fr_CA` because they aren't maintained at all and are years behind. The latter 2 also aren't existing on 1.21-dev, which means that for Bitcoin everyone defaulted to just `fr`. My recommendation is to follow that lead for now, and instead, at least for 1.14.6, make `fr` as good as we can.

If then there's a need for `_CA` because it differs much from `fr`, we can for next releases (1.14.7 and/or 1.21) work on the `_CA` and `_FR` ones, and take the then-awesome `fr` as a base. 

`bitcoin_fr.ts` currently has only 20 entries in need of attention - perhaps that can be done before the 13th (next week?)

Does that sound realistic? Let me know.

**Pull request merged**
