### PR TITLE
fixate v3 fork

### PR DESCRIPTION
**Pull request by patricklodder**
Fixate the version 3 softfork in chainparams.consensus and create checkpoints.

introduces 3 new consensus params:
- `nMinBlockVersion`: defines the minimum `block.nVersion` at a specific height
- `fEnforceDERSigs`: defines if DER signatures are enforced (BIP66)
- `fEnforceSerializedHeight`: defines if block height should be serialized into coinbase (BIP34)

Also removes calls to `IsSuperMajority()` in main.cpp with checks against the new consensus params, to save iterating over 2000 blocks all the time.

Checkpoints:
- 1032512 for mainnet fork
- 708121 for testnet fork
- 747620 on testnet because... it's a mess.

### CODE REVIEW

**Comment by rnicoll** [comment]
Seems to get stuck on testnet at 736473:

2016-01-08 21:54:06 UpdateTip: new best=9bef69ad7aeafe419af92c65eb7ed2f159a340c6f380afe584da28326999164a  height=736473  log2_work=43.552339  tx=1457723  date=2015-10-18 12:18:37 progress=0.984570  cache=58.1MiB(247728tx)
2016-01-08 21:54:06 Loaded 25585 blocks from external file in 93343ms
2016-01-08 21:54:06 Reindexing finished
2016-01-08 21:54:08 ERROR: ContextualCheckBlockHeader : rejected nVersion=2 block
2016-01-08 21:54:08 ERROR: invalid header received
2016-01-08 21:54:08 ProcessMessages(headers, 162003 bytes) FAILED peer=1
2016-01-08 21:54:23 keypool reserve 2

**Comment by rnicoll** [comment]
Syncs live fine though

**Comment by patricklodder** [comment]
@rnicoll re: testnet. I've seen this behavior before while synching 1.10 because of the huge fork there. I'll try to reproduce over the weekend and if I can I have a good test scenario for [`-strictprotoversion` flag](https://github.com/patricklodder/dogecoin/tree/1.10.1-strictprotoversion).

**Comment by patricklodder** [comment]
I've been unable to reproduce the issue with testnet sync, mine went all the way until 748268 (`d66de611d813db098fa44c1c2a6a3015d3752399c9e88c3d2ac446a2338a1ea0`) and is equal to my 1.10.0 miner. Might be because I only connected to 2 1.8.x nodes, and 3 1.10.0 during sync?

**Comment by rnicoll** [comment]
Confirmed, works fine with the node connected only to a 1.10 node.

**Pull request merged**
