### PR TITLE
[feat] Added ARMv8 SHA support 

### PR DESCRIPTION
**Pull request by edtubbs**
Implemented ARMv8 intrinsics for SHA-1 and SHA-256
Added configuration argument to enable support
Added experimental build to CI environment

### CODE REVIEW

**Comment by edtubbs** [comment]
There's indentation and comments to fix, I'm also planning on adding SHA-512 while it's still in draft.

**Comment by xanimo** [comment]
so i've failed the following test:
```
$ make check
Making check in src
make[1]: Entering directory '/home/x/source/repos/dogecoin/src'
make[2]: Entering directory '/home/x/source/repos/dogecoin/src'
make[3]: Entering directory '/home/x/source/repos/dogecoin'
make[3]: Leaving directory '/home/x/source/repos/dogecoin'
make  check-TESTS check-local
make[3]: Entering directory '/home/x/source/repos/dogecoin/src'
make[4]: Entering directory '/home/x/source/repos/dogecoin/src'
make[5]: Entering directory '/home/x/source/repos/dogecoin'
make[5]: Leaving directory '/home/x/source/repos/dogecoin'
../build-aux/test-driver: line 112: 119810 Illegal instruction     (core dumped) "$@" >> "$log_file" 2>&1
FAIL: test/test_dogecoin
============================================================================
Testsuite summary for Dogecoin Core 1.14.5
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/dogecoin/dogecoin/issues
============================================================================
make[4]: *** [Makefile:10009: test-suite.log] Error 1
make[4]: Leaving directory '/home/x/source/repos/dogecoin/src'
make[3]: *** [Makefile:10117: check-TESTS] Error 2
make[3]: Leaving directory '/home/x/source/repos/dogecoin/src'
make[2]: *** [Makefile:10222: check-am] Error 2
make[2]: Leaving directory '/home/x/source/repos/dogecoin/src'
make[1]: *** [Makefile:9901: check-recursive] Error 1
make[1]: Leaving directory '/home/x/source/repos/dogecoin/src'
make: *** [Makefile:690: check-recursive] Error 1
```
 need to try compiling again as simple as possible but i encountered the preceding error after making depends using:
```
make NO_QT=1 HOST=aarch64-linux-gnu -C depends && \
./autogen.sh && \
CONFIG_SITE="${PWD}/depends/aarch64-linux-gnu/share/config.site" ./configure \
  --without-gui \
  --disable-gui-tests \ 
  --disable-ccache \
  --enable-debug \
  --with-armv8-crypto \
  CFLAGS="-s -static --static -fPIC" \
  CXXFLAGS="-DDEBUG_LOCKORDER -g" \
  LDFLAGS="-s -static-libgcc -static-libstdc++ -Wl,-O2" && \
  make -j$(nproc) && \
  make check
```

running on 64-bit ubuntu desktop 21.10 (RPI 4/400):
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1500.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

will try again and let you know how it goes :)

**Comment by edtubbs** [comment]
I discussed this with @michilumin and she's agreed to test on ODROID.  We'll post the results here when once they're available.

**Comment by patricklodder** [comment]
@edtubbs after I changed base branch in the am it looks like this went loco with conflicts. It should be easily cleared with a rebase off 1.14.6-dev though, because the first commit is a merge-back and I think this is causing the issue.

**Pull request closed without merging**
