### PR TITLE
1.21 auxpow header

### PR DESCRIPTION
**Pull request by rnicoll**
Add data type to hold a merge-mined header from another blockchain, along with details of how to prove the merge-mined header is intended for the Dogecoin chain.

### CODE REVIEW

**Review by patricklodder — COMMENTED** [review]
`src/test/auxpow_tests.cpp` is added here but is never compiled as it isn't added to the test suite. If I add it to `src/Makefile.test.include`, it errors out:

```
  CXX      test/test_dogecoin-auxpow_tests.o
test/auxpow_tests.cpp:14:10: fatal error: rpc/auxpow_miner.h: No such file or directory
   14 | #include <rpc/auxpow_miner.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by rnicoll** [comment]
AuxPoW tests shouldn't have been in this, it doesn't have enough functionality for them to run. Moved to the next PR.

**Review by patricklodder — COMMENTED** [review]
I think the `src/test` should go into your extracted commit with the tests. Everything else is fine. 

I did some more extensive testing on this (mostly: testing the upgrade) but this will currently purge all blocks past auxpow height (but no longer be much confuse about parsing the block files)

**Comment by rnicoll** [comment]
@patricklodder Removed the rest of the `src/test` changes and pushed

**Review by patricklodder — APPROVED** [review]
tested & code review ACK.

Unit & functional tests come with a later PR

PS: thanks for getting rid of most of that awkward Namecore formatting, it was hurting my eyes ❤️

**Pull request merged**
