### PR TITLE
Fix invalid settings in dogecoind.service

### PR DESCRIPTION
**Pull request by acerix**
Fix https://github.com/dogecoin/dogecoin/issues/3065

### CODE REVIEW

**Comment by patricklodder** [comment]
Thank you!

**Comment by patricklodder** [comment]
I'm taking a little more time to test this because none of my current build environments that have automation like the NAMESPACE configuration in the descriptor file - but working to create reproducible test script (that maybe can be integrated with the CI). 

I intend to manually test with a couple of clean kvm images later this weekend (because docker isn't a good platform to test systemd)

**Review by patricklodder — APPROVED** [review]
ACK. Tested on:
- x86_64 with Ubuntu 22.04
- x86_64 with archlinux
- aarch64 with Ubuntu 22.04

**Review by CryptoUnchained — COMMENTED** [review]
Ty

**Pull request merged**
