### PR TITLE
estimatefee / estimatepriority RPC methods

### PR DESCRIPTION
**Pull request by rnicoll**
Opening for discussion, DO NOT MERGE.

This is a rework of bitcoin/bitcoin#3959 for Dogecoin. The CFeeRate class changes introduce differences in how transaction fees are calculated, and I've intentionally let the unit tests for transaction fees break here. I'm looking for opinions on whether we should retain transaction fees as-is in Dogecoin (min 1 DOGE, no fine grain fees), or adopt the finer-grained TX fees that this patch introduces to Bitcoin Core.

Personally I favour staying as-is, but wanted to have others chip in. I'll then update the unit tests to match, make code changes as required, and finish testing.

### CODE REVIEW

**Comment by rnicoll** [comment]
bitcoin/bitcoin#4314 is also relevant here, and I'll try to merge it into this PR once we have a decision

**Comment by rnicoll** [comment]
In hindsight, actually, I think lets keep the 1 DOGE min fee for _all_ transactions (remove the free section), but otherwise I quite like the improved granularity on TX fees.

**Comment by langerhans** [comment]
Agree with keeping our current fee structure. It works the way it does. Also it's easy enought to write down into one sentence ;) And no free transactions was introduced now a whole while ago already and seing the value of 1 DOGE it's a non-issue I think.  
(Although sending free transactions is till possible, but psst ;D )

**Comment by patricklodder** [comment]
Can we keep this one open for a little so I can do some investigation if this could help solve our growing "utxo problem"?

**Comment by langerhans** [comment]
@patricklodder Sure, no rush with merging it.

**Comment by patricklodder** [comment]
Ok, so I gave this some thought and basically this change would give us 2 issues:

1. We'll probably have to change dust rules if we want this because this will break up more outputs into  fractional `COIN` value. Do we want to change dust rules? I'd personally be happy not to.
2. This will potentially make utxo even smaller and with that grow in volume. I think we're already in need (somewhat, not desperately) of alternative "input selection" policies, like a fifo policy and a smallest-first policy, on top of the current policy. However, the latter would not be used unless we give people that actively consolidate their utxo an incentive (like a tax-break.) which is a really big subject to discuss and I was planning to put all that in a DIP so we can actually discuss this :)

As for the fee calculation engine proposed here, I really like straight-forward fees as we (kind-of, miners still check coin-age to decide on priority, iirc) have now. `(ceil(bytes.size()/1000) + nSmallOuts)* COIN` is nice, and simple :)

PS: #4305 and #4314 are related to this too.

**Comment by rnicoll** [comment]
Full resync in progress to verify, however this should now behave as expected.

**Comment by rnicoll** [comment]
Think Travis is having hiccups running two tests in parallel, rather than actual problems.

**Comment by langerhans** [comment]
Below from trying this on testnet. Looks kinda odd to me. Maybe it is different on mainnet?  
Feel calculation seems good tho.

image

**Comment by rnicoll** [comment]
The "-1" is not enough information. Syncing on live now to see if it stabilizes in time.

**Comment by rnicoll** [comment]
Estimates are accurate; they reflect expected cost per kb. Given we put a floor in of 1 DOGE, and most transactions are well below 1kb, this gives us estimates in the 3-5 DOGE/kb range for actual cost.

Could come back to this later to change fee calculations to be 1DOGE/kb with a 1 DOGE minimum, but then scaled as per BTC, and have the estimation code special-case 1DOGE fees. For now however, works as expected.

**Comment by rnicoll** [comment]
In fact moments after I write that, I think I have to revise to "Recommend we change calculation to 1 DOGE/kb with a 1 DOGE minimum", to move us closer to BTC calculations, so anything based on BTC maths is readily compatible.

**Comment by rnicoll** [comment]
There, tweaked estimation code to be closer. For some reason values are still high, though.

**Comment by langerhans** [comment]
What we should keep tho is our 1DOGE/ouput<1DOGE extra. Without that, spamming the blockchain would be too cheap...  
Anyway, new estimates look more sane to me, so merging this. Let's try to remmeber to revisit the genral fee structure later after we got the merging done?

**Pull request merged**
