### PR TITLE
univalue: update to latest version

### PR DESCRIPTION
**Pull request by patricklodder**
[Univalue](https://github.com/bitcoin-core/univalue-subtree) has seen a lot of fixes since the bitcoin 0.14 subtree squash and this hasn't been updated even though technically it's a dependency. This updates `src/univalue`'s source tree to the latest from the bitcoin-core repository, including it's API from version 1.0.2 to 1.0.4.

### Breaking changes within Univalue
- the `VOBJ::push_back(Pair(k,v))` construct has been replaced by `VOBJ::pushKV(k,v)`
- trailing whitespaces are removed from JSON output

Both breaking changes can be fixed with a simple search & replace script, so I used the current bitcoin/bitcoin method of doing `scripted-diff` commits, which can be automatically verified.

### Scripted diff checker

Since we don't have the automated verification script in the 1.14 branch yet, I backported that into `contrib/devtools` for now (1.21 has this script under `test/lint`). You can verify the scripted commits by running: 

```
contrib/devtools/commit-script-check.sh <commit or range>
```

where a single commit as argument will run down the entire tree from that commit to the root commit, and a range, such as `1.14.5-dev..HEAD`, will only check all the commits between the two refs given, i.e. between the tip of that branch and `HEAD`.

This should make the review of this PR, and future scripted commits, significantly easier.

### CODE REVIEW

**Comment by rnicoll** [comment]
Err... which repo did you find used `1.0.4`? Bitcoin Core v22 seems to be on `1.0.3` still? https://github.com/bitcoin/bitcoin/blob/master/src/univalue/configure.ac

Mostly are we really sure we want to go to 1.0.4?

**Comment by patricklodder** [comment]
> Err... which repo did you find used 1.0.4?

We are, maybe 🤔

> Mostly are we really sure we want to go to 1.0.4?

I've reviewed the changes made on the source tree and they look good. This doesn't have to be critical path for 1.14.5 though - I'd be happy to re-target this towards 1.14.6 and leave it for now, give it a chance to get some more test exposure in bitcoin's master.

**Comment by rnicoll** [comment]
Okay, as long as we're aware we're precendent-setting.

I think all looks good, and honestly the RPC test suite does a lot better job of testing this than anything else is likely to. I want to take another look tomorrow before ACKing, though.

**Comment by patricklodder** [comment]
> I think all looks good, and honestly the RPC test suite does a lot better job of testing this than anything else is likely to. I want to take another look tomorrow before ACKing, though.

Of course. I'm also totally fine to require 2 ACKs on this and get more eyes on it. Like I said there's no rush for this change, so if it takes more time then we simply take more time and shift it. I do think it should be done at some point though, because the version we have right now is from 2016 and there have been some relevant fixes. I can also sync up with 1.21's commit if that makes you more comfortable.

**Comment by rnicoll** [comment]
Curiously was thinking the other direction - throw this into 1.21 as well, see what its test suite (which is a lot bigger) makes of it.

**Pull request merged**
