### PR TITLE
depends: expat 2.5.0

### PR DESCRIPTION
**Pull request by sinetek**
see #3266 for information on this.

### CODE REVIEW

**Comment by MargauxSpana** [comment]
eee

**Comment by chromatic** [comment]
@patricklodder I don't mind rebasing this (and maintaining credit for @sinetek). That means you or Michi will have to be the final reviewer. Will that work?

**Comment by patricklodder** [comment]
> Will that work?

Absolutely!

**Review by patricklodder — COMMENTED** [review]
code review ACK & tested this on x86_64 Focal. Should perform a gitian check to be sure.

**Comment by patricklodder** [comment]
shasums from gitian-LXC:

```
8ed913ecd8e2edc69561617cfceaab8ae055f961d3f62940772d17b6a3c3136c  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
a9b197fbf4ac39b2fe55b416c4eb05123818976334c1ec872cd5baf955489435  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
40b6c77d302a1ae386701ffd36e78f622a2b5f86628a489227adb1e36a263933  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
e04cd0e10284af913c3495f3983026c9c53f29045457166c56143d5a59499aed  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
275ecc9886c612bb9b85d35a1941e27b1257c170adcf51e9df40e0d3cb18fd60  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
16b27a22b1a676687e1ada9c50778f60f891b89e0a022783e745a3393aa15ecc  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
4eac8520595bb7ea695c07acc0c70c39dcc7885d6799031a7946c60c13dd21fd  dogecoin-1.14.7-osx-unsigned.dmg
f9c05915533bc4cf901d7863a88fc0f6421be22d3da1ce672e8a9b211929621f  dogecoin-1.14.7-osx-unsigned.tar.gz
3a3442476399f979e72c03e034f428670d165a1ff110f429fb2ce768c7bd3a8c  dogecoin-1.14.7-osx64.tar.gz
ef86cda3b783d04c599f8f765f73cb08e5a2dfbf8bcb07bf01c93759098d184d  dogecoin-1.14.7-win-unsigned.tar.gz
89274c961c59f393a3a8a2a6efcadcc0b2f037bf35ac778d9947fcd100e24127  dogecoin-1.14.7-win32-debug.zip
4e6b6a0c4910a991cb5401b11ff341595d0e35af015f20af3b6a9ad7ace6e0d0  dogecoin-1.14.7-win32-setup-unsigned.exe
7deeadc760a1877dd03656d24d5d5f57c5e32f8cb42002c727dda7e341d7d79b  dogecoin-1.14.7-win32.zip
42c313d8604271da9773735aa8bec0c24b3042ed854092135b25109d888cbd92  dogecoin-1.14.7-win64-debug.zip
29a88cc84d5d1cc4a5932b6f8c441070174aa5b6b8d36fbce4b332ba035708a4  dogecoin-1.14.7-win64-setup-unsigned.exe
f7eafe429ac011b5e2b1a8b3491d51cd08da53535ac39e418d698c2125fe439f  dogecoin-1.14.7-win64.zip
2393c499b132dbc09c265dd5cd598815d0038fd10eb7ea3df772a5296229ec7f  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
e56736b988937e570ee1b54c0ce57aa36770f6570f0127b1f9079f8e39dfa4a1  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
34df9fe07d3bd9d6e376d8e068652582a35fcfa7ac8743905a512937be7276d5  dogecoin-1.14.7.tar.gz
```

**Comment by xanimo** [comment]
here are my results from docker:
```
8ed913ecd8e2edc69561617cfceaab8ae055f961d3f62940772d17b6a3c3136c  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
a9b197fbf4ac39b2fe55b416c4eb05123818976334c1ec872cd5baf955489435  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
40b6c77d302a1ae386701ffd36e78f622a2b5f86628a489227adb1e36a263933  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
e04cd0e10284af913c3495f3983026c9c53f29045457166c56143d5a59499aed  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
275ecc9886c612bb9b85d35a1941e27b1257c170adcf51e9df40e0d3cb18fd60  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
16b27a22b1a676687e1ada9c50778f60f891b89e0a022783e745a3393aa15ecc  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
2393c499b132dbc09c265dd5cd598815d0038fd10eb7ea3df772a5296229ec7f  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
e56736b988937e570ee1b54c0ce57aa36770f6570f0127b1f9079f8e39dfa4a1  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
ef86cda3b783d04c599f8f765f73cb08e5a2dfbf8bcb07bf01c93759098d184d  dogecoin-1.14.7-win-unsigned.tar.gz
89274c961c59f393a3a8a2a6efcadcc0b2f037bf35ac778d9947fcd100e24127  dogecoin-1.14.7-win32-debug.zip
4e6b6a0c4910a991cb5401b11ff341595d0e35af015f20af3b6a9ad7ace6e0d0  dogecoin-1.14.7-win32-setup-unsigned.exe
7deeadc760a1877dd03656d24d5d5f57c5e32f8cb42002c727dda7e341d7d79b  dogecoin-1.14.7-win32.zip
42c313d8604271da9773735aa8bec0c24b3042ed854092135b25109d888cbd92  dogecoin-1.14.7-win64-debug.zip
29a88cc84d5d1cc4a5932b6f8c441070174aa5b6b8d36fbce4b332ba035708a4  dogecoin-1.14.7-win64-setup-unsigned.exe
f7eafe429ac011b5e2b1a8b3491d51cd08da53535ac39e418d698c2125fe439f  dogecoin-1.14.7-win64.zip
4eac8520595bb7ea695c07acc0c70c39dcc7885d6799031a7946c60c13dd21fd  dogecoin-1.14.7-osx-unsigned.dmg
f9c05915533bc4cf901d7863a88fc0f6421be22d3da1ce672e8a9b211929621f  dogecoin-1.14.7-osx-unsigned.tar.gz
3a3442476399f979e72c03e034f428670d165a1ff110f429fb2ce768c7bd3a8c  dogecoin-1.14.7-osx64.tar.gz
```

**Review by patricklodder — APPROVED** [review]
ACK - tested on focal x86_64 and gitian sums match

**Pull request merged**
