### PR TITLE
depends: updated to zlib 1.3

### PR DESCRIPTION
**Pull request by edtubbs**
Updated depends to current version of zlib.

### CODE REVIEW

**Comment by edtubbs** [comment]
No specific trigger, initially updated it due to the errors from depends.dogecoincore.org which have since been resolved.

**Comment by patricklodder** [comment]
@edtubbs could you please rebase this on top of 727e6f11 so that we can do the gitian check inclusive of the protobuf change? Thanks!

**Comment by xanimo** [comment]
```
bd3c12611b382a01164a28166eb06f612620d1e9f9ebe42c4fff647e87663e1f  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
2c02930933e0d828ba4234736ba40c1ca91dcb213843970cf3a035705ba7741a  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
f249d32d4dbc0376ed09c09102f8123085e80963dc0f7239fe80c2611c6f96f7  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
8cf1da164cc1fc91f321ddf77d0e4c01fc0fe8a35e1076e3b6cb96fef24faeb8  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
e61acfa2a2f680466cc12f6116016dc99f31e52e05ba6f60426b3dfdadd7fe62  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
491ec981a33bc5792b6ac9b0fd73f2ef7ec0bc8fc61b57b9875eda1cc7d73da2  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
96529a3671f9139c63961b4382635c23570e819a9d1da926d5bd99fe76deeb0d  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
529e17ca5726663d2b6972586315a8098f67d8bdab71f5e1e16586012b6b4598  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
e97800d714edcbbdb2e8b36de1168a4712fbdebd2e321575e1ae0e35d97e7100  dogecoin-1.14.7-win-unsigned.tar.gz
c99261e1571753ee2eba29dcb0a963ee088556bb5aafdeae2d323892609da721  dogecoin-1.14.7-win32-debug.zip
fb1d250948e25a1026e7a15b5c3dc6baa291985fcf39ae2d8dee28e293e8394e  dogecoin-1.14.7-win32-setup-unsigned.exe
74a50af20479ca61ccdd7c45bb5a0934241fcea2c918e84f43dd67dc1cca3515  dogecoin-1.14.7-win32.zip
8ce00ae47538e868902cd6f83ca8328ab0654f757b27db5343d5e7c2a87f1567  dogecoin-1.14.7-win64-debug.zip
411e4157d3aa137dd73ddf375d14c9edcef33330c4dd63fe27abd65885b4fdf4  dogecoin-1.14.7-win64-setup-unsigned.exe
19b512e8719cfa49ab980cb75cca530ac76feca3c9e6ff386e77052b190760f1  dogecoin-1.14.7-win64.zip
bc4ac8b04cee670275bd30626de963ff1ae4596efe577605e75d88245a5c0eda  dogecoin-1.14.7-osx-unsigned.dmg
ce46cec7182a7db7c85970b250d3f480931e58ba3457ed49f0013377974b0ab0  dogecoin-1.14.7-osx-unsigned.tar.gz
42f39ad079a67780343a2a2145bf51b1dbe9b13469d9b7dfedc74881f385f8bd  dogecoin-1.14.7-osx64.tar.gz
```

**Comment by chromatic** [comment]
Hmm, so far I have different checksums. Do you still have the tarball checksum?

```
fb71042bcbd22ff7d718543e2b488df62ba942b5813c3a73e7347fe3988cd099  dogecoin-1.14.7-osx-unsigned.dmg
a7036963518422458d42c557844b1cc15804b98d87caa78fe83b9aac8866cdcb  dogecoin-1.14.7-osx-unsigned.tar.gz
85cd5e91fca4665b1606d87aa54e10804c5118f0bc4a4a9dee2305c25d7aa74d  dogecoin-1.14.7-osx64.tar.gz
dde946511f5d66be25bf9e643ea056ad73914372732898c2831beddb02f3830a  src/dogecoin-1.14.7.tar.gz
3afafc690452848756afd137fbb0d6f908d93c62f758e26fd4f3ba6849b61306  dogecoin-osx-1.14-res.yml
```

**Comment by xanimo** [comment]
ruh roh. ermm i'll run it again this evening but do you mean the .yml file? otherwise not sure.

**Comment by xanimo** [comment]
i think so, let me try to find it rq.

**Comment by xanimo** [comment]
yeah it's mismatched :( not sure why but i'll run it again this evening. are you building with lxc or docker btw?
```
3937f1d90e962efb9064f2ddf54446301eb282f73eb488a1ce0d2914e64844bc  src/dogecoin-1.14.7.tar.gz
```

**Comment by chromatic** [comment]
I ran this command:

```
$ bash contrib/gitian-build-test.sh -b --docker -u https://github.com/patricklodder/dogecoin/ -c 1.14.7-reduce-qt
```

How about you?

**Comment by xanimo** [comment]
oh think you are building https://github.com/dogecoin/dogecoin/pull/3358? i am using a custom [script](https://gist.github.com/xanimo/e479f3eff5797b37ae01cfef3135bc11) that i modified but the command i used was similar, just using eds repo:
```
./build.sh --mem=16000 --proc=4 --commit=3d7395284d1d3209834c602e74f933efd00d8ee6 --url=https://github.com/edtubbs/dogecoin --docker
```

**Comment by xanimo** [comment]
i have same hashes in #3358 with what you have so far :+1:

**Comment by chromatic** [comment]
Well that explains it. I'll move my build fingerprints over to the correct PR and see if I can reproduce yours on this commit. :facepalm:

**Comment by xanimo** [comment]
sounds good :) and no worries.

**Comment by patricklodder** [comment]
LXC gitian shasums, these match with @xanimo:

```
bd3c12611b382a01164a28166eb06f612620d1e9f9ebe42c4fff647e87663e1f  dogecoin-1.14.7-aarch64-linux-gnu-debug.tar.gz
2c02930933e0d828ba4234736ba40c1ca91dcb213843970cf3a035705ba7741a  dogecoin-1.14.7-aarch64-linux-gnu.tar.gz
f249d32d4dbc0376ed09c09102f8123085e80963dc0f7239fe80c2611c6f96f7  dogecoin-1.14.7-arm-linux-gnueabihf-debug.tar.gz
8cf1da164cc1fc91f321ddf77d0e4c01fc0fe8a35e1076e3b6cb96fef24faeb8  dogecoin-1.14.7-arm-linux-gnueabihf.tar.gz
e61acfa2a2f680466cc12f6116016dc99f31e52e05ba6f60426b3dfdadd7fe62  dogecoin-1.14.7-i686-pc-linux-gnu-debug.tar.gz
491ec981a33bc5792b6ac9b0fd73f2ef7ec0bc8fc61b57b9875eda1cc7d73da2  dogecoin-1.14.7-i686-pc-linux-gnu.tar.gz
42f39ad079a67780343a2a2145bf51b1dbe9b13469d9b7dfedc74881f385f8bd  dogecoin-1.14.7-osx64.tar.gz
bc4ac8b04cee670275bd30626de963ff1ae4596efe577605e75d88245a5c0eda  dogecoin-1.14.7-osx-unsigned.dmg
ce46cec7182a7db7c85970b250d3f480931e58ba3457ed49f0013377974b0ab0  dogecoin-1.14.7-osx-unsigned.tar.gz
3937f1d90e962efb9064f2ddf54446301eb282f73eb488a1ce0d2914e64844bc  dogecoin-1.14.7.tar.gz
c99261e1571753ee2eba29dcb0a963ee088556bb5aafdeae2d323892609da721  dogecoin-1.14.7-win32-debug.zip
fb1d250948e25a1026e7a15b5c3dc6baa291985fcf39ae2d8dee28e293e8394e  dogecoin-1.14.7-win32-setup-unsigned.exe
74a50af20479ca61ccdd7c45bb5a0934241fcea2c918e84f43dd67dc1cca3515  dogecoin-1.14.7-win32.zip
8ce00ae47538e868902cd6f83ca8328ab0654f757b27db5343d5e7c2a87f1567  dogecoin-1.14.7-win64-debug.zip
411e4157d3aa137dd73ddf375d14c9edcef33330c4dd63fe27abd65885b4fdf4  dogecoin-1.14.7-win64-setup-unsigned.exe
19b512e8719cfa49ab980cb75cca530ac76feca3c9e6ff386e77052b190760f1  dogecoin-1.14.7-win64.zip
e97800d714edcbbdb2e8b36de1168a4712fbdebd2e321575e1ae0e35d97e7100  dogecoin-1.14.7-win-unsigned.tar.gz
96529a3671f9139c63961b4382635c23570e819a9d1da926d5bd99fe76deeb0d  dogecoin-1.14.7-x86_64-linux-gnu-debug.tar.gz
529e17ca5726663d2b6972586315a8098f67d8bdab71f5e1e16586012b6b4598  dogecoin-1.14.7-x86_64-linux-gnu.tar.gz
```

**Review by patricklodder — APPROVED** [review]
ACK, tested on x86_64 Ubuntu Jammy and Gitian match

**Pull request merged**
