### PR TITLE
Update build-unix.md

### PR DESCRIPTION
**Pull request by alfariqicrypto**
combine command. to make it easier when copying scrypt. remove the other sudo. only 1 is enough

### CODE REVIEW

**Review by AbcSxyZ — CHANGES_REQUESTED** [review]
We may also add slashes to avoid long lines, which is also less convenient for copy pasting.

Do you think it could be great to also do the following ? :
```
sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev \
    bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev \
    libboost-test-dev libboost-thread-dev
```
It's possible to do the same for all code blocks where there is a scrolling bar, in `optionnaly dependecy` section & ARM-Cross compilation

**Comment by alfariqicrypto** [comment]
o... its great... i love dogecoin

**Comment by AbcSxyZ** [comment]
You could add the change rather than closing the PR :)

**Comment by alfariqicrypto** [comment]
okay

**Pull request closed without merging**
