### PR TITLE
Merge nMajority* values with Bitcoin Core parameters

### PR DESCRIPTION
**Pull request by rnicoll**
In Bitcoin Core the nMajority values were renamed to `nMinerConfirmationWindow` and
`nRuleChangeActivationThreshold`, while in Dogecoin Core we'd ended up with both.
Merge the values into a single coherent whole.

### CODE REVIEW

**Comment by rnicoll** [comment]
Verified by resyncing full testnet, no issues.

**Comment by patricklodder** [comment]
retriggering CI

**Comment by patricklodder** [comment]
According to [linux CI](https://travis-ci.com/github/dogecoin/dogecoin/jobs/506673504#L2134), there is a regression in `versionbits_tests`.

**Comment by rnicoll** [comment]
Note to self; in hindsight, probably better to rip out the supermajority code entirely and hard code the height of the v4 blocks starting.

**Comment by patricklodder** [comment]
We've already done the fixation with #1734. I kept the chain params and `IsSuperMajority()` because then we have a reference, even while there are no active softforks in this branch? The reason we agreed to do this change was because there were unused chainparams (apparently only in tests!?! which is bad!) that were confusing vs what was used for the v4 soft fork...

So I do not like the edit...

**Pull request closed without merging**
