### PR TITLE
depends: Update libevent to 2.1.11

### PR DESCRIPTION
**Pull request by rnicoll**
Tested locally with test and main nets, along with unit test suite. Going to push this to a long running node to soak before we merge, but raising so others are aware the work is done.

This is an item for #2321

### CODE REVIEW

**Comment by patricklodder** [comment]
needs gitian check

**Review by fmhc — APPROVED** [review]
checked checksums for fun as I'm reading into the open PRs and digging around in this space to find other dependency upgrades and how they are handled.

**Comment by rnicoll** [comment]
Built on Gitian and deployed on a production node, will see how it looks in a day.

**Comment by rnicoll** [comment]
Node didn't start, reported corrupted data on risk. Reindexing and hoping it's just bad luck.

**Comment by rnicoll** [comment]
Node fully synced. Shut it down and started it to verify there's no startup issue. I think this is okay to review now.

**Comment by rnicoll** [comment]
```
1.14.4-libevent$ sha256sum *.*
367451177b9e43afbd0b14bede46eb2447d68367670e372d06dcbd5cd6dd82de  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
825ab754b2eaf2943773231897b53328ecf5850d8286defee718b7b05f6278f9  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
11ecf3ca5030369aa157d5838f33279a4705ededcb7837fbbd1ba14e6d4551d1  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
e60989737a13ef5ab777bf2c22b1d7aad03b723b672f3e8d98347acd51422627  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
e8593dea762054529598f5faa4dda37e1d5bca0111c148e8e17e53608535149c  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
6029dc5e40080741f21272a34cb9d59c87a0955f7878d2ecc519f1e544ae8d55  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
ddf4d6f6b068cfdf0d018aba6ef4835f1886be5ae96f99034cfed407562ac4e8  dogecoin-1.14.4-osx64.tar.gz
c2b5eb63a6768cb5abc5842913d39cf462e26a72732b98fabf56e5b2e6dc26eb  dogecoin-1.14.4-osx-unsigned.dmg
a8dd6b44ca86ed7f629cf7c9504a1c58403cc62cd0ddc0559a8dfd77c1c28840  dogecoin-1.14.4.tar.gz
bd4e326dbb499278b74c6371d6101ba8e8fa8ffa9ae02cfab0ceb2f61d485df9  dogecoin-1.14.4-win32-debug.zip
6dc02c169dc277c6d86201afe5177b2ab73f81613aa06aae39f8d17709df66d3  dogecoin-1.14.4-win32-setup-unsigned.exe
ea8428e419b97ac307e928176337318ad3e30f124bef7b08efca273eb0eeaab3  dogecoin-1.14.4-win32.zip
2ec3534e14fce10732fe87c7542cf1c55013c1b73f40a4f98ddb395a8c7392d0  dogecoin-1.14.4-win64-debug.zip
9ce1b8e7d21786aa0834c97b07ce6d6a5cc124bd76d79dac2831da539b6f82c7  dogecoin-1.14.4-win64-setup-unsigned.exe
1ac182b7fd98af0c1d2b2c1267cd2b187f737e22cd307da5a58f0d7d02cc857a  dogecoin-1.14.4-win64.zip
8f296d4f7182c14b179c9933ab5f130f9b2dd5bb5dc180b0c6dc458051ed8e82  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
0b705085c53b71b4483cb8bc85bd339e59ec0f3cdae92602dd05be7b3764b59d  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Comment by micaelmalta** [comment]
@rnicoll I dont have the same signatures...

./gitian-build.sh -j 8 -m 8192 -u https://github.com/rnicoll/dogecoin --build --commit mmicael 1.14.4-libevent

```
3972b1c704cce22613b8d57d9d4a6e4d8d242620b136a76119ec0e8fb7ec8199  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
590c451dc845f94af5d5d24f672e04e32842706692d075a8e52e74591fbe06e3  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
6508dec980193f41530950d11e584f16a24402fb558e2f7ce42c91df77c76ca6  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
9076ddf7db0ca122fffb31bf50d30ddc8da8a3dd3f2cdfe0a212ef84754ce51b  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
25c3fac2e4772103ede0b6418b058e972156d5ad8511453e49bb7c77c181d503  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
743d05f049161ccaab86374b2bff506388ed20024576d588e1079db40fcaeff8  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
fb9ea919f5b512b57580e48e9bb6886606082432797ede43d7814f88faca4c75  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
568190f936d40289e0b956957404046b6d5ac846e17206add05d2cb276199cdb  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
61c920ae2b31211622a7179cd199f4f913babb7f610ca93b5eb3f8482d8b445c  dogecoin-1.14.4-win-unsigned.tar.gz
3a3ef7a41de7cd0fcfa16378ba5598a8aecc3853be06dcc9fa3ad10ae7b71947  dogecoin-1.14.4-win32-debug.zip
611bdb05ab6ca35e46e16928d680878f9d9b4b89bf4f3ad1998267228c887eae  dogecoin-1.14.4-win32-setup-unsigned.exe
8741c81c2f3dfa9ced27b95214ab055f52cc0e10dceb31ec4639e166e580ab99  dogecoin-1.14.4-win32.zip
4596afe518d8e3f9688bff19c015fe0ae6f31192cf45ce9aad2d4baf6e629de9  dogecoin-1.14.4-win64-debug.zip
ab854510479dae170848ad448c4415d90da7811a65408df0c6c6d7cf4014d0a8  dogecoin-1.14.4-win64-setup-unsigned.exe
4f83e3f82624b95fedcac8262052f0960b2d0bf3dea65f3edf02bd3dde32de51  dogecoin-1.14.4-win64.zip
451f5a50241c332d05db53c60f08182fbfd6c80f166ecf7579e9583d706e7c52  dogecoin-1.14.4-osx-unsigned.dmg
6f1b7498fe104dc8126ce77b604b8fcbfe2a7066f6dae21c7bca16f06772a600  dogecoin-1.14.4-osx-unsigned.tar.gz
a530c8e2e16fa5630f410daa8a89a0106e80cfa73c303bf2f6f31381fa9e6a22  dogecoin-1.14.4-osx64.tar.gz
c4629323a357fd5dbf144cb441505fd01502855908ccbbf11e02bed12be2f888  src/dogecoin-1.14.4.tar.gz
eca08ba588353c14a8fd1d576d7e8b2d0bf8666332b24512746ae51ac3978c31  dogecoin-osx-1.14-res.yml
```

**Comment by rnicoll** [comment]
Rebased and rebuilding

**Comment by rnicoll** [comment]
Okay with the rebase, running `./dogecoin/contrib/gitian-build.sh -b jrn@jrn.me.uk 1.14.4-libevent` I now get:

```
$ sha256sum *
1e5d352c888cf3523647e1da958a4799812f8d3d3a6c7b5db7d3676e5b33bfcc  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
759258dfd0a17e82631ad38178e3e51b97131f72eb3ad689dcbc0563973ac51e  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
455a11db713110b18969a3e9a306e2629c159b8a5dd909603761371b634dc5ef  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
4df5598994d3085e77dfdbf656b0cec22e4cfd01b1742b4d29da041cd951e1a5  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
757add83129500ab880a27fa4ee6c4451f4f5ab7cc30f27e57e1e58e91cfd89a  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
9ee5cf4a48052e1a036a78d748eef704ed8781df4b9edc5dc040847820cd73a2  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
3eb87bd7dc4d3459d97c42fdfd6abb8bf9fac4653485c8dcfd7d7fbd6602310e  dogecoin-1.14.4-osx64.tar.gz
430c1c1337e3e0d748775ece20cf61393051dd8f3bc9e364913bbb9bc3b6420e  dogecoin-1.14.4-osx-unsigned.dmg
efd14d570151a95061b8986e8c2105ef591f0aaca88ad39e87571b294dfe40ad  dogecoin-1.14.4.tar.gz
a7282bf56d2b99ad605b679ec859ba610d7d752359976254862b93bab2e8c18d  dogecoin-1.14.4-win32-debug.zip
9cce15f7aae5b58e5f991ab964e0d3f4ca4fe12b08289fe4eb1ae6926f68a4a5  dogecoin-1.14.4-win32-setup-unsigned.exe
f3c84b9a8532c2969631bb185f5f4cfc2e37dfd8c6784f49d324d196908ad7c3  dogecoin-1.14.4-win32.zip
1180a813ecfa1fd8098656c4b54004a13d113a1c0194c9e8517b3996ded49874  dogecoin-1.14.4-win64-debug.zip
b6884a36a53c2b8ecbb0242b274be1fc7b8295c16a8d2fed6bfc938695c4fd96  dogecoin-1.14.4-win64-setup-unsigned.exe
bbf99d690b33ba61fec45fe0c60de8769f530dc7181ee02e3934813bac5af073  dogecoin-1.14.4-win64.zip
7edbe96093100adb9b6ee705cfe5b2599444b5d54de2c4c498344418736504d7  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
e2d8abcd61f73efb40f21ed371aa9e206a0fbd23f8286855b6a3b2b1970ed456  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Comment by micaelmalta** [comment]
./gitian-build.sh -j 8 -m 8192 -u https://github.com/rnicoll/dogecoin --build --commit mmicael 1.14.4-libevent

```
1e5d352c888cf3523647e1da958a4799812f8d3d3a6c7b5db7d3676e5b33bfcc  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
759258dfd0a17e82631ad38178e3e51b97131f72eb3ad689dcbc0563973ac51e  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
455a11db713110b18969a3e9a306e2629c159b8a5dd909603761371b634dc5ef  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
4df5598994d3085e77dfdbf656b0cec22e4cfd01b1742b4d29da041cd951e1a5  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
757add83129500ab880a27fa4ee6c4451f4f5ab7cc30f27e57e1e58e91cfd89a  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
9ee5cf4a48052e1a036a78d748eef704ed8781df4b9edc5dc040847820cd73a2  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
7edbe96093100adb9b6ee705cfe5b2599444b5d54de2c4c498344418736504d7  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
e2d8abcd61f73efb40f21ed371aa9e206a0fbd23f8286855b6a3b2b1970ed456  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
fd23c210f586999264dd00d569ce0d2b2594f602c331f566fa004f30811ac421  dogecoin-1.14.4-win-unsigned.tar.gz
a7282bf56d2b99ad605b679ec859ba610d7d752359976254862b93bab2e8c18d  dogecoin-1.14.4-win32-debug.zip
9cce15f7aae5b58e5f991ab964e0d3f4ca4fe12b08289fe4eb1ae6926f68a4a5  dogecoin-1.14.4-win32-setup-unsigned.exe
f3c84b9a8532c2969631bb185f5f4cfc2e37dfd8c6784f49d324d196908ad7c3  dogecoin-1.14.4-win32.zip
1180a813ecfa1fd8098656c4b54004a13d113a1c0194c9e8517b3996ded49874  dogecoin-1.14.4-win64-debug.zip
b6884a36a53c2b8ecbb0242b274be1fc7b8295c16a8d2fed6bfc938695c4fd96  dogecoin-1.14.4-win64-setup-unsigned.exe
bbf99d690b33ba61fec45fe0c60de8769f530dc7181ee02e3934813bac5af073  dogecoin-1.14.4-win64.zip
efd14d570151a95061b8986e8c2105ef591f0aaca88ad39e87571b294dfe40ad  src/dogecoin-1.14.4.tar.gz
acdd3e99906abbb8914a2946cb4cd519bd54a13d6e795632c4c5fd4c5dbf95d5  dogecoin-win-res.yml
430c1c1337e3e0d748775ece20cf61393051dd8f3bc9e364913bbb9bc3b6420e  dogecoin-1.14.4-osx-unsigned.dmg
5973e441e550db359a4517bbda774ebc7dda59532838e631c619571b87487471  dogecoin-1.14.4-osx-unsigned.tar.gz
3eb87bd7dc4d3459d97c42fdfd6abb8bf9fac4653485c8dcfd7d7fbd6602310e  dogecoin-1.14.4-osx64.tar.gz
efd14d570151a95061b8986e8c2105ef591f0aaca88ad39e87571b294dfe40ad  src/dogecoin-1.14.4.tar.gz
d1829746cd0566a60c74b997781ac7b385d0bec93057ea9e420191e0b79884d9  dogecoin-osx-res.yml
```

**Comment by micaelmalta** [comment]
GITIAN CIRRUS: https://cirrus-ci.com/build/4704793919750144

```
1e5d352c888cf3523647e1da958a4799812f8d3d3a6c7b5db7d3676e5b33bfcc  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
759258dfd0a17e82631ad38178e3e51b97131f72eb3ad689dcbc0563973ac51e  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
455a11db713110b18969a3e9a306e2629c159b8a5dd909603761371b634dc5ef  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
4df5598994d3085e77dfdbf656b0cec22e4cfd01b1742b4d29da041cd951e1a5  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
757add83129500ab880a27fa4ee6c4451f4f5ab7cc30f27e57e1e58e91cfd89a  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
9ee5cf4a48052e1a036a78d748eef704ed8781df4b9edc5dc040847820cd73a2  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
3eb87bd7dc4d3459d97c42fdfd6abb8bf9fac4653485c8dcfd7d7fbd6602310e  dogecoin-1.14.4-osx64.tar.gz
5973e441e550db359a4517bbda774ebc7dda59532838e631c619571b87487471  dogecoin-1.14.4-osx-unsigned.tar.gz
efd14d570151a95061b8986e8c2105ef591f0aaca88ad39e87571b294dfe40ad  dogecoin-1.14.4.tar.gz
a7282bf56d2b99ad605b679ec859ba610d7d752359976254862b93bab2e8c18d  dogecoin-1.14.4-win32-debug.zip
9cce15f7aae5b58e5f991ab964e0d3f4ca4fe12b08289fe4eb1ae6926f68a4a5  dogecoin-1.14.4-win32-setup-unsigned.exe
f3c84b9a8532c2969631bb185f5f4cfc2e37dfd8c6784f49d324d196908ad7c3  dogecoin-1.14.4-win32.zip
1180a813ecfa1fd8098656c4b54004a13d113a1c0194c9e8517b3996ded49874  dogecoin-1.14.4-win64-debug.zip
b6884a36a53c2b8ecbb0242b274be1fc7b8295c16a8d2fed6bfc938695c4fd96  dogecoin-1.14.4-win64-setup-unsigned.exe
bbf99d690b33ba61fec45fe0c60de8769f530dc7181ee02e3934813bac5af073  dogecoin-1.14.4-win64.zip
fd23c210f586999264dd00d569ce0d2b2594f602c331f566fa004f30811ac421  dogecoin-1.14.4-win-unsigned.tar.gz
7edbe96093100adb9b6ee705cfe5b2599444b5d54de2c4c498344418736504d7  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
e2d8abcd61f73efb40f21ed371aa9e206a0fbd23f8286855b6a3b2b1970ed456  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Comment by patricklodder** [comment]
The binary artifact from GH Actions is making me reindex my `Dogecoin-Qt -testnet -txindex` install - investigating whether this is caused by the CI build or with the libevent change.

**Comment by rnicoll** [comment]
Tested the Gitian build on my local machine and it loaded testnet fine. My mainnet is a mess, so reindexing that anyway to verify it.

**Comment by patricklodder** [comment]
Reindex trigger was a local issue. Running it once more to make 100% sure, after re-reindexing w/ 1.14.3

**Comment by patricklodder** [comment]
gitian sigs confirmed

```
1e5d352c888cf3523647e1da958a4799812f8d3d3a6c7b5db7d3676e5b33bfcc  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
759258dfd0a17e82631ad38178e3e51b97131f72eb3ad689dcbc0563973ac51e  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
455a11db713110b18969a3e9a306e2629c159b8a5dd909603761371b634dc5ef  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
4df5598994d3085e77dfdbf656b0cec22e4cfd01b1742b4d29da041cd951e1a5  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
757add83129500ab880a27fa4ee6c4451f4f5ab7cc30f27e57e1e58e91cfd89a  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
9ee5cf4a48052e1a036a78d748eef704ed8781df4b9edc5dc040847820cd73a2  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
430c1c1337e3e0d748775ece20cf61393051dd8f3bc9e364913bbb9bc3b6420e  dogecoin-1.14.4-osx-unsigned.dmg
5973e441e550db359a4517bbda774ebc7dda59532838e631c619571b87487471  dogecoin-1.14.4-osx-unsigned.tar.gz
3eb87bd7dc4d3459d97c42fdfd6abb8bf9fac4653485c8dcfd7d7fbd6602310e  dogecoin-1.14.4-osx64.tar.gz
a7282bf56d2b99ad605b679ec859ba610d7d752359976254862b93bab2e8c18d  dogecoin-1.14.4-win32-debug.zip
f3c84b9a8532c2969631bb185f5f4cfc2e37dfd8c6784f49d324d196908ad7c3  dogecoin-1.14.4-win32.zip
1180a813ecfa1fd8098656c4b54004a13d113a1c0194c9e8517b3996ded49874  dogecoin-1.14.4-win64-debug.zip
bbf99d690b33ba61fec45fe0c60de8769f530dc7181ee02e3934813bac5af073  dogecoin-1.14.4-win64.zip
7edbe96093100adb9b6ee705cfe5b2599444b5d54de2c4c498344418736504d7  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
e2d8abcd61f73efb40f21ed371aa9e206a0fbd23f8286855b6a3b2b1970ed456  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Review by patricklodder — APPROVED** [review]
ACK

**Pull request merged**
