### PR TITLE
Change Bitcoin to Dogecoin in qa/ files

### PR DESCRIPTION
**Pull request by chromatic**
This changes all occurrences of `BITCOIN` to `DOGECOIN` and `bitcoind` to `dogecoind` in all files in `qa/`. It does not change copyright information.

See comments in #3327 ; we discussed doing this in a major release.

### CODE REVIEW

**Comment by patricklodder** [comment]
concept is okay with me.

**Comment by patricklodder** [comment]
> I think maybe it was the issue noted at https://github.com/dogecoin/dogecoin/issues/3464.

correct.

**Comment by georgeartem** [comment]
👍Sent from my iPhoneOn Apr 15, 2024, at 8:21 AM, Old Dip Tracker ***@***.***> wrote:﻿
@patricklodder commented on this pull request.

Please note there are still some bitcoin artifacts that could be changed in:

qa/rpc-tests/test_framework/coverage.py:76
qa/rpc-tests/test_framework/util.py:303
qa/rpc-tests/test_framework/mininode.py:15
qa/rpc-tests/multi_rpc.py:27
qa/pull-tester/rpc-tests.py:338

For completeness, maybe the docs in qa/README.md and qa/rpc-tests/README.md should be amended too?
Other than that, tests pass x86_64 Ubuntu Jammy, and I left 2 inline comments about test comments that now make even less sense (but should not be fixed in this PR, imho)

In qa/rpc-tests/p2p-segwit.py:
>      # the test.
     def test_upgrade_after_activation(self, node, node_id):
         print("\tTesting software upgrade after softfork activation")
 
-        assert(node_id != 0) # node0 is assumed to be a segwit-active bitcoind
+        assert(node_id != 0) # node0 is assumed to be a segwit-active dogecoind

Note that this comment makes no sense. I think that it's not for this PR to fix (let's keep separation of concerns) but the backport debt is significantly greater than the name of the binary in a comment.



In qa/rpc-tests/p2p-compactblocks.py:
> @@ -396,7 +396,7 @@ def check_compactblock_construction_from_block(self, version, header_and_shortid
                 header_and_shortids.shortids.pop(0)
             index += 1
 
-    # Test that bitcoind requests compact blocks when we announce new blocks
+    # Test that dogecoind requests compact blocks when we announce new blocks

Note that the full comment block is not entirely valid for dogecoind. No need to change that now, but it can be misleading.

**Comment by chromatic** [comment]
I've pushed a new commit with review comments addressed.

**Review by patricklodder — APPROVED** [review]
ACK - tested on x86_64 Ubuntu 22.04

**Pull request merged**
