### PR TITLE
qt: display full version on overview screen

### PR DESCRIPTION
**Pull request by patricklodder**
Removes "1.14" that was embedded in the logo image on the overview screen and replaces it with a dynamically generated version (including revision number and commit short hash suffix) on the lower left side, laid over the transparent part of the logo. 

[This was flagged up on reddit](https://www.reddit.com/r/dogecoindev/comments/pxnj5y/what_if_we_ban_access_on_our_nodes_to_peers_not/hess0ph/) and I was told others saw this confusion when talking to people about what version they were running too.

### Screenshot
Screen Shot 2021-10-17 at 02 27 28

### CODE REVIEW

**Comment by patricklodder** [comment]
> Is there a way to give it the red text a white border, like the current image?

Could do that, it's just css

**Comment by rnicoll** [comment]
I'd definitely be up for removing it from the image, and putting it into the boundary. @patricklodder thoughts?

**Comment by qlpqlp** [comment]
Now that you all are talking about Logo abd UI improvments, what about the logo? any plans?
I have made this exemples now in a few minuts if you also want to change a bit more :) 
I can make it as an vector SVG on Inkscape or any susgestions to change a bit more :)
logos_exemple

**Comment by rnicoll** [comment]
Last time anyone tried changing the logo, it started a major flame war, so lets go with no plans currently.

**Comment by patricklodder** [comment]
This is what e0675aa looks like on a mac

Screen Shot 2021-10-17 at 02 27 28

**Comment by patricklodder** [comment]
Amended commit message to reflect the change as it is now.

**Comment by slightlyskepticalpotat** [comment]
image
Looks like this on Linux.

**Comment by qlpqlp** [comment]
> image
> Looks like this on Linux.

Dosent look so bad, you have maximized the window :)

For me the version display is a lot better and i like the cleaner Dogecoin logo :)

One questions. Should we move the logo and change the HOME icon with the Dogecoin Logo?

And inted of disaying the version above the status bar, if we move the verion to the Title Bar?

To arrange more space and also solve some resolutions problems?

Sorry @patricklodder :) 
 display

**Comment by rnicoll** [comment]
Lets not try having major visible changes on a minor release, cannot emphasise how much updating the look can be controversial and it has to be something the community is included in (which means doing polls).

I'm ambivalent on version in bottom-left vs title bar.

**Comment by rnicoll** [comment]
1 14 5-windows

Looking good on Windows

**Comment by patricklodder** [comment]
> Going to throw it through Gitian so I can see it on Windows too

Oh! You should be able to use the CI artifacts now (bar of course the usual antivirus false positive for having miner code in the exec) so that may save some time in the future! It's supposed to work similar to doing the gitian build for everything except macOS (where you will get a quadrillion more errors for missing code signing and all that.)

> And instead of displaying the version above the status bar, if we move the version to the Title Bar?

The title bar really is an OS artifact (so an OS can decide to not display it) and is meant to have identifying information so that the window manager can let the user know which window is what. Hence the `[testnet]` being useful, because it's possible to run both mainnet and testnet at the same time, but the version imho not so much because it's not trivial to run multiple versions on the same network at the same time and without doing datadir configuration the software will simply decline.

> One questions. Should we move the logo and change the HOME icon with the Dogecoin Logo?

That's a separate thing from this PR. I wouldn't do it on 1.14.x either - like @rnicoll said - because:

1. 1.21-dev contains proper decoupling of ui and the validator/wallet APIs. Once the basics are in that development branch, this makes it a much better candidate for re-skinning and optimizing the QT wallet look & feel. Doing it now will bring bigger issues with integration to that branch.
2. Shibes love their wallet look & feel more than anything else (even if it's quirky and ugly) and there are many artsy shibes in the communities. If anything, I expect that making the QT wallet "skinnable" would probably be something shibes love. We can probably decouple sexy-UI-development from boring-protocol-development completely, meaning that you wouldn't have to wait for a release of the core client to do a look & feel improvement.
3. 1.14 is going to be a maintenance-only branch that we keep for compatibility, soon, so it's like improving a dead end road.

**Comment by qlpqlp** [comment]
Thanks @patricklodder and @rnicoll :)
looking very good on Windows and Mac :)

**Comment by rnicoll** [comment]
@qlpqlp Want to open an issue against 1.21 to remind us to consider UI options? Definitely one we'll need wider input on, but we should come back to it.

**Comment by qlpqlp** [comment]
> @qlpqlp Want to open an issue against 1.21 to remind us to consider UI options? Definitely one we'll need wider input on, but we should come back to it.
> 

Sure :), thanks @rnicoll .
 Im collecting some improvments that will discuss later this new week on separeted posts. Will also prepare my C++ dev enviorment lol, litle rusty. Last time I code C++ was bettwin 1997 and 2004 I think lol

**Pull request merged**
