### PR TITLE
Update OpenSSL to 1.0.2o and update Qt download URL

### PR DESCRIPTION
**Pull request by gradinkov**

### CODE REVIEW

**Comment by gradinkov** [comment]
Oh boy you sure need to fix your CI.

**Comment by rnicoll** [comment]
We've focused on 1.14 (under the `1.14-dev` branch) for the CI fixes, although yes, yes we do.

**Comment by gradinkov** [comment]
Should I retarget this one to 1.14-dev?

**Comment by rnicoll** [comment]
Ideally could you raise it against 1.10-dev and 1.14-dev? I'll be catching up with Doge tomorrow and hope to get it merged then!

**Comment by gewure** [comment]
update?

**Comment by orhtej2** [comment]
This PR was superseded by !1630

**Pull request closed without merging**
