### PR TITLE
Call va_end() on va_started() args

### PR DESCRIPTION
**Pull request by chromatic**
This is equivalent to [Bitcoin's 5ba61f](https://github.com/bitcoin/bitcoin/commit/5ba61f0034597ffeedc8c44af5a6ec670b095d83); created by @kallewoof.

Addresses #2625 .

### CODE REVIEW

**Review by patricklodder — APPROVED** [review]
ACK. Tested to fix #2625, `cppcheck` no longer complains:

```
$ cppcheck src/zmq
Checking src/zmq/zmqabstractnotifier.cpp ...
Checking src/zmq/zmqabstractnotifier.cpp: ENABLE_ZMQ...
Checking src/zmq/zmqabstractnotifier.cpp: HAVE_CONFIG_H...
1/3 files checked 4% done
Checking src/zmq/zmqnotificationinterface.cpp ...
Checking src/zmq/zmqnotificationinterface.cpp: ENABLE_ZMQ...
Checking src/zmq/zmqnotificationinterface.cpp: HAVE_CONFIG_H...
2/3 files checked 48% done
Checking src/zmq/zmqpublishnotifier.cpp ...
Checking src/zmq/zmqpublishnotifier.cpp: ENABLE_ZMQ...
Checking src/zmq/zmqpublishnotifier.cpp: HAVE_CONFIG_H...
3/3 files checked 100% done
```

**Review by rnicoll — APPROVED** [review]
utACK

**Comment by rnicoll** [comment]
Thanks @chromatic & @patricklodder

**Comment by Star6654** [comment]
Thanks

**Pull request merged**
