### PR TITLE
Rename pixmaps

### PR DESCRIPTION
**Pull request by DemonRx**
### A little re-branding. 

Renaming of the pixmap files from bitcoin -> dogecoin; being that the files actually depict dogecoin's logo and not bitcoin.

Also making their references in other areas of the source to correctly point to these files.

This also resolves having to manually rename the referenced dogecoin128.png file for use with installing the linux dogecoin-qt.desktop file.

This matter was brought up without any objections to date: 
https://github.com/dogecoin/dogecoin/pull/1761#issuecomment-789664111

But more than open to input on this. Much fun :+1:

### CODE REVIEW

**Review by patricklodder — APPROVED** [review]

**Comment by patricklodder** [comment]
Would like one more ack please :-)

**Comment by langerhans** [comment]
This "fixes" the naming for mostly Linux and a bit of Windows. Do we intend to also change the name of the icons in src/qt/icons? Cause if we want to be consistent then we should (maybe in a new PR). But that's a lot of changes that need rebase with every major release 🤔 So a bit torn on this.

**Comment by patricklodder** [comment]
> Do we intend to also change the name of the icons in src/qt/icons?

These are compiled in though, so that has no direct exposure to the outside? Whereas the contrib/ files are actually exposed to users' filesystems and would be used by people packaging the binaries? Just thinking out loud...

**Comment by langerhans** [comment]
Okay, that sounds like a sensible differentiation 👍

**Review by langerhans — APPROVED** [review]

**Pull request merged**
