### PR TITLE
Fixate 1.14.8 for release

### PR DESCRIPTION
**Pull request by chromatic**
Tentative release date is August 3, 2024.

### CODE REVIEW

**Review by patricklodder — DISMISSED** [review]
ACK. I think the release date is fine.

Note: This should be merged after #3609 and #3612

**Review by patricklodder — CHANGES_REQUESTED** [review]
I missed that `CLIENT_VERSION_IS_RELEASE` also needs to be changed in `src/clientversion.h` - see a6d122013 for details.

**Comment by chromatic** [comment]
> I missed that `CLIENT_VERSION_IS_RELEASE` also needs to be changed in `src/clientversion.h`

At some point in the future, should we consider removing this duplication?

**Comment by patricklodder** [comment]
> At some point in the future, should we consider removing this duplication?

Of course. If I remember correctly, it's there for MSVC. I don't think that we're properly maintaining that platform in the first place, but if and when there is someone that does, we can definitely improve on this.

**Review by patricklodder — APPROVED** [review]
ACK - this is complete now

**Comment by patricklodder** [comment]
Marked as urgent as this would otherwise be holding up release unnecessarily. I'll merge in 1h unless there's reasonable objection.

**Comment by PayamShahmansour** [comment]
> Tentative release date is August 3, 2024.

**Comment by PlatinumWrist5055** [comment]
> Tentative release date is August 3, 2024.

Thanks appreciate this update

**Pull request merged**
