### PR TITLE
Change key derivation path to be correct for Dogecoin

### PR DESCRIPTION
**Pull request by micaelmalta**

### CODE REVIEW

**Comment by patricklodder** [comment]
What does this do to wallets that have been derived using the former path? Is there any impact to currently installed wallets?

**Comment by micaelmalta** [comment]
@patricklodder sorry, this PR should have been in DRAFT... We are working with @rnicoll on a solution for backward compatibility

**Comment by nikoulai** [comment]
> What does this do to wallets that have been derived using the former path? Is there any impact to currently installed wallets?

Hello
Would this impact already installed software somehow? (@micaelmalta )

**Comment by patricklodder** [comment]
> Would this impact already installed software somehow?

No. For the actually merged PR in #2490, HD Wallets generated pre-1.14.5 will simply continue using the derivation path that is specified in the file and aren't impacted.

**But be aware if you have made a lot of transactions with 1.14.0 - you need to check if you have any transactions that got stuck due to a bug in the logic in that version, see #2838 on how to remove the stuck transactions (or restart your wallet with `-zapwallettxs -rescan` command line parameters after you made sure that you don't have any pending transactions.)**

I'm preparing a guide document for people that are upgrading from 1.14.0

**Comment by nikoulai** [comment]
> > Would this impact already installed software somehow?
> 
> No. For the actually merged PR in #2490, HD Wallets generated pre-1.14.5 will simply continue using the derivation path that is specified in the file and aren't impacted.
> 
> **But be aware if you have made a lot of transactions with 1.14.0 - you need to check if you have any transactions that got stuck due to a bug in the logic in that version, see #2838 on how to remove the stuck transactions (or restart your wallet with `-zapwallettxs -rescan` command line parameters after you made sure that you don't have any pending transactions.)**
> 
> I'm preparing a guide document for people that are upgrading from 1.14.0

Thanks for the info :)

**Pull request closed without merging**
