### PR TITLE
Fix BerkeleyDB.5.1 MACOS

### PR DESCRIPTION
**Pull request by micaelmalta**

### CODE REVIEW

**Comment by micaelmalta** [comment]
https://github.com/dogecoin/dogecoin/issues/1948

**Comment by patricklodder** [comment]
I'm getting an error during configure stage of `make -C depends bdb` using this branch, I think the SDK version is the issue - not sure.

full verbose log from clang on the error:

```
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.8.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name conftest.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-strict-return -fno-rounding-math -munwind-tables -faligned-alloc-unavailable -fcompatibility-qualified-id-block-type-checking -fvisibility-inlines-hidden-static-local-var -target-cpu core2 -debugger-tuning=lldb -target-linker-version 650.9 -v -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5 -I /Users/patrick/dev/dogecoin/core/depends/x86_64-apple-darwin20.4.0/include -internal-isystem /usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -internal-externc-isystem /usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -O2 -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -fdebug-compilation-dir /Users/patrick/dev/dogecoin/core/depends/work/build/x86_64-apple-darwin20.4.0/bdb/5.1.29-29c4a72920c -ferror-limit 19 -stack-protector 1 -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcommon -fcolor-diagnostics -vectorize-loops -vectorize-slp -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -mllvm -disable-aligned-alloc-awareness=1 -o /var/folders/q0/_5h8n4c555vdfcxczw3bkqpc0000gn/T/conftest-8fc8b6.o -x c conftest.c
clang -cc1 version 12.0.5 (clang-1205.0.22.9) default target x86_64-apple-darwin20.4.0
ignoring nonexistent directory "/Users/patrick/dev/dogecoin/core/depends/x86_64-apple-darwin20.4.0/include"
ignoring nonexistent directory "/usr/include"
#include "..." search starts here:
#include <...> search starts here:
 /usr/local/include
 /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include
 /Library/Developer/CommandLineTools/usr/include
 /System/Library/Frameworks (framework directory)
 /Library/Frameworks (framework directory)
End of search list.
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -arch x86_64 -platform_version macos 10.8.0 0.0.0 -o a.out -L/Users/patrick/dev/dogecoin/core/depends/x86_64-apple-darwin20.4.0/lib /var/folders/q0/_5h8n4c555vdfcxczw3bkqpc0000gn/T/conftest-8fc8b6.o -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/lib/darwin/libclang_rt.osx.a
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

**Comment by rnicoll** [comment]
What's the status of this? Do we need it for OS X, was the SDK version wrong, the suspense is killing me!

**Comment by rnicoll** [comment]
@micaelmalta We're looking at moving to 5.3, does https://github.com/dogecoin/dogecoin/pull/2483 fix the Mac issue you were seeing?

**Comment by micaelmalta** [comment]
> @micaelmalta We're looking at moving to 5.3, does #2483 fix the Mac issue you were seeing?

https://github.com/dogecoin/dogecoin/pull/2483#issuecomment-904952250 :(

**Pull request closed without merging**
