### PR TITLE
Fix errors of bitcoin_fr_FR.ts file for 1.14.7 dev

### PR DESCRIPTION
**Pull request by Loopite**
You have few errors which were corrected. Now, the file is available at:

[bitcoin_fr_FR.txt](https://github.com/dogecoin/dogecoin/files/10252720/bitcoin_fr_FR.txt)

### CODE REVIEW

**Comment by patricklodder** [comment]
Hi! `master` is frozen per https://github.com/dogecoin/dogecoin#branches - it gets updated on release. I am closing this PR. If you want to build ahead of the release, please build with `1.14.7-dev` as a source.

**Comment by Loopite** [comment]
Ok I'm going to do this later. Thanks for the precision.

**Comment by patricklodder** [comment]
@Loopite We can do one of 2 things, let me know what you prefer:

1. I can look into your file and see if I can create a pull request in your name, or
2. I can work on a good guide (pref with some others) re: how to do a pull request

**Comment by Loopite** [comment]
> I can work on a good guide (pref with some others) re: how to do a pull request

I think it would be better. Then we'll be able to know what kind of branches are available as source. Meanwhile, I'll work this morning on the fr_FR translations.

**Pull request closed without merging**
