### PR TITLE
Update native_cctools and clang dependencies

### PR DESCRIPTION
**Pull request by rnicoll**
Rolls in earlier commits to minimize conflicts, as well. Helps with #2321.

Would be good to have manual checks on non-Ubuntu platforms (Mac)

### CODE REVIEW

**Comment by patricklodder** [comment]
This needs gitian checks

**Comment by mmicael1** [comment]
Let's validate this PR https://github.com/dogecoin/dogecoin/pull/2333 so I can test it locally!

**Comment by rnicoll** [comment]
This is on the long running test server now.

**Comment by micaelmalta** [comment]
Not running on Gitian MacOS:

```Preprocessing native_cctools...
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.4.3 or higher is required.  You are running version 2.8.12.2
```

**Comment by micaelmalta** [comment]
Trying this fix based on Bitcoin native_ctools

https://github.com/rnicoll/dogecoin/compare/1.14.4-native_cctools...micaelmalta:1.14.4-native_cctools?expand=1

**Comment by patricklodder** [comment]
> https://github.com/rnicoll/dogecoin/compare/1.14.4-native_cctools...micaelmalta:1.14.4-native_cctools?expand=1
> 
> Edit: Seems to be an issue with Gitian Trusty suite. Upgrading descriptor to Focal (Following Bitcoin descriptors) - If it s the case, a separate PR will be created just with Gitian Upgrade

The problem with that fix is that the minimum osx version gets updated to 10.14 - I think that's too much for a minor software update.

**Comment by rnicoll** [comment]
Do we know if there's a lower clang version that will work for Focal and has less of an OS X requirement jump?

**Comment by micaelmalta** [comment]
It has been upgraded to Cmake 3.4.3 on Clang 3.9. The only upgrade would be Clang 3.8

**Comment by rnicoll** [comment]
So are we basically in a position where supporting Focal means we have to change OS X release? Did we need Focal for GitHub Actions or was it desirable? Trying to find a path forward.

**Comment by patricklodder** [comment]
> So are we basically in a position where supporting Focal means we have to change OS X release? Did we need Focal for GitHub Actions or was it desirable? Trying to find a path forward.

I have yet no solution to do it in focal without the SDK update. If we can't do that, we have to look into alternatives:

The only card we can play here is to take a step back and use bionic for 1.14, keep using focal for 1.21 - which seems to work for CI, but I'm not 100% sure about gitian, yet.

**Comment by patricklodder** [comment]
removed from 1.14.4 target milestone - hopefully we can move away from trusty gitian builds with 1.14.5 and then this becomes relevant again.

**Pull request closed without merging**
