### PR TITLE
Update to Berkeley DB 5.3

### PR DESCRIPTION
**Pull request by bjacquin**
Old BerkeleyDB version such as 5.1 are being removed from most Linux distribution.

See: https://bugs.gentoo.org/792222
See: https://fedoraproject.org/wiki/Changes/Libdb_deprecated

There was a previous attempt made in https://github.com/dogecoin/dogecoin/pull/2245 however the pull request seems to be containing a lot of changes at once making the review and merge more difficult.

### CODE REVIEW

**Comment by patricklodder** [comment]
Hi!

Difference between #2245 and this is also that the former was targeting the next major release whereas this is built upon the 1.14 codebase, meaning it's next minor release. 

Do you have any insights about portability from a file created with 5.3 towards software compiled with 5.1? No problem is not, just means we have to find out and/or build some tooling.

**Comment by rnicoll** [comment]
Created a build against 5.3 to test:

```
$ ldd src/dogecoind
        linux-vdso.so.1 (0x00007ffcd4d40000)
        libboost_filesystem.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0 (0x00007fa46344e000)
        libboost_program_options.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0 (0x00007fa4633bf000)
        libboost_thread.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.71.0 (0x00007fa463393000)
        libboost_chrono.so.1.71.0 => /usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.71.0 (0x00007fa463385000)
        libdb_cxx-5.3.so => /usr/lib/x86_64-linux-gnu/libdb_cxx-5.3.so (0x00007fa4631ad000)
```

Got an account on 5.3 and dumped the private key so I'd have it:

```
$ ./src/dogecoin-cli  getaccountaddress ""
nmBvdWEfj27uCCVVBnfaCNecDKgSGUdShy
$ ./src/dogecoin-cli  dumpprivkey nmBvdWEfj27uCCVVBnfaCNecDKgSGUdShy
[redacted]
```

Then downloaded 1.14.4 official, verified it's statically compiled so won't use the BDB on the host, and ran the same commands, same result. So 5.3 wallet downgrading to 5.1 works.

Then did the opposite; delete the wallet, create a new wallet file with 5.1, dump private key, open the wallet with DB 5.3 and verify dumping the private key works.

Just about to do another cycle of 5.3 to 5.1 to be really really sure.

**Comment by rnicoll** [comment]
5.3 to 5.1 downgrade re-confirmed. I'd like someone to do a Gitian build with this just in case, but LGTM in theory.

**Comment by ReverseControl** [comment]
@rnicoll Which branch for the gitian build?

**Comment by micaelmalta** [comment]
@rnicoll 

```
db53
6134db1c49cd3743e7f60a987dad420cbceae007ce594205fb5d1ab5a0467035  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
a11883b152f118d88bc62137004f8aeedc5428fccf60c8b3ac3326b11340b47a  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
efcd928b1c1a5e511e185b20c4a0abc3ee5b8a22edec58efd45aac2e2c5b7906  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
e0953a670dadbc5f7acd602246ecb92aa99d3e7c33733cb73b4ec8519b5e86f9  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
054da8bdee811e3233228b2d4e0cc138282e750fe6c79b21eb594f6944b01fad  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
cfa7554483024c71f009680bb374d611d4ccd15b72bc4ed72eed4acd98e7eb6b  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
84f044d716afffa84b3ea3e94bdb1c96b1bcfff3351aca0b72d8cd27c820bd05  dogecoin-1.14.4-osx64.tar.gz
3d3be99608374192f8bb1cf79d7819aa77ea9078dc1b1dc7b578bd5141df48e7  dogecoin-1.14.4-osx-unsigned.dmg
3297c6eff33c9b6b16f7cc15e2b9ae87530868698c194d16156a5d06d395e1b8  dogecoin-1.14.4-osx-unsigned.tar.gz
79470c5615a212d88fe56d0079dbd4bd21ada3264e224f6e7accf8a004c32af9  dogecoin-1.14.4.tar.gz
23d7c119c3116a64263ca06a863084231381a0163e63154fa1fbf3cf4f1e6a32  dogecoin-1.14.4-win32-debug.zip
63cb07193423182fa98805a8677b250df943cc0367e67066c416cbb649cce945  dogecoin-1.14.4-win32-setup-unsigned.exe
87e2940fc5149c5e8766a9dc08236404c30087b8c16ea12918d3f7eb8a8a0a84  dogecoin-1.14.4-win32.zip
78747d59fdd3957740d427f3871fa5e7506136f06b4c6022e2f6f66e060feedc  dogecoin-1.14.4-win64-debug.zip
aa5a1cc13c12225ce1769b888887aa461b76da8ccbdeed7c44c15aa203fde3e8  dogecoin-1.14.4-win64-setup-unsigned.exe
6a3cd7ba67f1dffeffae539f9634e881d420f1a37f0d749cbfd111c5beb311cf  dogecoin-1.14.4-win64.zip
56d55acd1a19c18a3638ba19c56909c7c0f95028dd354161fc29e24cc120daba  dogecoin-1.14.4-win-unsigned.tar.gz
7bfcf9e20209ebdcd6ecb917fc050fdc53a0db6f6922f3efa83c49f778411d78  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
710d00dce328b72dab9ae34ffdd218bf6478f4a3e93a4c39d16a09e002643e3d  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
```

**Comment by rnicoll** [comment]
> 
> 
> @rnicoll Which branch for the gitian build?

Sorry just saw this, my notifications are weird, no idea how I've broken tagging me in comments. I think looks like Micael this covered, but thanks!

**Review by rnicoll — APPROVED** [review]
I'm in favour, but want to give this 24-48 hours for others to comment just in case.

**Comment by patricklodder** [comment]
Since some of the build documentation has changed, I'm verifying that. I also need a second gitian build to verify determinism, will set that up to run.

**Comment by patricklodder** [comment]
Gitian checksums match:

```
6134db1c49cd3743e7f60a987dad420cbceae007ce594205fb5d1ab5a0467035  dogecoin-1.14.4-aarch64-linux-gnu-debug.tar.gz
a11883b152f118d88bc62137004f8aeedc5428fccf60c8b3ac3326b11340b47a  dogecoin-1.14.4-aarch64-linux-gnu.tar.gz
efcd928b1c1a5e511e185b20c4a0abc3ee5b8a22edec58efd45aac2e2c5b7906  dogecoin-1.14.4-arm-linux-gnueabihf-debug.tar.gz
e0953a670dadbc5f7acd602246ecb92aa99d3e7c33733cb73b4ec8519b5e86f9  dogecoin-1.14.4-arm-linux-gnueabihf.tar.gz
054da8bdee811e3233228b2d4e0cc138282e750fe6c79b21eb594f6944b01fad  dogecoin-1.14.4-i686-pc-linux-gnu-debug.tar.gz
cfa7554483024c71f009680bb374d611d4ccd15b72bc4ed72eed4acd98e7eb6b  dogecoin-1.14.4-i686-pc-linux-gnu.tar.gz
3d3be99608374192f8bb1cf79d7819aa77ea9078dc1b1dc7b578bd5141df48e7  dogecoin-1.14.4-osx-unsigned.dmg
3297c6eff33c9b6b16f7cc15e2b9ae87530868698c194d16156a5d06d395e1b8  dogecoin-1.14.4-osx-unsigned.tar.gz
84f044d716afffa84b3ea3e94bdb1c96b1bcfff3351aca0b72d8cd27c820bd05  dogecoin-1.14.4-osx64.tar.gz
23d7c119c3116a64263ca06a863084231381a0163e63154fa1fbf3cf4f1e6a32  dogecoin-1.14.4-win32-debug.zip
87e2940fc5149c5e8766a9dc08236404c30087b8c16ea12918d3f7eb8a8a0a84  dogecoin-1.14.4-win32.zip
78747d59fdd3957740d427f3871fa5e7506136f06b4c6022e2f6f66e060feedc  dogecoin-1.14.4-win64-debug.zip
6a3cd7ba67f1dffeffae539f9634e881d420f1a37f0d749cbfd111c5beb311cf  dogecoin-1.14.4-win64.zip
7bfcf9e20209ebdcd6ecb917fc050fdc53a0db6f6922f3efa83c49f778411d78  dogecoin-1.14.4-x86_64-linux-gnu-debug.tar.gz
710d00dce328b72dab9ae34ffdd218bf6478f4a3e93a4c39d16a09e002643e3d  dogecoin-1.14.4-x86_64-linux-gnu.tar.gz
79470c5615a212d88fe56d0079dbd4bd21ada3264e224f6e7accf8a004c32af9  dogecoin-1.14.4.tar.gz
```

**Comment by rnicoll** [comment]
Okay to merge?

**Comment by patricklodder** [comment]
> Okay to merge?

Yeah - 5.3 in itself looks good with the minimal testing we've given it. As we anyway have to work on the docs, we can work these as we go.

**Review by patricklodder — APPROVED** [review]
utACK. Have to give it a bit more test love but this can be done separately, unlikely we'd reverse the upgrade.

**Comment by micaelmalta** [comment]
@patricklodder @rnicoll I have an error building locally on MacOS

`checking for mutexes... UNIX/fcntl
configure: error: Support for FCNTL mutexes was removed in BDB 4.8.
make: *** [/Users/m.malta/development/dogecoin/depends/work/build/x86_64-apple-darwin20.6.0/bdb/5.3.28-63cd6a1bbc4/build_unix/.stamp_configured] Error 1
`

**Comment by rnicoll** [comment]
@micaelmalta I've found https://trac.macports.org/ticket/61409 which has https://github.com/macports/macports-ports/commit/b661c0e483b08cd4d19a1d50dfc8ebbe93966631 as a potential solution, although a little terrifyingly large. Can you take a look and see if that can fix it for Mac?

**Comment by mmalta-daily** [comment]
It means that the day we add it on either Gitian builds or CI, it s gonna fail :(

Will have a look

**Comment by micaelmalta** [comment]
It means that the day we add it on either Gitian builds or CI, it s gonna fail :(

Will have a look

**Review by dgs2019 — COMMENTED** [review]
[[Testing E2E Android](https://github.com/invertase/react-native-firebase/actions/workflows/tests_e2e_android.yml)]([Testing E2E Android](https://github.com/invertase/react-native-firebase/actions/workflows/tests_e2e_android.yml))

**Comment by ReverseControl** [comment]
@patricklodder What is the status of this?

**Pull request merged**
