### PR TITLE
Update build fedora.md

### PR DESCRIPTION
**Pull request by FierceSkit**
Hey!
I've been updating the Guide to include Fedora 39.
Tested on Fedora (x86 & ARM)

### CODE REVIEW

**Comment by patricklodder** [comment]
This is useful, especially because we've fixed the openssl3 issues with 1.14.7.

I want to test 35-38 with the 39 instructions, because these should work uniformly now.

**Comment by georgeartem** [comment]
does this re-open #3417 ?

**Comment by georgeartem** [comment]
answered my own question by looking at the minimum version of Fedora in #3417

**Comment by patricklodder** [comment]
> looking at the minimum version of Fedora in https://github.com/dogecoin/dogecoin/pull/3417

That's the minimum version used for running the release binaries though, I don't encourage going that far back in testing compiles.

**Comment by patricklodder** [comment]
The "Fedora 39" build instructions work for ALL versions since 35 thanks to #3079 and #3058.

I've tested this with the following docker template and script:

```Dockerfile
FROM fedora:VERSION
WORKDIR /build                                                                  

RUN dnf install -y gcc-c++ libtool which diffutils make autoconf automake \
                openssl-devel libevent-devel boost-devel libdb-cxx-devel git

# checkout aa53a0d77c47a0b89d83a4a80fd44d917c82bd04 from 1.14.7-dev
RUN git clone https://github.com/dogecoin/dogecoin.git \
 && cd dogecoin \
 && git checkout aa53a0d77c47a0b89d83a4a80fd44d917c82bd04

WORKDIR /build/dogecoin

RUN ./autogen.sh \
 && ./configure --without-gui \
 && make -j8
```

```bash
for v in 35 36 37 38 39; do cat Dockerfile.template | sed s/VERSION/${v}/ | docker build -; done
```

---

@FierceSkit could you please remove the specific instructions per version and simply reduce it to only the one you created for 39? "Tested on" can be changed to "35-39"

**Comment by patricklodder** [comment]
Needs a squash - shall I do that for you?

**Comment by FierceSkit** [comment]
> Needs a squash - shall I do that for you?

Yep!

**Review by patricklodder — APPROVED** [review]
ACK - tested on Fedora 35-39

Needs ACK from another maintainer to check the squash

**Comment by chromatic** [comment]
Contents look fine pre- and post-squash. I'm compiling and running tests before I approve.

**Comment by chromatic** [comment]
I see one failure, but I think it's due to load on the box and not this PR:

```
bumpfee.py:                                                
Initializing test directory /tmp/testzcfyax8r/482
Mining blocks...                             
Running tests                                
Assertion failed:                                          
Stopping nodes                                
Not cleaning up dir /tmp/testzcfyax8r/482    
Failed                                       
                                                           
stderr:                                      
  File "/home/chromatic/dev/dogecoin/qa/rpc-tests/test_framework/test_framework.py", line 145, in main
    self.run_test()                           
  File "/home/chromatic/dev/dogecoin/qa/rpc-tests/bumpfee.py", line 66, in run_test
    test_segwit_bumpfee_succeeds(rbf_node, dest_address)
  File "/home/chromatic/dev/dogecoin/qa/rpc-tests/bumpfee.py", line 127, in test_segwit_bumpfee_succeeds
    assert bumped_tx["txid"] in rbf_node.getrawmempool()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
```

I cannot reproduce that running the test directly in a loop, so I'm comfortable approving this unless you see otherwise @patricklodder.

**Comment by patricklodder** [comment]
> I see one failure, but I think it's due to load on the box and not this PR

This PR does not change code, so unless you can prove that code for compilation reads this file, I think your assessment is correct. 

But to entertain the bug: This is one of the tests that needs to be reworked for reliability. In this case, the test has a race condition between the `bumpfee` and `getrawmempool` calls in the context of sync processing of mempool updates (the former returns a lock, script moves on to the latter, then that locks the mempool so that the update cycle waits - perhaps it was doing a `txmempool::check`, which happens randomly). The latter python assertion should be replaced by a `wait_until` that loops through `getrawmempool` with a timeout until it has it.

**Review by chromatic — APPROVED** [review]
ACK, code compiles cleanly and tests pass (after re-running) on x86-64 Linux.

**Pull request merged**
