### PR TITLE
snap packaging for 1.14.6

### PR DESCRIPTION
**Pull request by slightlyskepticalpotat**
Please do not merge this yet, I will leave this as a draft until later in the release cycle in case any dependencies change.

Changes:
- Increment version number
- Make i386 and arm64 systems consistently build
- Add the tx and test binaries
- Update dependencies

### CODE REVIEW

**Comment by chromatic** [comment]
@slightlyskepticalpotat We're getting close to the 1.14.6 release. How can I help get this out of draft?

**Comment by patricklodder** [comment]
I think that re: 

> Update dependencies

we have to make a decision on #2409 - it works fine for me but we have to gitian-build it for that to make it in.

**Comment by chromatic** [comment]
With #2409 approved, this should now be unblocked.

**Review by patricklodder — COMMENTED** [review]
Got this to work on x86_64, by:
- changing line 2 on `snapcraft.yml` back to `1.14.5`.
- using stable snapcraft (`sudo snap install snapcraft`, i.e. without the `classic`)
- Built it not with `multipass` but with `lxd` by supplying `--use-lxd` because multipass doesn't like my Ubuntu 22.04 install and vice versa
- Install with `--devmode` works.

However, when installing without `--devmode`, I get an error:

```console
$ sudo snap install dogecoin-core_1.14.5_amd64.snap 
error: cannot find signatures with metadata for snap
       "dogecoin-core_1.14.5_amd64.snap"
```

for now, soft NAK because I think the process needs some work and the inclusion of this in `contrib` is not optimal. I would be okay to host this on a separate repository under the `dogecoin` organization instead, so that we can decouple the release cycle here of Dogecoin Core itself from the snap release cycle.

**Comment by patricklodder** [comment]
Moved to blocking because this blocks release until we either decide to include it, or postpone it to next release.

Personally am inclined to not include it, but that may be because I don't use snap - would like more opinions.

**Comment by chromatic** [comment]
I ran into some errors trying to test this:

```
2022-07-16T13:59:17-07:00 INFO Waiting for automatic snapd restart...
snapd 2.56.2 from Canonical✓ installed
"snapd" switched to the "latest/stable" channel

core18 20220428 from Canonical✓ installed
core20 20220527 from Canonical✓ installed
"core20" switched to the "latest/stable" channel

snapcraft 7.0.11 from Canonical✓ installed
"snapcraft" switched to the "latest/stable" channel

bash: line 0: cd: /root/project/: Permission denied                             
bash: line 0: cd: /root/project/: Permission denied
Run the same command again with --debug to shell into the environment if you wish to introspect this failure.
An error occurred when trying to execute 'sudo -H -i env SNAPCRAFT_BUILD_ENVIRONMENT=managed-host HOME=/root SNAPCRAFT_HAS_TTY=True snapcraft snap' with 'multipass': returned exit code 1.
```

**Comment by chromatic** [comment]
:+1: from me to decouple the packaging from the release cycle. A separate repository to handle packaging would be interesting; it could include things like the Dockerfiles we were experimenting with for the Arch/RHEL build instructions, or BSD packaging, etc.

**Comment by patricklodder** [comment]
Alright. I'll take this out of the queue for now but leave the PR open, put back do-not-merge

@slightlyskepticalpotat are you interested in / available for maintaining this with us on a separate repo?

**Comment by patricklodder** [comment]
@slightlyskepticalpotat no probs. I'll do a proposal later this week on the new repository. Will close this right now, but won't forget.... because I put it in my calendar for Saturday 😂

dontforget

**Comment by slightlyskepticalpotat** [comment]
Hi, did the repository ever get created? I searched through my emails today
and couldn't find any notification. 😅

**Comment by patricklodder** [comment]
Not yet, will prioritize this to be done this week.

**Comment by slightlyskepticalpotat** [comment]
Going to start testing with the goal of having a working package for 1.14.6
in the next week or so.

**Comment by slightlyskepticalpotat** [comment]
??? I commented that on August 26 through email, not sure why it just went
through in the middle of the night.

**Comment by patricklodder** [comment]
> not sure why it just went through in the middle of the night.

Multiple emails got delivered the past couple of hours - GitHub quirk 🤷🏻‍♀️

**Pull request closed without merging**
