### PR TITLE
Improved gitian build script

### PR DESCRIPTION
**Pull request by patricklodder**
Squash of #2579 from @AbcSxyZ, which is integration work on top of #2396.

I couldn't maintainer-squash that PR without losing merge audit trail because the source fork has been deleted, so we'll have to do it this way. I have reviewed and tested #2579 thoroughly.

### CODE REVIEW

**Comment by patricklodder** [comment]
Blocks (because we have no gitian testers and this simplifies gitian testing greatly): #2409, #2910, #2936

**Comment by chromatic** [comment]
I'm testing this now. I had to comment out the line `RUN echo 'Acquire::http { Proxy "$MIRROR_BASE"; };' > /etc/apt/apt.conf.d/50cacher` in `gitian-builder/bin/make-base-vm` so that the `apt-get` commands would work in the Ubuntu Dockerfile.

**Comment by patricklodder** [comment]
> I had to comment out the line [..] so that the `apt-get` commands would work in the Ubuntu Dockerfile.

That implies we need an additional instruction re: `apt-cacher-ng`. What distro/version is your host?

**Comment by xanimo** [comment]
I tested this script using docker yesterday to build v1.14.5 and everything worked fine once it got started. I encountered 2 issues at first though, 1) being instructions indicating execution of script within contrib which when followed inadvertently overwrite the gitian descriptor for osx which I solved by executing one level below the repo e.g. `./dogecoin/contrib/gitian-build.sh` and 2) reinstalling apt-cacher-ng and ensuring it was configured to allow download via http proxy and was up and running when I began to build. 

Outside that the process was relatively seamless, the checksums all seem to match when verified with core dev sigs with exception to abc, fdov and my signatures which I'm assuming have to do with being added to 1.14.6-dev after the tag and release. That was really the only area of concern for me but all in all it works as intended. Let me know if you all would like a link to a gist with the build output or anything else.

**Comment by patricklodder** [comment]
> Let me know if you all would like a link to a gist with the build output or anything else.

Thanks! Which OS & version did you run this on? I want to try and repro the apt cacher issue.

**Comment by chromatic** [comment]
> What distro/version is your host?

Ubuntu 21.10 running on Intel x86/64.

**Comment by xanimo** [comment]
> > Let me know if you all would like a link to a gist with the build output or anything else.
> 
> Thanks! Which OS & version did you run this on? I want to try and repro the apt cacher issue.

I am on x86_64 running impish as well. The service was installed but was not running and I couldn't start despite many attempts at restarting, hence my defaulting to a clean reinstallation.

**Comment by patricklodder** [comment]
I changed 2 things:

1. Added instructions to enable apt-cacher properly, and help select the right choice when asked about tunnels
2. Changed the source for the 3 additional files we need on top of depends, from Bitcoin Core's dependency host to ours.

Verified that this works on both impish and focal.

**Comment by patricklodder** [comment]
I changed 2 things:

1. Added instructions to enable apt-cacher properly, and help select the right choice when asked about tunnels
2. Changed the source for the 3 additional files we need on top of depends, from Bitcoin Core's dependency host to ours.

Verified that this works on both impish and focal.

**Comment by patricklodder** [comment]
Also changed the example to 1.14.5 instead of 1.14.4 because the latter uses trusty.

**Comment by chromatic** [comment]
Using 1.14.5 as the target version seems to work a lot better. Things are building now.

**Comment by patricklodder** [comment]
I was thinking that perhaps, after we make sure the build works, we can also do a run against a commit as that is also supplied by this script, i.e. try to run it against #2936? Then we know it's 100% good, and as a plus, we unblock that PR in one go 😁.

**Comment by chromatic** [comment]
:+1: to that plan!

**Comment by chromatic** [comment]
I'm testing this against #2936 as well now. If I confirm the results, I'll approve this.

**Review by chromatic — APPROVED** [review]
ACK; built and confirmed file checksums against those in PR 2936.

**Pull request merged**
