### PR TITLE
[Auto] docs: ThreadGetMyExternalIP has been removed

### PR DESCRIPTION
**Pull request by rnicoll**
It was removed in https://github.com/bitcoin/bitcoin/pull/5161

### CODE REVIEW

**Comment by rnicoll** [comment]
ACK

**Comment by patricklodder** [comment]
Seems like we still got this one: https://github.com/dogecoin/dogecoin/blob/1.9-dev/src/net.cpp#L1714

postponing merge for consistency :)

**Comment by langerhans** [comment]
Merge after #1120

**Comment by rnicoll** [comment]
Abandoning 1.9 development branch in favour of 1.10.

**Pull request closed without merging**
